import {integrationSetup} from '@/app/integration-config';
import {invalidMutationOrigin} from '@/app/request-origin';
import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess} from '@/app/company-access';
import {canAccess} from '@/app/permissions';
import {beginGmail,gmailReady,syncGmail,decryptToken} from '@/app/gmail-service';
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
async function context(){const user=await getChatGPTUser();if(!user)return null;const access=await getCompanyAccess(user);return !access.blocked&&access.role!=='member'?{user,access,db:companyDb()}:null;}
export async function GET(req?:NextRequest){const c=await context();if(!c)return fail('Administrator access is required.',403);try{const row:any=await c.db.prepare('SELECT email,enabled,last_sync,last_error,cursor,refresh_token FROM gmail_connections WHERE owner=?').bind(c.access.owner).first();const setup=integrationSetup('gmail',req?.nextUrl.origin);return NextResponse.json({setup,ready:setup.ready,canUseCosts:canAccess(c.access,'Costs'),connected:!!row?.refresh_token,email:row?.email||'',enabled:!!row?.enabled,lastSync:row?.last_sync||'',lastError:row?.last_error||'',hasMore:!!row?.cursor});}catch{return fail('Could not load the Gmail connection.',503);}}
export async function POST(req:NextRequest){if(invalidMutationOrigin(req))return fail('Invalid request origin.',403);const c=await context();if(!c)return fail('Administrator access is required.',403);try{const b:any=await req.json();if(b.action==='connect'){if(!integrationSetup('gmail',req.nextUrl.origin).ready)return fail('Complete Gmail setup for this site before connecting.');return NextResponse.json({url:await beginGmail(c.access.owner,c.user.userId)});}
 if(b.action==='disconnect'){const row:any=await c.db.prepare('SELECT refresh_token FROM gmail_connections WHERE owner=?').bind(c.access.owner).first();await c.db.batch([c.db.prepare("UPDATE gmail_connections SET refresh_token='',enabled=0,lock_until=0,last_error='',cursor='',updated=? WHERE owner=?").bind(new Date().toISOString(),c.access.owner),c.db.prepare('DELETE FROM gmail_oauth_states WHERE owner=?').bind(c.access.owner)]);let revoked=true;if(row?.refresh_token){try{const token=await decryptToken(row.refresh_token,c.access.owner);const res=await fetch('https://oauth2.googleapis.com/revoke',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token}),signal:AbortSignal.timeout(10000)});revoked=res.ok;}catch{revoked=false;}}return NextResponse.json({ok:true,message:revoked?'Gmail disconnected. Imported invoices remain available.':'Disconnected in PLAN.FLO. Remove access in your Google account to finish revoking permission.'});}
 if(!canAccess(c.access,'Costs'))return fail('Enable Costs in App settings before using invoice matching.',403);
 if(b.action==='enable'){if(typeof b.enabled!=='boolean')return fail('Choose whether invoice matching is enabled.');const result=await c.db.prepare("UPDATE gmail_connections SET enabled=?,updated=? WHERE owner=? AND refresh_token<>''").bind(b.enabled?1:0,new Date().toISOString(),c.access.owner).run();if(!result.meta.changes)return fail('Connect Gmail first.');return NextResponse.json({ok:true});}
 if(b.action==='sync')return NextResponse.json(await syncGmail(c.access.owner));return fail('Unknown action.');}catch(e:any){return fail(e.message||'Could not update Gmail.',400);}}
