'use client';
import {useState,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,ClipboardList,Clock3,FileQuestion,FolderOpen,LayoutDashboard,ListTodo,LockKeyhole,Menu,Receipt,ShoppingCart,Users,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {StageProgress} from '../stage-progress';
import type {DemoData} from './demo-data';
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);
const day=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
const views=[['Overview',LayoutDashboard],['Costs',Receipt],['Variations',FolderOpen],['RFIs',FileQuestion],['Time Sheets',Clock3],['Tasks',ListTodo],['Site Diary',ClipboardList],['Purchase Orders',ShoppingCart],['Drawings',FolderOpen]] as const;
type View=typeof views[number][0];
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="demo-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;}
function Status({value}:{value:string}){return <span className={'demo-status '+(['Approved','Responded','Complete'].includes(value)?'done':'')}>{value}</span>;}
function Detail({title,children}:{title:string;children:ReactNode}){return <Dialog><DialogTrigger asChild><Button variant="outline" aria-label={'View '+title}>View <ArrowRight size={14}/></Button></DialogTrigger><DialogContent className="demo-detail"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Fictional sample record · Private, view-only demonstration</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>;}
function Table({caption,head,children}:{caption:string;head:string[];children:ReactNode}){return <div className="demo-table-wrap" role="region" aria-label={caption} tabIndex={0}><table className="demo-table"><caption>{caption}</caption><thead><tr>{head.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
export default function DemoWorkspace({data:d}:{data:DemoData}){
 const [view,setView]=useState<View>('Overview'),[menu,setMenu]=useState(false),[week,setWeek]=useState('2026-09-28');const t=d.totals;
 function open(next:View){setView(next);setMenu(false);}
 const weeks=['2026-09-07','2026-09-14','2026-09-21','2026-09-28'];const weekEnd=new Date(Date.parse(week+'T00:00:00Z')+7*86400000).toISOString().slice(0,10),entries=d.timesheets.filter(e=>e.date>=week&&e.date<weekEnd),weekHours=entries.reduce((s,e)=>s+e.hours,0);
 return <div className="app private-demo"><aside className={'sidebar demo-sidebar '+(menu?'show':'')} aria-label="Private demo navigation"><a className="brand planflo-brand" href="/" aria-label="Return to live workspace"><img src="/planflo-icon.svg" alt=""/><span className="planflo-wordmark"><strong>PLAN.<span>FLO</span></strong><small>Plan. Manage. Deliver.</small></span></a><div className="demo-company"><span className="demo-badge"><LockKeyhole size={13}/>Private demo</span><strong>{d.company}</strong><small>{d.project.name}</small></div><nav aria-label="Demo project sections">{views.map(([name,Icon])=><button type="button" key={name} className={'side-item '+(view===name?'active':'')} aria-current={view===name?'page':undefined} onClick={()=>open(name)}><Icon size={18}/>{name}</button>)}</nav><div className="demo-sidebar-footer"><p>All people, records and figures are fictional. No live workspace data.</p><a href="/" className="side-item"><ArrowLeft size={17}/>Back to workspace</a></div></aside>{menu&&<button className="scrim" aria-label="Close demo navigation" onClick={()=>setMenu(false)}/>}
 <div className="main"><header className="demo-topbar"><Button variant="ghost" size="icon" className="demo-menu" aria-label={menu?'Close demo navigation menu':'Open demo navigation'} onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</Button><span>Private demo / {view}</span><a href="/">Exit demo <ArrowRight size={15}/></a></header><main className="content demo-content"><div className="demo-notice" role="note"><LockKeyhole size={19}/><div><strong>Fictional sample data · View-only</strong><p>Only your verified owner account can open this demo. No real staff accounts, invitations, emails or integrations are connected.</p></div></div><div className="page-heading demo-heading"><div><div className="eyebrow">{d.company} · {d.project.number}</div><h1>{d.project.name}</h1><p>{view} · Sample position at {day(d.asOf)} · All money in AUD, ex GST</p></div><span className="demo-badge">DEMO</span></div>
 {view==='Overview'&&<><div className="demo-metrics"><Metric label="Revised contract" value={money(t.revisedContract)} note={`${money(t.baseContract)} base + ${money(t.approvedVariations)} approved`}/><Metric label="Actual cost to date" value={money(t.actualCost)} note={`${money(t.actualLabour)} labour + ${money(t.actualMaterials)} materials`}/><Metric label="Hours used" value={String(t.actualHours)} note={`of ${t.budgetHours.toLocaleString('en-AU')} budgeted hours`}/><Metric label="Pending variation" value={money(t.pendingVariations)} note="Excluded from revised contract"/></div><StageProgress projectId={d.project.id} definitions={d.project.stageDefinitions} version={0} stages={d.project.stageProgress} editable={false} onChanged={async()=>{}}/><div className="demo-two"><section className="demo-panel"><h2>Budget and actual costs</h2>{[['Labour',t.actualLabour,t.budgetLabour],['Materials',t.actualMaterials,t.budgetMaterials]].map(([name,actual,budget])=><div className="demo-cost-chart" key={String(name)}><div><strong>{name}</strong><span>{money(Number(actual))} / {money(Number(budget))}</span></div><div className="demo-bar" role="img" aria-label={`${name}: ${money(Number(actual))} actual of ${money(Number(budget))} budget`}><span style={{width:`${Number(actual)/Number(budget)*100}%`}}/></div></div>)}<p>{money(t.remainingBudget)} of the approved cost budget remains, including outstanding commitments. Stage completion is independent of hours and spend.</p><Button variant="outline" onClick={()=>open('Costs')}>View costs <ArrowRight size={16}/></Button></section><section className="demo-panel"><h2>Needs attention</h2><button className="demo-attention" onClick={()=>open('RFIs')}><span><strong>{d.rfis.filter(r=>r.status==='Issued').length} RFI awaiting a response</strong><small>Office communications cabinet location</small></span><ArrowRight size={17}/></button><button className="demo-attention" onClick={()=>open('Variations')}><span><strong>{d.variations.filter(v=>v.status==='Pending').length} pending variation</strong><small>{money(t.pendingVariations)} not yet approved</small></span><ArrowRight size={17}/></button><button className="demo-attention" onClick={()=>open('Tasks')}><span><strong>{d.tasks.filter(task=>task.status!=='Complete').length} open tasks</strong><small>Fit-off, coordination and handover preparation</small></span><ArrowRight size={17}/></button></section></div></>}
 {view==='Costs'&&<><div className="demo-metrics"><Metric label="Labour budget" value={money(t.budgetLabour)} note={`${t.budgetHours} hours at a blended $75 cost allowance`}/><Metric label="Materials budget" value={money(t.budgetMaterials)} note="Includes the approved sample variation scope"/><Metric label="Actual costs" value={money(t.actualCost)} note="Calculated from sample hours and expenses"/><Metric label="Budget remaining" value={money(t.remainingBudget)} note="Budget less actual costs; not a completion forecast"/></div><section className="demo-panel"><h2>Cost reconciliation</h2><Table caption="Approved budget versus actual costs" head={['Category','Budget','Actual','Remaining']}><tr><th scope="row">Labour</th><td>{money(t.budgetLabour)}</td><td>{money(t.actualLabour)}</td><td>{money(t.budgetLabour-t.actualLabour)}</td></tr><tr><th scope="row">Materials</th><td>{money(t.budgetMaterials)}</td><td>{money(t.actualMaterials)}</td><td>{money(t.budgetMaterials-t.actualMaterials)}</td></tr><tr><th scope="row">Total</th><td>{money(t.budgetCost)}</td><td>{money(t.actualCost)}</td><td>{money(t.remainingBudget)}</td></tr></Table><p>The current budget covers the base scope and both approved variations. The pending {money(t.pendingVariations)} variation is excluded. The {money(d.purchaseOrder.amount)} outstanding order is a commitment, not an expense; uncommitted materials budget is {money(t.uncommittedMaterials)}.</p></section><section className="demo-panel"><h2>Material expenses</h2><Table caption="Fictional material expense records" head={['Date','Reference / supplier','Description','Amount']} >{d.expenses.map(e=><tr key={e.id}><td>{day(e.date)}</td><td><strong>{e.reference}</strong><small>{e.supplier}</small></td><td>{e.description}</td><td>{money(e.amount)}</td></tr>)}</Table><p>Sample references only. No real invoice files or supplier accounts are attached.</p></section></>}
 {view==='Variations'&&<><div className="demo-metrics"><Metric label="Base contract" value={money(t.baseContract)} note="Original sample contract"/><Metric label="Approved variations" value={money(t.approvedVariations)} note="Two accepted variations, recorded as Approved"/><Metric label="Revised contract" value={money(t.revisedContract)} note="Base + approved variations"/><Metric label="Pending exposure" value={money(t.pendingVariations)} note={`If approved, contract would be ${money(t.potentialContract)}`}/></div><section className="demo-panel"><h2>Variation register</h2><Table caption="Three fictional variations" head={['Reference / variation','Status','Amount','Details']}>{d.variations.map(v=><tr key={v.id}><td><strong>{v.reference}</strong><small>{v.title}</small></td><td><Status value={v.status}/></td><td>{money(v.amount)}</td><td><Detail title={v.reference+' · '+v.title}><Status value={v.status}/><p>{v.description}</p><Table caption="Sample variation line items" head={['Description','Quantity','Rate','Amount']}>{v.items.map(i=><tr key={i.description}><td>{i.description}</td><td>{i.quantity}</td><td>{money(i.rate)}</td><td>{money(i.quantity*i.rate)}</td></tr>)}</Table><strong>Total ex GST: {money(v.amount)}</strong></Detail></td></tr>)}</Table></section></>}
 {view==='RFIs'&&<section className="demo-panel"><h2>RFI register</h2><p>Two sample requests: one answered (Responded), one open (Issued).</p><Table caption="Fictional requests for information" head={['Reference / request','Status','Response due','Details']}>{d.rfis.map(r=><tr key={r.id}><td><strong>{r.reference}</strong><small>{r.title}</small></td><td><Status value={r.status}/></td><td>{day(r.due)}</td><td><Detail title={r.reference+' · '+r.title}><Status value={r.status}/><h3>Question</h3><p>{r.question}</p><h3>Response</h3><p>{r.response||'Awaiting a sample response. No email has been sent.'}</p><small>Issued {day(r.issued)} · Due {day(r.due)}</small></Detail></td></tr>)}</Table></section>}
 {view==='Time Sheets'&&<><div className="demo-metrics"><Metric label="Sample staff" value={String(d.staff.length)} note="Fictional people; no login accounts"/><Metric label="Project hours" value={String(t.actualHours)} note="7 September – 2 October 2026"/><Metric label="Labour cost" value={money(t.actualLabour)} note="Hours × sample internal cost rates"/><Metric label="Hours remaining" value={String(t.budgetHours-t.actualHours)} note="Budget less recorded sample hours"/></div><section className="demo-panel"><h2>Fictional project team</h2><Table caption="Sample staff project totals" head={['Staff / role','Hours','Sample cost rate','Labour cost']}>{d.staff.map(s=>{const rows=d.timesheets.filter(e=>e.staffId===s.id);return <tr key={s.id}><td><strong>{s.name}</strong><small>{s.role}</small></td><td>{rows.reduce((n,e)=>n+e.hours,0)}</td><td>{money(s.rate)} / hour</td><td>{money(rows.reduce((n,e)=>n+e.cost,0))}</td></tr>;})}</Table><p>These are fictional internal cost rates, not actual Urban Charge rates or payroll instructions.</p></section><section className="demo-panel"><div className="demo-section-head"><div><h2>Weekly time entries</h2><p>{weekHours} sample hours this week</p></div><Select value={week} onValueChange={setWeek}><SelectTrigger aria-label="Timesheet week"><SelectValue/></SelectTrigger><SelectContent>{weeks.map(w=><SelectItem key={w} value={w}>Week of {day(w)}</SelectItem>)}</SelectContent></Select></div><Table caption="Sample weekly timesheet entries" head={['Date','Staff','Work package','Hours','Labour cost']}>{entries.map(e=><tr key={e.id}><td>{day(e.date)}</td><td>{e.employee}</td><td>{e.package}</td><td>{e.hours}</td><td>{money(e.cost)}</td></tr>)}</Table></section></>}
 {view==='Tasks'&&<section className="demo-panel"><h2>Project tasks</h2><p>Six fictional tasks: three complete and three open. No reminders or messages are sent.</p><Table caption="Sample project tasks" head={['Task','Assigned to','Status','Due']}>{d.tasks.map(task=><tr key={task.id}><td>{task.title}</td><td>{task.assignee}</td><td><Status value={task.status}/></td><td>{day(task.due)}</td></tr>)}</Table></section>}
 {view==='Site Diary'&&<section className="demo-panel"><h2>Site diary</h2>{d.diaries.map(entry=><article className="demo-diary" key={entry.id}><h3>{day(entry.date)}</h3><small>{entry.workers} fictional workers on site</small><p>{entry.work}</p><p><strong>Coordination note:</strong> {entry.issues}</p></article>)}</section>}
 {view==='Purchase Orders'&&<section className="demo-panel"><h2>Sample purchase order</h2><div className="demo-section-head"><div><h3>{d.purchaseOrder.reference}</h3><p>{d.purchaseOrder.supplier} · {day(d.purchaseOrder.date)}</p></div><Status value={d.purchaseOrder.status}/></div><p>Project PO matching reference: <strong>{d.project.purchaseOrderReference}</strong></p><Table caption="Sample purchase order items" head={['Description','Quantity','Rate','Amount']}>{d.purchaseOrder.items.map(i=><tr key={i.description}><td>{i.description}</td><td>{i.quantity}</td><td>{money(i.rate)}</td><td>{money(i.quantity*i.rate)}</td></tr>)}</Table><h3>Total ex GST: {money(d.purchaseOrder.amount)}</h3><p>{d.purchaseOrder.notes}</p><p>No order has been sent and no mailbox is connected.</p></section>}
 {view==='Drawings'&&<section className="demo-panel"><h2>{d.drawing.title}</h2><p>{d.drawing.reference} · Generated sample · Not to scale · Not for construction</p><img className="demo-drawing" src={d.drawing.url} alt={`Fictional ${d.project.name} plan showing a warehouse, loading bay, office, services area and illustrative light points`}/><p>This drawing is created solely for the demo. It contains no real site information. Markup, measurement and upload controls are available in the live workspace, not this view-only preview.</p></section>}
 <footer className="demo-footer">Private demonstration · Fictional data · No changes to your live workspace</footer></main></div></div>;
}
