import {projectStages} from '../project-stages';
import {variationInput} from '../variation-status';
/** Server-only fixture source: never import values into client code or query real business tables here. */
export function buildDemoData(){
 const staff=[{id:'demo-alex',name:'Alex Demo',role:'Site lead',rate:80,days:15,hoursPerDay:8},{id:'demo-casey',name:'Casey Demo',role:'Electrician',rate:70,days:20,hoursPerDay:8},{id:'demo-jamie',name:'Jamie Demo',role:'Electrician',rate:70,days:15,hoursPerDay:8},{id:'demo-taylor',name:'Taylor Demo',role:'Apprentice',rate:40,days:20,hoursPerDay:5}];
 const dates=Array.from({length:26},(_,i)=>new Date(Date.UTC(2026,8,7+i))).filter(d=>![0,6].includes(d.getUTCDay())).map(d=>d.toISOString().slice(0,10));
 const timesheets=staff.flatMap(s=>dates.slice(0,s.days).map((date,i)=>({id:`${s.id}-${date}`,staffId:s.id,employee:s.name,date,hours:s.hoursPerDay,rate:s.rate,cost:s.hoursPerDay*s.rate,package:i<5?'Undergrounds':'Lighting',notes:'Fictional project hours; not payroll.'})));
 const variations=[
 {id:'demo-var-001',reference:'DEMO-VAR-001',title:'Additional warehouse lighting',status:'Approved',description:'Sample accepted scope: additional high-bay lighting and installation.',items:[{description:'Additional high-bay lighting package',quantity:12,rate:1000},{description:'Installation and commissioning allowance',quantity:1,rate:6000}]},
 {id:'demo-var-002',reference:'DEMO-VAR-002',title:'Loading-bay power outlets',status:'Approved',description:'Sample accepted scope: six additional loading-bay outlet points.',items:[{description:'Additional outlet points, installed',quantity:6,rate:1250}]},
 {id:'demo-var-003',reference:'DEMO-VAR-003',title:'Office communications upgrade',status:'Pending',description:'Awaiting sample client approval; excluded from the revised contract.',items:[{description:'Communications outlet allowance',quantity:14,rate:700}]},
 ].map(v=>({...v,amount:variationInput(v.status,{items:v.items}).amount as number}));
 const expenses=[{id:'demo-exp-001',reference:'DEMO-INV-001',date:'2026-09-11',supplier:'Demo Cable Supply',description:'Cable and containment materials',amount:15600},{id:'demo-exp-002',reference:'DEMO-INV-002',date:'2026-09-18',supplier:'Demo Lighting Supply',description:'Base-scope luminaires and controls',amount:12400},{id:'demo-exp-003',reference:'DEMO-INV-003',date:'2026-09-25',supplier:'Demo Electrical Supply',description:'Conduit, supports and consumables',amount:6800}];
 const rfis=[{id:'demo-rfi-001',reference:'DEMO-RFI-001',title:'Warehouse lighting mounting position',status:'Responded',issued:'2026-09-18',due:'2026-09-23',question:'Confirm the sample lighting positions shown on DEMO-EL-001.',response:'Sample response: use the coordinated positions illustrated in the demonstration plan. This is not construction advice.'},{id:'demo-rfi-002',reference:'DEMO-RFI-002',title:'Office communications cabinet location',status:'Issued',issued:'2026-09-28',due:'2026-10-06',question:'Confirm the preferred sample cabinet location before the pending communications variation proceeds.',response:''}];
 const tasks=[{id:'demo-task-1',title:'Establish temporary site power',assignee:'Alex Demo',status:'Complete',due:'2026-09-09'},{id:'demo-task-2',title:'Complete underground pathway inspection',assignee:'Casey Demo',status:'Complete',due:'2026-09-16'},{id:'demo-task-3',title:'Complete warehouse rough-in review',assignee:'Jamie Demo',status:'Complete',due:'2026-09-25'},{id:'demo-task-4',title:'Fit off warehouse lighting',assignee:'Casey Demo',status:'In Progress',due:'2026-10-09'},{id:'demo-task-5',title:'Confirm office cabinet location after RFI response',assignee:'Alex Demo',status:'To Do',due:'2026-10-06'},{id:'demo-task-6',title:'Prepare test sheets for handover',assignee:'Taylor Demo',status:'To Do',due:'2026-10-16'}];
 const diaries=[{id:'demo-diary-1',date:'2026-09-25',workers:4,work:'Sample warehouse rough-in completed. Crew checked labelled circuits against the demonstration plan.',issues:'Office cabinet location remains subject to DEMO-RFI-002.'},{id:'demo-diary-2',date:'2026-10-02',workers:2,work:'Sample lighting fit-off preparation continued. Materials checked against the sample purchase order.',issues:'No safety or inspection certification is represented by this fictional diary.'}];
 const purchaseOrder={reference:'DEMO-PO-001',supplier:'Demo Switchboard Supply',status:'Issued',date:'2026-09-30',items:[{description:'Sample distribution board package',quantity:1,rate:12000}],amount:12000,notes:'Outstanding sample commitment, not an expense or payment. Excluded from actual costs; included within the remaining materials budget.'};
 const baseContract=240000,approvedVariations=variations.filter(v=>v.status==='Approved').reduce((s,v)=>s+v.amount,0),pendingVariations=variations.filter(v=>v.status==='Pending').reduce((s,v)=>s+v.amount,0),actualHours=timesheets.reduce((s,t)=>s+t.hours,0),actualLabour=timesheets.reduce((s,t)=>s+t.cost,0),actualMaterials=expenses.reduce((s,e)=>s+e.amount,0),budgetHours=1600,budgetLabour=120000,budgetMaterials=85000;
 const stageDefinitions=projectStages.map(s=>({...s})),stageProgress=Object.fromEntries(stageDefinitions.map((s,i)=>[s.id,i<4])),completedStages=stageDefinitions.filter(s=>stageProgress[s.id]).length;
 return {label:'Private demo · Fictional sample data · View-only',asOf:'2026-10-02',company:'Urban Charge Electrical',project:{id:'demo-riverside-warehouse',name:'Riverside Warehouse',number:'DEMO-RW-001',purchaseOrderReference:purchaseOrder.reference,status:'Active',stageDefinitions,stageProgress,stageVersion:0},staff,timesheets,variations,expenses,rfis,tasks,diaries,purchaseOrder,drawing:{reference:'DEMO-EL-001',title:'Illustrative warehouse electrical layout',url:'/api/demo/drawing'},totals:{baseContract,approvedVariations,pendingVariations,revisedContract:baseContract+approvedVariations,potentialContract:baseContract+approvedVariations+pendingVariations,budgetHours,budgetLabour,budgetMaterials,budgetCost:budgetLabour+budgetMaterials,actualHours,actualLabour,actualMaterials,actualCost:actualLabour+actualMaterials,remainingBudget:budgetLabour+budgetMaterials-actualLabour-actualMaterials,uncommittedMaterials:budgetMaterials-actualMaterials-purchaseOrder.amount,completedStages,totalStages:stageDefinitions.length,progressPercent:Math.round(completedStages/stageDefinitions.length*100)}};
}
export type DemoData=ReturnType<typeof buildDemoData>;
export function demoDrawingSvg(){return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="760" viewBox="0 0 1200 760"><rect width="1200" height="760" fill="white"/><g font-family="Arial,sans-serif" fill="#151515"><text x="45" y="48" font-size="25" font-weight="bold">Riverside Warehouse — DEMO-EL-001</text><text x="45" y="78" font-size="16">FICTIONAL DEMO DRAWING · NOT FOR CONSTRUCTION · NOT TO SCALE</text><g fill="none" stroke="#151515" stroke-width="3"><rect x="80" y="125" width="1020" height="500"/><path d="M820 125v500M820 380h280M80 525h740"/></g><text x="360" y="165" font-size="22">WAREHOUSE</text><text x="890" y="165" font-size="22">OFFICE</text><text x="315" y="590" font-size="22">LOADING BAY</text><text x="870" y="430" font-size="20">SERVICES</text><g fill="none" stroke="#2563ff" stroke-width="3">${[230,430,630].flatMap(x=>[260,420].map(y=>`<circle cx="${x}" cy="${y}" r="20"/><path d="M${x-14} ${y-14}l28 28m-28 0l28 -28"/>`)).join('')}<rect x="930" y="480" width="95" height="55"/></g><text x="950" y="514" font-size="18">DB</text><text x="850" y="250" font-size="17">Sample office fit-out</text><text x="850" y="282" font-size="15">Cabinet location: open RFI</text><text x="80" y="690" font-size="17">Circle + cross: sample light point     DB: sample distribution board</text><text x="80" y="725" font-size="14">Urban Charge Electrical · Private demonstration · No real site details or engineering design</text></g></svg>`;}
