import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess} from '@/app/company-access';
import {feedbackTypes,feedbackImpacts,feedbackStatuses} from '@/app/feedback-model';
import {permissionTabs} from '@/app/permissions';
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
export async function GET(req:NextRequest){const user=await getChatGPTUser();if(!user)return fail('Sign in required.',401);const access=await getCompanyAccess(user);if(access.blocked||access.role==='member')return fail('Administrator access is required.',403);try{const status=req.nextUrl.searchParams.get('status')||'All';if(status!=='All'&&!feedbackStatuses.includes(status as any))return fail('Choose a valid status.');const raw=req.nextUrl.searchParams.get('offset')||'0',offset=Number(raw);if(!Number.isInteger(offset)||offset<0)return fail('Invalid page.');const condition=status==='All'?'owner=?':'owner=? AND status=?',args=status==='All'?[access.owner]:[access.owner,status];const rows=await companyDb().prepare(`SELECT id,sender_name,sender_email,type,impact,subject,message,project_name,section,status,version,created,updated FROM feedback WHERE ${condition} ORDER BY created DESC,id DESC LIMIT 51 OFFSET ?`).bind(...args,offset).all();return NextResponse.json({items:rows.results.slice(0,50),hasMore:rows.results.length>50})}catch(e){console.error('Feedback inbox',e);return fail('Could not load feedback. Please retry.',500)}}
export async function POST(req:NextRequest){const user=await getChatGPTUser();if(!user)return fail('Sign in required.',401);const access=await getCompanyAccess(user);if(access.blocked)return fail('Company access is disabled.',403);try{const b:any=await req.json(),db=companyDb();if(b.action==='status'){if(access.role==='member')return fail('Administrator access is required.',403);if(!feedbackStatuses.includes(b.status)||!Number.isInteger(b.version))return fail('Choose a valid status.');const row:any=await db.prepare('SELECT id,version FROM feedback WHERE id=? AND owner=?').bind(String(b.id||''),access.owner).first();if(!row)return fail('Feedback unavailable.',404);const result=await db.prepare('UPDATE feedback SET status=?,updated=?,version=version+1 WHERE id=? AND owner=? AND version=?').bind(b.status,new Date().toISOString(),row.id,access.owner,b.version).run();if(!result.meta.changes)return fail('This item changed elsewhere. Refresh the inbox before updating it.',409);return NextResponse.json({ok:true})}
if(b.action!=='submit')return fail('Invalid feedback action.');const id=String(b.id||''),subject=String(b.subject||'').trim(),message=String(b.message||'').trim(),type=String(b.type||''),impact=type==='Problem'?String(b.impact||''):'';if(!/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(id)||!feedbackTypes.includes(type as any)||!subject||subject.length>160||!message||message.length>5000||(type==='Problem'&&!feedbackImpacts.includes(impact as any)))return fail('Choose a category and enter a title (up to 160 characters) and message (up to 5,000 characters).');const prior:any=await db.prepare('SELECT owner,sender_id FROM feedback WHERE id=?').bind(id).first();if(prior){if(prior.owner!==access.owner||prior.sender_id!==user.userId)return fail('Please start a new feedback submission.',409);return NextResponse.json({id})}const projectId=String(b.projectId||'');const project:any=projectId?await db.prepare('SELECT name FROM projects WHERE id=? AND owner=?').bind(projectId,access.owner).first():null;if(projectId&&!project)return fail('The project is unavailable.',404);const section=String(b.section||'');if(section&&![...permissionTabs,'Dashboard','Projects','My Tasks','Time Sheets','Settings'].includes(section as any))return fail('Invalid page context.');const now=new Date().toISOString();await db.prepare('INSERT INTO feedback (id,owner,sender_id,sender_name,sender_email,type,impact,subject,message,project_id,project_name,section,status,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,access.owner,user.userId,user.fullName||user.email,user.email,type,impact,subject,message,projectId,project?.name||'',section,'New',now,now).run();return NextResponse.json({id});}catch(e){console.error('Save feedback',e);return fail('Feedback could not be saved. Your message is still here; please retry.',500)}}
