import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';
import {renderToStaticMarkup} from 'react-dom/server';
import {PDFDocument} from 'pdf-lib';
import {NextRequest} from 'next/server';
import {createMailWorker} from '../workers/auth-email/index.mjs';
const out='test-audit/evidence'; mkdirSync(out,{recursive:true});
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');
for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
class Statement{
 constructor(public query:string,public args:any[]=[]){ }
 bind(...args:any[]){return new Statement(this.query,args)}
 async first(column?:string){const row=sql.prepare(this.query).get(...this.args);return row?(column?row[column]:row):null}
 async all(){return {success:true,results:sql.prepare(this.query).all(...this.args),meta:{}}}
 async raw(){const s=sql.prepare(this.query);s.setReturnArrays(true);return s.all(...this.args)}
 async run(){const r=sql.prepare(this.query).run(...this.args);return {success:true,results:[],meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}}}
}
const db={prepare:(q:string)=>new Statement(q),batch:async(ss:Statement[])=>{sql.exec('BEGIN');try{const a=[];for(const s of ss)a.push(await s.run());sql.exec('COMMIT');return a}catch(e){sql.exec('ROLLBACK');throw e}}};
sql.exec('PRAGMA foreign_keys=ON');
const objects=new Map<string,Uint8Array>();
(globalThis as any).__testEnv={PLANFLO_AUTH_MODE:"managed-sites",PLANFLO_DEPLOYMENT:"managed-sites",DB:db,FILES:{put:async(k:string,b:ArrayBuffer)=>objects.set(k,new Uint8Array(b)),get:async(k:string)=>objects.has(k)?{body:objects.get(k)}:null,delete:async(k:string)=>objects.delete(k)},PLANFLO_PLATFORM_OWNER_ID:'rob',PLANFLO_PLATFORM_OWNER_EMAIL:'rob@example.test',PLANFLO_ADMIN_EMAILS:'rob@example.test'};
globalThis.fetch=async()=>{throw new Error('ISOLATION: network fetch blocked')};
const identities:any={rob:['rob','rob@example.test'],a:['a','owner-a@example.test'],aa:['aa','admin-a@example.test'],ae:['ae','electrician-a@example.test'],b:['b','owner-b@example.test'],be:['be','electrician-b@example.test'],support:['support','support@example.test'],join:['join','join@example.test'],own:['own','own@example.test']};
function identity(name:string|null){const v=name?identities[name]:null;(globalThis as any).__testHeaders=new Headers(v?{'oai-authenticated-user-id':v[0],'oai-authenticated-user-email':v[1]}:{})}
const permissions=JSON.stringify(Object.fromEntries(['Drawings','Photos','Tasks','Files','Overview','Time','Schedule','O&M Manuals'].map(k=>[k,{view:true,edit:true}])));
for(const [id,owner,role,seat] of [['aa','a','admin','office'],['ae','a','member','field'],['be','b','member','field']])sql.prepare("INSERT INTO company_members(id,owner,email,name,user_id,role,seat_type,permissions,status,created) VALUES(?,?,?,?,?,?,?,?, 'active',?)").run(id,owner,identities[id][1],id,id,role,seat,permissions,new Date().toISOString());
for(const [id,owner] of [['a1','a'],['a2','a'],['b1','b'],['own1','own']])sql.prepare("INSERT INTO projects(id,owner,name,created) VALUES(?,?,?,?)").run(id,owner,'Synthetic '+id,new Date().toISOString());
sql.prepare('INSERT INTO project_members(owner,project_id,member_id) VALUES(?,?,?)').run('a','a1','ae');
sql.prepare('INSERT INTO project_members(owner,project_id,member_id) VALUES(?,?,?)').run('b','b1','be');
sql.prepare("INSERT INTO platform_operators(email,role,updated) VALUES(?,'support',?)").run('support@example.test',new Date().toISOString());
const data=await import('../app/api/data/route');const upload=await import('../app/api/upload/route');const file=await import('../app/api/file/[id]/route');const actions=await import('../app/api/file-actions/route');const folders=await import('../app/api/folders/route');const revisions=await import('../app/api/plan-revisions/route');const company=await import('../app/api/company/route');const admin=await import('../app/api/admin/route');const controls=await import('../app/api/admin-controls/route');const staff=await import('../app/api/staff-work/route');const tasks=await import('../app/api/tasks/route');const accessModule=await import('../app/company-access');const auth=await import('../app/chatgpt-auth');
const adminPage=await import('../app/admin/page');
const pdf=await PDFDocument.create();pdf.addPage([100,100]);const validPdf=await pdf.save();const validPng=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZ1sAAAAASUVORK5CYII=','base64');writeFileSync(out+'/dummy.pdf',validPdf);writeFileSync(out+'/dummy.png',validPng);
const results:any[]=[];
function check(name:string,condition:boolean,detail:any){results.push({name,result:condition?'PASS':'FAIL',detail});console.log((condition?'PASS':'FAIL')+' '+name+' '+JSON.stringify(detail))}
function req(path:string,body?:any){return new NextRequest('http://localhost:5199'+path,{method:body===undefined?'GET':'POST',headers:body instanceof FormData?{origin:'http://localhost:5199'}:{origin:'http://localhost:5199','content-type':'application/json'},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)})}
async function json(r:Response){return {status:r.status,body:await r.json()}}
async function addFile(projectId:string,category='plans',name='dummy.pdf',contents:string|Uint8Array='%PDF-1.4\nSynthetic audit fixture\n%%EOF',type='application/pdf',folderId=''){const f=new FormData();f.set('projectId',projectId);f.set('category',category);f.set('folderId',folderId);f.set('file',new File([contents],name,{type}));return json(await upload.POST(req('/api/upload',f)))}
async function getFile(id:string,revision=''){return file.GET(req('/api/file/'+id+(revision?'?revision='+revision:'')),{params:Promise.resolve({id})})}
identity(null);check('anonymous data denied',(await data.GET(req('/api/data'))).status===401,{});check('anonymous upload denied',(await addFile('a1')).status===401,{});check('anonymous file denied',(await getFile('missing')).status===401,{});
for(const who of ['a','aa','ae','b']){identity(who);for(const [name,route] of [['admin',admin],['controls',controls],['staff',staff]] as any){check(who+' denied platform '+name+' GET',(await route.GET(req('/api/'+name))).status===403,{});check(who+' denied platform '+name+' POST',(await route.POST(req('/api/'+name,{action:'operator',email:identities[who][1],role:'support',active:true,version:0}))).status===403,{})}const a=await accessModule.getCompanyAccess((await auth.getChatGPTUser())!);check(who+' platform nav flag hidden',!a.platformAdmin,{platformAdmin:a.platformAdmin})}
identity('rob');check('Rob platform overview allowed',(await admin.GET(req('/api/admin'))).status===200,{});
identity('support');check('Rob-only policy rejects legacy support',(await admin.GET(req('/api/admin?view=tickets'))).status===403,{actualPolicy:'active support operator'});
identity('aa');const forge=await json(await company.POST(req('/api/company',{action:'update',id:'ae',name:'Electrician',role:'owner',seatType:'office',permissions:{platformAdmin:{view:true,edit:true}}})));const role=sql.prepare('SELECT role,permissions FROM company_members WHERE id=?').get('ae');check('company admin cannot grant platform role',role?.role==='member'&&!String(role?.permissions).includes('platformAdmin'),{status:forge.status,role:role?.role});sql.prepare('UPDATE company_members SET permissions=?,seat_type=? WHERE id=?').run(permissions,'field','ae');
identity('a');const af=await addFile('a1');const af2=await addFile('a2');check('company A drawing upload',af.status===200,af);const photo=await addFile('a1','photos','dummy.png',validPng,'image/png');check('company A photo upload',photo.status===200,photo);check('upload to other company denied',(await addFile('b1')).status===403,{});const fid=af.body.id;let r=await getFile(fid);check('preview/download returns same bytes',r.status===200&&(await r.text()).includes('Synthetic audit fixture'),{status:r.status,cache:r.headers.get('cache-control'),sandbox:r.headers.get('content-security-policy')});
identity('b');check('cross-company download denied',(await getFile(fid)).status===404,{});const other=await json(await data.GET(req('/api/data?project=a1')));check('cross-company list hides records/files',other.status===200&&other.body.files.length===0&&other.body.projects.every((p:any)=>p.owner==='b'),{fileCount:other.body.files.length});
identity('ae');const list=await json(await data.GET(req('/api/data')));check('electrician assigned A1 cannot discover A2',!list.body.projects.some((p:any)=>p.id==='a2'),{visibleProjects:list.body.projects.map((p:any)=>p.id),fixtureAssignment:'A1 only, seeded project_members'});r=await getFile(af2.body.id);check('electrician assigned A1 denied A2 drawing',r.status===403||r.status===404,{status:r.status});
identity('a');const f1=await json(await folders.POST(req('/api/folders',{action:'create',projectId:'a1',category:'plans',name:'Audit'})));const f2=await json(await folders.POST(req('/api/folders',{action:'create',projectId:'a2',category:'plans',name:'Other'})));check('same-project folder creation',f1.status===200,f1);check('same-project file move',(await actions.POST(req('/api/file-actions',{action:'move',projectId:'a1',category:'plans',ids:[fid],folderId:f1.body.id}))).status===200,{});check('cross-project folder move denied',(await actions.POST(req('/api/file-actions',{action:'move',projectId:'a1',category:'plans',ids:[fid],folderId:f2.body.id}))).status===400,{});
const revform=new FormData();revform.set('fileId',fid);revform.set('label','Revision 2');revform.set('file',new File(['%PDF-1.4\nSynthetic revision\n%%EOF'],'revision.pdf',{type:'application/pdf'}));const rev=await json(await revisions.POST(req('/api/plan-revisions',revform)));check('drawing revision save',rev.status===200,rev);r=await getFile(fid);check('latest revision downloaded',(await r.text()).includes('Synthetic revision'),{});r=await getFile(fid,fid);check('original revision retained',(await r.text()).includes('Synthetic audit fixture'),{});
identity('b');check('cross-company revision listing denied',(await revisions.GET(req('/api/plan-revisions?fileId='+fid))).status===403,{});check('cross-company file rename denied',(await actions.POST(req('/api/file-actions',{action:'rename',projectId:'a1',category:'plans',ids:[fid],name:'stolen'}))).status===404,{});
identity('a');const strict=await tasks.POST(req('/api/tasks',{projectId:'a1',title:'Bad association',status:'To Do',data:{priority:'Normal',fileIds:[af2.body.id]}}));check('specialist task rejects cross-project reference',strict.status===400,{status:strict.status,body:await strict.text()});const generic=await json(await data.POST(req('/api/data',{action:'record',projectId:'a1',kind:'task',title:'Bad generic reference',data:{fileIds:[af2.body.id]}})));check('generic record rejects cross-project reference',generic.status===400||generic.status===403,{status:generic.status,id:generic.body.id});
const bad=await addFile('a1','plans','empty.exe','','application/octet-stream');check('initial drawing upload rejects empty non-drawing',bad.status===400,bad);
const invite=await json(await company.POST(req('/api/company',{action:'add',email:'join@example.test',name:'Join fixture',role:'member',permissions:{Drawings:{view:true,edit:false}}})));check('invite generated',invite.status===200,{status:invite.status});const pending=sql.prepare('SELECT id FROM company_members WHERE email=?').get('join@example.test');sql.prepare('INSERT INTO project_members(owner,project_id,member_id) VALUES(?,?,?)').run('a','a1',pending!.id);identity('b');check('wrong email invite denied',(await company.POST(req('/api/company',{action:'accept',token:invite.body.token}))).status===403,{});identity('join');check('matching email accepts invite',(await company.POST(req('/api/company',{action:'accept',token:invite.body.token}))).status===200,{});check('invite replay denied',(await company.POST(req('/api/company',{action:'accept',token:invite.body.token}))).status===400,{});check('view-only member upload denied',(await addFile('a1')).status===403,{});
identity('a');const ownInvite=await json(await company.POST(req('/api/company',{action:'add',email:'own@example.test',name:'Existing owner',role:'member',permissions:{Drawings:{view:true,edit:false}}})));identity('own');await data.GET(req('/api/data'));const accepted=await company.POST(req('/api/company',{action:'accept',token:ownInvite.body.token}));const after=await json(await data.GET(req('/api/data')));check('existing owner workspace protected when joining',accepted.status===409||after.body.projects.some((p:any)=>p.id==='own1'),{acceptStatus:accepted.status,visibleProjects:after.body.projects.map((p:any)=>p.id)});

for(const who of [null,'a','aa','ae','b','be','rob','support']){identity(who);const html=renderToStaticMarkup(await adminPage.default());check(String(who)+' direct admin page Rob-only',html.includes('TEST_PLATFORM_CONSOLE')===(who==='rob'),{consoleRendered:html.includes('TEST_PLATFORM_CONSOLE')})}
identity(null);for(const [name,route] of [['admin',admin],['controls',controls],['staff',staff]] as any){check('anonymous platform '+name+' denied',(await route.GET(req('/api/'+name))).status===403,{})}
identity('a');const realPdf=new FormData();realPdf.set('projectId','a1');realPdf.set('category','plans');realPdf.set('file',new File([validPdf],'valid-dummy.pdf',{type:'application/pdf'}));const vp=await json(await upload.POST(req('/api/upload',realPdf)));const pdfResponse=await getFile(vp.body.id);check('valid PDF upload and download byte equality',vp.status===200&&Buffer.from(await pdfResponse.arrayBuffer()).equals(Buffer.from(validPdf)),{status:vp.status});
const pngForm=new FormData();pngForm.set('projectId','a1');pngForm.set('category','photos');pngForm.set('file',new File([validPng],'valid-dummy.png',{type:'image/png'}));const pi=await json(await upload.POST(req('/api/upload',pngForm)));check('valid PNG upload and download byte equality',pi.status===200&&Buffer.from(await (await getFile(pi.body.id)).arrayBuffer()).equals(validPng),{status:pi.status});
const save=await json(await tasks.POST(req('/api/tasks',{projectId:'a1',title:'Valid task',status:'To Do',data:{priority:'Normal',fileIds:[vp.body.id]}})));check('valid task saves',save.status===200,save);
await actions.POST(req('/api/file-actions',{action:'archive',projectId:'a1',category:'plans',ids:[vp.body.id]}));check('file archive stored',sql.prepare('SELECT archived FROM files WHERE id=?').get(vp.body.id)?.archived===1,{});check('archive still downloadable (current semantics)',(await getFile(vp.body.id)).status===200,{});await actions.POST(req('/api/file-actions',{action:'restore',projectId:'a1',category:'plans',ids:[vp.body.id]}));check('file restore stored',sql.prepare('SELECT archived FROM files WHERE id=?').get(vp.body.id)?.archived===0,{});
const joinMember=sql.prepare('SELECT id FROM company_members WHERE user_id=?').get('join');await company.POST(req('/api/company',{action:'disable',id:joinMember?.id}));identity('join');check('disabled member file denied',(await getFile(fid)).status===403,{});check('disabled member data denied',(await data.GET(req('/api/data'))).status===403,{});
identities.exp=['exp','expired@example.test'];identity('a');const exp=await json(await company.POST(req('/api/company',{action:'add',email:'expired@example.test',name:'Expired'})));sql.prepare("UPDATE company_members SET expires='2000-01-01T00:00:00.000Z' WHERE email=?").run('expired@example.test');identity('exp');check('expired invite rejected',(await company.POST(req('/api/company',{action:'accept',token:exp.body.token}))).status===400,{});
identities.rev=['rev','revoked@example.test'];identity('a');const inv=await json(await company.POST(req('/api/company',{action:'add',email:'revoked@example.test',name:'Revoked'})));const member=sql.prepare('SELECT id FROM company_members WHERE email=?').get('revoked@example.test');await company.POST(req('/api/company',{action:'disable',id:member?.id}));identity('rev');check('revoked invite rejected',(await company.POST(req('/api/company',{action:'accept',token:inv.body.token}))).status===400,{});
identity('be');check('company B electrician cannot download A file',(await getFile(fid)).status===404,{});check('company B electrician cannot upload to A',(await addFile('a1')).status===403,{});
const navSource=readFileSync('app/workspace-client.tsx','utf8');check('navigation source gates platform link',navSource.includes('access.platformAdmin&&<a'),{type:'source assertion plus exercised access flags; not browser rendering'});

// Regression suite added after the original 83 checks; original expectations retained.
const assignment=await import('../app/api/project-members/route');
const schedule=await import('../app/api/schedule/route');
const register=await import('../app/api/workspace-register/route');
const safety=await import('../app/api/safety/route');
const equipment=await import('../app/api/equipment/route');
const om=await import('../app/api/om/route');
const budget=await import('../app/api/budget/route');
const daily=await import('../app/api/daily-review/route');
const reminders=await import('../app/api/app-reminders/route');
const feedback=await import('../app/api/feedback/route');
const ownerGate=await import('../app/platform-owner');
const allPermissions=JSON.stringify(Object.fromEntries((await import('../app/permissions')).permissionTabs.map(k=>[k,{view:true,edit:true}])));
// Ordinary office member receives broad tabs to prove project checks are independent of tabs.
sql.prepare('UPDATE company_members SET permissions=?,seat_type=? WHERE id=?').run(allPermissions,'office','ae');
identity('ae');
for(const [name,route,path] of [['budget',budget,'/api/budget?project=a2'],['safety',safety,'/api/safety?projectId=a2'],['equipment',equipment,'/api/equipment?kind=ewp&projectId=a2'],['om',om,'/api/om?projectId=a2'],['tasks',tasks,'/api/tasks?projectId=a2'],['revisions',revisions,'/api/plan-revisions?fileId='+af2.body.id]] as any){const rr=await route.GET(req(path));check('unassigned project denied by '+name,[403,404].includes(rr.status),{status:rr.status})}
check('member cannot self assign',(await assignment.POST(req('/api/project-members',{memberId:'ae',projectIds:['a1','a2'],version:0}))).status===403,{});
check('unassigned upload blocked',(await addFile('a2')).status===403,{});
check('unassigned generic save blocked',(await data.POST(req('/api/data',{action:'record',projectId:'a2',kind:'task',data:{fileIds:[]}}))).status===403,{});
check('unassigned project setup blocked',(await data.POST(req('/api/data',{action:'projectSetup',projectId:'a2',data:{name:'Attempt'}}))).status===403,{});
check('unassigned folder creation blocked',(await folders.POST(req('/api/folders',{action:'create',projectId:'a2',category:'plans',name:'Attempt'}))).status===404,{});
const unassignedRevision=new FormData();unassignedRevision.set('fileId',af2.body.id);unassignedRevision.set('label','Attempt');unassignedRevision.set('file',new File([validPdf],'valid.pdf',{type:'application/pdf'}));check('unassigned revision upload blocked',(await revisions.POST(req('/api/plan-revisions',unassignedRevision))).status===403,{});
for(const projectId of ['a1','a2','b1']){const owner=projectId[0];sql.prepare("INSERT INTO records(id,owner,project_id,kind,title,data,created) VALUES(?,?,?,'time',?,?,?)").run('time-'+projectId,owner,projectId,'Hours '+projectId,JSON.stringify({employee:'Worker '+projectId,date:'2026-10-01',hours:1,rate:1}),new Date().toISOString());sql.prepare("INSERT INTO schedule_entries(id,owner,worker_key,worker_name,project_id,project_name,kind,date,start,end,created,updated) VALUES(?,?,?,?,?,?,'work','2026-10-01','08:00','16:00',?,?)").run('shift-'+projectId,owner,'member:ae','Worker '+projectId,projectId,projectId,new Date().toISOString(),new Date().toISOString())}
const reg=await json(await register.GET(req('/api/workspace-register?kind=time')));check('timesheet list scoped to assigned projects',reg.status===200&&reg.body.rows.every((r:any)=>r.projectId==='a1')&&reg.body.projects.every((p:any)=>p.id==='a1'),{ids:reg.body.rows.map((r:any)=>r.projectId)});
const sch=await json(await schedule.GET(req('/api/schedule?week=2026-10-01')));check('schedule entries and project picker scoped',sch.status===200&&sch.body.entries.every((e:any)=>e.projectId==='a1')&&sch.body.projects.every((p:any)=>p.id==='a1'),{entries:sch.body.entries.map((e:any)=>e.projectId),projects:sch.body.projects.map((p:any)=>p.id)});
check('unassigned timesheet save denied',(await register.POST(req('/api/workspace-register',{kind:'time',projectId:'a2',data:{employee:'A',date:'2026-10-01',hours:1,rate:1}}))).status===404,{});
check('unassigned schedule delete denied',(await schedule.POST(req('/api/schedule',{action:'delete',id:'shift-a2',version:1}))).status===404,{});
check('unassigned schedule copy denied',(await schedule.POST(req('/api/schedule',{action:'copy',id:'shift-a2',version:1,dates:['2026-10-02']}))).status===404,{});
const shiftEntry={workerKey:'member:ae',projectId:'a2',kind:'work',date:'2026-10-01',start:'08:00',end:'16:00',breakMinutes:0,notes:'',role:'',leaveType:''};check('unassigned schedule save denied',(await schedule.POST(req('/api/schedule',{action:'save',entry:shiftEntry}))).status===400,{});
const taskList=await json(await tasks.GET(req('/api/tasks')));check('task picker/assets scoped',taskList.body.projects.every((p:any)=>p.id==='a1')&&taskList.body.assets.every((f:any)=>f.projectId==='a1'),{});
const dv=await json(await daily.GET(req('/api/daily-review?date=2026-10-01')));check('daily review list scoped',dv.status===200&&dv.body.projects.every((p:any)=>p.id==='a1')&&dv.body.items.every((i:any)=>i.projectId==='a1'),{status:dv.status});
const dr=await daily.GET(req('/api/daily-review?date=2026-10-01&project=a2'));check('daily review unassigned filter denied',dr.status===404,{status:dr.status});
const rem=await json(await reminders.GET());check('reminder results scoped',rem.status===200&&rem.body.items.every((r:any)=>r.projectId==='a1'),{status:rem.status});
identity('aa');let assignData=await json(await assignment.GET(req('/api/project-members?memberId=ae')));check('company admin can inspect assignments',assignData.status===200&&assignData.body.projectIds.join()==='a1',{});
check('company admin cannot assign foreign project',(await assignment.POST(req('/api/project-members',{memberId:'ae',projectIds:['b1'],version:assignData.body.version}))).status===404,{});
check('company admin cannot edit foreign member',(await assignment.POST(req('/api/project-members',{memberId:'be',projectIds:['a1'],version:0}))).status===404,{});
const currentVersion=assignData.body.version;check('company admin assigns second project',(await assignment.POST(req('/api/project-members',{memberId:'ae',projectIds:['a1','a2'],version:currentVersion}))).status===200,{});
check('stale assignments rejected',(await assignment.POST(req('/api/project-members',{memberId:'ae',projectIds:[],version:currentVersion}))).status===409,{});
identity('ae');check('new assignment permits drawing',(await getFile(af2.body.id)).status===200,{});identity('aa');assignData=await json(await assignment.GET(req('/api/project-members?memberId=ae')));await assignment.POST(req('/api/project-members',{memberId:'ae',projectIds:['a1'],version:assignData.body.version}));identity('ae');check('assignment removal takes effect next request',(await getFile(af2.body.id)).status===404,{});
identity('aa');const adminList=await json(await data.GET(req('/api/data')));check('company admin still sees all own projects',adminList.body.projects.length===2&&adminList.body.projects.every((p:any)=>p.owner==='a'),{});check('company admin can download unassigned own-company file',(await getFile(af2.body.id)).status===200,{});identity('b');const bList=await json(await data.GET(req('/api/data')));check('other owner sees only own company',bList.body.projects.length===1&&bList.body.projects[0].id==='b1',{});
identity('a');for(const [name,contents,mime] of [['fake.pdf','not a PDF','application/pdf'],['fake.png','not a PNG','image/png'],['x.exe','%PDF-1.4','application/pdf'],['wrong.pdf','%PDF-1.4','image/png'],['empty.pdf','','application/pdf']] as const){const before=objects.size;const x=await addFile('a1','plans',name,contents,mime);check('reject invalid drawing '+name+' '+mime,x.status===400&&objects.size===before,{status:x.status,objectsUnchanged:objects.size===before})}
const invalidRevision=new FormData();invalidRevision.set('fileId',fid);invalidRevision.set('label','bad');invalidRevision.set('file',new File(['not PDF'],'bad.pdf',{type:'application/pdf'}));check('invalid revision rejected',(await revisions.POST(req('/api/plan-revisions',invalidRevision))).status===400,{});
const foreign=await (async()=>{identity('b');const v=await addFile('b1');identity('a');return v.body.id})();
for(const [name,d] of [['cross-company',{fileIds:[foreign]}],['nested cross-project',{details:{fileIds:[af2.body.id]}}],['bad ref type',{fileIds:'not-array'}],['forged revision',{planId:fid,revisionId:af2.body.id}]] as any){const x=await data.POST(req('/api/data',{action:'record',projectId:'a1',kind:'task',title:name,data:d}));check('generic attachment rejects '+name,x.status===400,{status:x.status})}
check('valid generic drawing markup preserved',(await data.POST(req('/api/data',{action:'record',projectId:'a1',kind:'markup',title:'Mark',data:{planId:fid,revisionId:rev.body.id,points:[{x:1,y:1}]}}))).status===200,{});
identity('ae');const permsNow=sql.prepare('SELECT permissions FROM company_members WHERE id=?').get('ae')!.permissions;sql.prepare('UPDATE company_members SET permissions=? WHERE id=?').run(JSON.stringify({Tasks:{view:true,edit:true}}),'ae');check('assigned project still requires drawing permission',(await getFile(fid)).status===403,{});check('generic record cannot attach forbidden-tab file',(await data.POST(req('/api/data',{action:'record',projectId:'a1',kind:'task',title:'Denied drawing',data:{fileIds:[fid]}}))).status===400,{});sql.prepare('UPDATE company_members SET permissions=? WHERE id=?').run(permsNow,'ae');
const envTest=(globalThis as any).__testEnv;identity('rob');check('Rob cannot enable delegated operator',(await controls.POST(req('/api/admin-controls',{action:'operator',email:'someone@example.test',role:'support',active:true,version:0}))).status===403,{});const savedOwnerId=envTest.PLANFLO_PLATFORM_OWNER_ID;delete envTest.PLANFLO_PLATFORM_OWNER_ID;check('missing platform subject fails closed',(await admin.GET(req('/api/admin'))).status===403,{});envTest.PLANFLO_PLATFORM_OWNER_ID='wrong';check('wrong platform subject denied',(await admin.GET(req('/api/admin'))).status===403,{});envTest.PLANFLO_PLATFORM_OWNER_ID=savedOwnerId;
identities.imposter=['imposter','rob@example.test'];identity('imposter');check('matching email alone cannot elevate',(await admin.GET(req('/api/admin'))).status===403,{});check('wrong email cannot elevate with matching subject',!ownerGate.isPlatformOwner({userId:'rob',email:'other@example.test'}),{});identity('support');check('legacy operator nav flag hidden',!(await accessModule.getCompanyAccess((await auth.getChatGPTUser())!)).platformAdmin,{});
let foreignKeyRejected=false;try{sql.prepare('INSERT INTO project_members(owner,project_id,member_id) VALUES(?,?,?)').run('a','b1','ae')}catch{foreignKeyRejected=true}check('database rejects cross-company assignment',foreignKeyRejected,{});
identity('a');identities.configOwner=['configOwner','config-owner@example.test'];sql.prepare('INSERT INTO settings(owner,company) VALUES(?,?)').run('configOwner','Owned company');const ci=await json(await company.POST(req('/api/company',{action:'add',email:'config-owner@example.test',name:'Owner'})));identity('configOwner');check('settings-only owner cannot lose workspace',(await company.POST(req('/api/company',{action:'accept',token:ci.body.token}))).status===409,{});
let staleOwnerWrite=false;try{sql.prepare('INSERT INTO projects(id,owner,name,created) VALUES(?,?,?,?)').run('stale-project','ae','Stale owner write',new Date().toISOString())}catch{staleOwnerWrite=true}check('database blocks stale personal-workspace write after join',staleOwnerWrite,{});
let concurrentOwnerJoin=false;try{sql.prepare("UPDATE company_members SET user_id='configOwner',status='active' WHERE email='config-owner@example.test'").run()}catch{concurrentOwnerJoin=true}check('database blocks bypass/concurrent join by workspace owner',concurrentOwnerJoin,{});

// Exercise populated review/reminder results and mutation paths, not empty-list assertions.
for(const projectId of ['a1','a2']){
 sql.prepare("INSERT INTO review_activity(owner,project_id,source_type,source_id,category,title,operation,after_data,occurred) VALUES('a',?,'record',?,'record:task',?,'insert',?,?)").run(projectId,'review-seed-'+projectId,projectId,JSON.stringify({title:projectId,data:{}}),'2026-10-01T01:00:00.000Z');
 sql.prepare("INSERT INTO records(id,owner,project_id,kind,title,status,data,created) VALUES(?,'a',?,'task',?,'To Do',?,?)").run('overdue-'+projectId,projectId,'Overdue '+projectId,JSON.stringify({due:'2026-09-01',assigneeKey:'user:ae',fileIds:[]}),new Date().toISOString());
}
identity('ae');const filledReview=await json(await daily.GET(req('/api/daily-review?date=2026-10-01')));check('populated daily review excludes unassigned activity',filledReview.body.items.some((r:any)=>r.sourceId==='review-seed-a1')&&!filledReview.body.items.some((r:any)=>r.projectId==='a2'),{items:filledReview.body.items.length});
const foreignEvent=sql.prepare("SELECT id FROM review_activity WHERE source_id='review-seed-a2'").get()!.id;check('unassigned daily review mutation denied',(await daily.POST(req('/api/daily-review',{eventId:Number(foreignEvent),decision:'Verified'}))).status===404,{});
const filledReminders=await json(await reminders.GET());check('populated reminders exclude unassigned project',filledReminders.body.items.some((r:any)=>r.id==='overdue-a1')&&!filledReminders.body.items.some((r:any)=>r.projectId==='a2'),{items:filledReminders.body.items.length});
check('unassigned budget write denied',(await budget.POST(req('/api/budget',{projectId:'a2',costBudget:5}))).status===404,{});
check('unassigned equipment assignment denied',(await equipment.POST(req('/api/equipment',{action:'assign',projectId:'a2',templateId:'nonexistent'}))).status===404,{});
check('unassigned safety save denied',(await safety.POST(req('/api/safety',{type:'record',projectId:'a2',title:'Attempt',category:'SWMS',data:{fields:[]}}))).status===404,{});
check('unassigned O&M save denied',(await om.POST(req('/api/om',{projectId:'a2',status:'Draft',data:{}}))).status===404,{});
check('unassigned task save denied',(await tasks.POST(req('/api/tasks',{projectId:'a2',title:'Attempt',status:'To Do',data:{priority:'Normal',fileIds:[]}}))).status===404,{});
check('unassigned feedback project context denied',(await feedback.POST(req('/api/feedback',{action:'submit',id:crypto.randomUUID(),subject:'Test',message:'Synthetic message',type:'Question',projectId:'a2',section:'Tasks'}))).status===404,{});
check('customer cannot call platform export',(await controls.GET(req('/api/admin-controls?view=export&owner=a'))).status===403,{});
identity('aa');check('company admin cannot call platform export',(await controls.GET(req('/api/admin-controls?view=export&owner=a'))).status===403,{});
check('null assignment body rejected',(await assignment.POST(req('/api/project-members',null))).status===400,{});
const missingOrigin=new NextRequest('http://localhost:5199/api/project-members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId:'ae',projectIds:[],version:2})});check('assignment mutation requires same origin',(await assignment.POST(missingOrigin)).status===403,{});
const beforeAssignments=sql.prepare("SELECT project_id FROM project_members WHERE member_id='ae'").all();const failedUpdate=await assignment.POST(req('/api/project-members',{memberId:'ae',projectIds:['a1','b1'],version:2}));check('mixed-company assignment leaves existing set unchanged',failedUpdate.status===404&&JSON.stringify(sql.prepare("SELECT project_id FROM project_members WHERE member_id='ae'").all())===JSON.stringify(beforeAssignments),{});
identity('rob');const sx=await json(await controls.GET(req('/api/admin-controls?view=export&owner=a')));check('Rob company export includes assignment records',sx.status===200&&Array.isArray(sx.body.tables?.project_members),{status:sx.status});
identity('a');identities.noProjects=['noProjects','no-projects@example.test'];sql.prepare("INSERT INTO company_members(id,owner,email,name,user_id,role,seat_type,permissions,status,created) VALUES('noProjects','a','no-projects@example.test','No projects','noProjects','member','office',?,'active',?)").run(allPermissions,new Date().toISOString());identity('noProjects');const empty=await json(await data.GET(req('/api/data')));check('unassigned member defaults to no project data',empty.body.projects.length===0&&empty.body.files.length===0&&empty.body.records.length===0,{});check('unassigned member cannot retrieve known file',(await getFile(fid)).status===404,{});

// Exercise actual Better Auth handlers + Drizzle/D1 adapter. No provider or network.
const runtime=await import('../app/auth-runtime');
const authRoutes=await import('../app/api/auth/[...all]/route');
const onboarding=await import('../app/api/onboarding/route');
const e=(globalThis as any).__testEnv;
e.PLANFLO_AUTH_MODE='standalone';e.PLANFLO_DEPLOYMENT='test';
identity('rob');check('standalone ignores forged Sites owner headers',await auth.getChatGPTUser()===null,{});
e.PLANFLO_AUTH_ORIGIN='https://auth.example.test';e.BETTER_AUTH_SECRET='synthetic-test-secret-never-use-in-production-2026';
const mailbox:{to:string;purpose:string;url:string}[]=[];
const testMailWorker=createMailWorker({fetch:async()=>Response.json({id:'synthetic-accepted-email'})});
e.AUTH_EMAIL={fetch:async(r:Request)=>{const mail=await r.clone().json() as any;const response=await testMailWorker.fetch(r,{AUTH_EMAIL_PROVIDER:'resend',AUTH_EMAIL_FROM:'auth@example.test',RESEND_API_KEY:'re_synthetic_test_only',PLANFLO_AUTH_ORIGIN:e.PLANFLO_AUTH_ORIGIN});if(response.ok)mailbox.push(mail);return response;}};
let ip=1;
function authRequest(path:string,body?:unknown,cookie='',origin='https://auth.example.test'){
 if(path==='sign-up/email'&&body&&typeof body==='object')body={firstName:'Synthetic',surname:'Customer',businessName:'Synthetic Electrical',abn:'10 000 000 000',address:'1 Test Street, Testville',phone:'+61 400 000 000',rec:'TEST-REC-001',...body};
 return new Request('https://auth.example.test/api/auth/'+path,{method:body===undefined?'GET':'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':`192.0.2.${ip}`,cookie},body:body===undefined?undefined:JSON.stringify(body)});
}
async function ar(path:string,body?:unknown,cookie='',origin='https://auth.example.test'){return (body===undefined?authRoutes.GET:authRoutes.POST)(authRequest(path,body,cookie,origin))}
function setSession(cookie:string){(globalThis as any).__testHeaders=new Headers({cookie,'oai-authenticated-user-id':'rob','oai-authenticated-user-email':'rob@example.test'})}
const email='customer@example.test',password='Correct Horse Battery 42!';
r=await ar('sign-up/email',{name:'Synthetic Customer',email,password,callbackURL:'/login'});
check('customer signup accepted',r.status===200,{status:r.status});
check('verification email captured only by test adapter',mailbox.length===1&&mailbox[0].purpose==='verification'&&mailbox[0].to===email,{});
check('signup creates no session',!r.headers.get('set-cookie')?.includes('session_token='),{});
check('unverified login denied',(await ar('sign-in/email',{email,password})).status===403,{});
const verify=mailbox[0].url;
r=await authRoutes.GET(new Request(verify));check('email verification succeeds',[200,302].includes(r.status),{status:r.status});
check('stored email verified',sql.prepare('SELECT email_verified FROM auth_user WHERE email=?').get(email)?.email_verified===1,{});
r=await ar('sign-in/email',{email,password});const cookie=r.headers.get('set-cookie')?.split(';')[0]||'';
check('verified customer login succeeds',r.status===200&&!!cookie,{status:r.status});
const setCookie=r.headers.get('set-cookie')||'';check('session cookie secure HttpOnly SameSite',/secure/i.test(setCookie)&&/httponly/i.test(setCookie)&&/samesite=lax/i.test(setCookie),{});
setSession(cookie);const customer=await auth.getChatGPTUser();check('server session resolves namespaced immutable identity',!!customer?.userId.startsWith('auth:')&&customer.email===email,{});
check('customer cannot become Rob via headers',customer?.userId!=='rob'&&!await (await import('../app/operator-access')).operatorRole(customer!),{});
check('verified customer blocked until company onboarding',(await accessModule.getCompanyAccess(customer!)).blocked===true,{});
const onboardReq=(companyName:string)=>new Request('https://auth.example.test/api/onboarding',{method:'POST',headers:{origin:'https://auth.example.test','content-type':'application/json'},body:JSON.stringify({company:companyName})});
check('company onboarding succeeds',(await onboarding.POST(onboardReq('Synthetic Customer Ltd'))).status===201,{});
check('onboarding cannot overwrite company',(await onboarding.POST(onboardReq('Other Ltd'))).status===409,{});
check('onboarded owner gains own workspace',!(await accessModule.getCompanyAccess(customer!)).blocked,{});
check('session tampering denied',await runtime.customerAuth().api.getSession({headers:new Headers({cookie:cookie+'tampered'})})===null,{});
check('cross-origin signup denied',(await ar('sign-up/email',{email:'bad@example.test',name:'Bad',password},'','https://evil.example')).status===403,{});
check('disabled auth plugins inaccessible',(await ar('sign-in/magic-link',{email})).status===404,{});
check('oversized password rejected before hashing',(await ar('sign-in/email',{email,password:'x'.repeat(129)})).status===400,{});
ip++;r=await ar('sign-up/email',{name:'Duplicate',email,password});check('duplicate signup uses generic success',r.status===200,{status:r.status});
check('duplicate signup retains one user',sql.prepare('SELECT COUNT(*) AS n FROM auth_user WHERE email=?').get(email)?.n===1,{});
r=await ar('request-password-reset',{email,redirectTo:'/login'});check('password recovery request succeeds',r.status===200,{status:r.status});
const recovery=mailbox.findLast(m=>m.purpose==='recovery')!;check('recovery delivered to synthetic mailbox',!!recovery,{});
const recoveryResponse=await authRoutes.GET(new Request(recovery.url));const resetUrl=new URL(recoveryResponse.headers.get('location')!,'https://auth.example.test');const resetToken=resetUrl.searchParams.get('token');
const newPassword='New Correct Horse Battery 43!';r=await ar('reset-password',{token:resetToken,newPassword});check('password reset succeeds',r.status===200,{status:r.status});
check('password reset revokes existing session',await auth.getChatGPTUser()===null,{});
check('recovery token cannot be reused',(await ar('reset-password',{token:resetToken,newPassword:password})).status>=400,{});
ip++;check('old password no longer works',(await ar('sign-in/email',{email,password})).status===401,{});
r=await ar('sign-in/email',{email,password:newPassword});const newCookie=r.headers.get('set-cookie')?.split(';')[0]||'';check('new password works',r.status===200&&!!newCookie,{});
check('logout succeeds',(await ar('sign-out',{},newCookie)).status===200,{});setSession(newCookie);check('logout invalidates server session',await auth.getChatGPTUser()===null,{});
ip++;const absentReset=await ar('request-password-reset',{email:'absent@example.test',redirectTo:'/login'});check('unknown email recovery stays generic',absentReset.status===200,{});
const expired=await ar('reset-password',{token:'invalid-or-expired',newPassword});check('invalid recovery token rejected',expired.status>=400,{});
ip++;const codes=[];for(let n=0;n<7;n++)codes.push((await ar('sign-in/email',{email,password:'Incorrect Password 42!'})).status);check('database rate limiter throttles repeated login',codes.includes(429),{codes});
// Invitation acceptance using a genuinely verified standalone identity.
ip++;const inviteEmail='staff-auth@example.test';await ar('sign-up/email',{name:'Staff Auth',email:inviteEmail,password});await authRoutes.GET(new Request(mailbox.findLast(m=>m.to===inviteEmail&&m.purpose==='verification')!.url));
r=await ar('sign-in/email',{email:inviteEmail,password});const staffCookie=r.headers.get('set-cookie')?.split(';')[0]||'';setSession(staffCookie);
const inviteToken='synthetic-standalone-invite';sql.prepare("INSERT INTO company_members(id,owner,email,name,role,seat_type,permissions,status,token_hash,expires,created) VALUES('auth-staff','a',?,'Staff Auth','member','office',?,'pending',?,?,?)").run(inviteEmail,allPermissions,await accessModule.hashInvite(inviteToken),new Date(Date.now()+86400000).toISOString(),new Date().toISOString());
check('verified customer accepts email-matching invite',(await company.POST(req('/api/company',{action:'accept',token:inviteToken}))).status===200,{});
const staffAuth=await auth.getChatGPTUser();const staffAccess=await accessModule.getCompanyAccess(staffAuth!);check('joined member belongs only to inviting company',staffAccess.owner==='a'&&staffAccess.role==='member'&&!staffAccess.blocked,{});
check('joined staff cannot create personal company',(await onboarding.POST(onboardReq('Forbidden Company'))).status===409,{});
check('new invited staff has no projects by default',staffAccess.projectIds?.length===0,{});
check('standalone staff cannot open other company file',(await getFile(fid)).status===404,{});
check('reused invitation rejected',(await company.POST(req('/api/company',{action:'accept',token:inviteToken}))).status===400,{});
sql.prepare("UPDATE company_members SET status='disabled' WHERE id='auth-staff'").run();check('disabling member immediately blocks existing session',(await accessModule.getCompanyAccess(staffAuth!)).blocked===true,{});
const savedMail=e.AUTH_EMAIL;delete e.AUTH_EMAIL;check('unconfigured email fails closed',(await ar('sign-up/email',{email:'no-mail@example.test',name:'No mail',password})).status===503,{});e.AUTH_EMAIL=savedMail;
check('password stored as hash not plaintext',sql.prepare('SELECT password FROM auth_account WHERE user_id=?').get(customer!.userId.slice(5))?.password!==newPassword,{});

// Additional expiry and origin boundaries.
check('cross-origin workspace mutation denied',(await data.POST(new NextRequest('http://localhost:5199/api/data',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:JSON.stringify({action:'project'})}))).status===403,{});
check('missing origin workspace mutation denied',(await data.POST(new NextRequest('http://localhost:5199/api/data',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}))).status===403,{});
ip++;check('external recovery redirect rejected',(await ar('request-password-reset',{email,redirectTo:'https://evil.example/steal'})).status>=400,{});
check('external verification callback rejected',(await ar('send-verification-email',{email,callbackURL:'https://evil.example/steal'})).status>=400,{});
check('malformed verification token rejected',(await ar('verify-email?token=invalid')).status>=400,{});
ip++;await ar('request-password-reset',{email,redirectTo:'/login'});const expiredMail=mailbox.findLast(m=>m.purpose==='recovery')!;
sql.prepare('UPDATE auth_verification SET expires_at=0').run();const expiredResponse=await authRoutes.GET(new Request(expiredMail.url));check('expired recovery link cannot issue reset token',!new URL(expiredResponse.headers.get('location')||'/','https://auth.example.test').searchParams.has('token'),{status:expiredResponse.status});
sql.prepare('UPDATE auth_session SET expires_at=0').run();setSession(staffCookie);check('expired server session denied',await auth.getChatGPTUser()===null,{});
const {safeReturn}=await import('../app/login/auth-form');check('login return cannot escape origin',safeReturn('//evil.example')==='/'&&safeReturn('/\\evil.example')==='/'&&safeReturn('https://evil.example')==='/',{});check('login return preserves invitation',safeReturn('/join?token=synthetic')==='/join?token=synthetic',{});
const registration=await import('../app/registration-profile');
check('ABN format check accepts spaced checksum-valid number',registration.validAbn('10 000 000 000'),{});
check('ABN format rejects length checksum and letter errors',!registration.validAbn('1000000000')&&!registration.validAbn('10000000001')&&!registration.validAbn('10A00000000'),{});
const storedRegistration=sql.prepare('SELECT first_name,surname,business_name,abn,address,phone,rec FROM auth_user WHERE email=?').get(email)!;
check('signup profile persists normalized fields',storedRegistration.first_name==='Synthetic'&&storedRegistration.surname==='Customer'&&storedRegistration.abn==='10000000000'&&storedRegistration.rec==='TEST-REC-001',{});
const companyProfileRow=sql.prepare('SELECT company,abn,address,phone,rec,email FROM settings WHERE owner=?').get(customer!.userId)!;
check('verified onboarding copies company draft exactly once',companyProfileRow.company==='Synthetic Customer Ltd'&&companyProfileRow.abn==='10000000000'&&companyProfileRow.rec==='TEST-REC-001'&&companyProfileRow.email===email,{});
const invalidSignup=async(overrides:Record<string,unknown>)=>authRoutes.POST(new Request('https://auth.example.test/api/auth/sign-up/email',{method:'POST',headers:{origin:'https://auth.example.test','content-type':'application/json','cf-connecting-ip':'192.0.2.150'},body:JSON.stringify({firstName:'Validation',surname:'Fixture',businessName:'Validation Ltd',abn:'10000000000',address:'1 Test Street',phone:'0400000000',rec:'TEST-REC',email:'invalid-profile@example.test',password,...overrides})}));
for(const [name,overrides] of Object.entries({missingName:{firstName:''},missingSurname:{surname:''},missingBusiness:{businessName:''},badAbn:{abn:'10000000001'},missingAddress:{address:''},badPhone:{phone:'invalid'},missingRec:{rec:''},tooLongName:{firstName:'x'.repeat(81)}})){const response=await invalidSignup(overrides);check('registration rejects '+name,response.status===400,{});}
check('invalid registration creates no identity or company',!sql.prepare('SELECT id FROM auth_user WHERE email=?').get('invalid-profile@example.test'),{});
const priorMail=mailbox.length;ip++;const joinRegistration=await invalidSignup({email:'minimal-invite@example.test',signupIntent:'join',businessName:'',abn:'',address:'',rec:''});check('invited signup accepts personal details without new business',joinRegistration.status===200&&mailbox.length===priorMail+1,{});
await authRoutes.GET(new Request(mailbox.findLast(m=>m.to==='minimal-invite@example.test')!.url));const minimalLogin=await ar('sign-in/email',{email:'minimal-invite@example.test',password});setSession(minimalLogin.headers.get('set-cookie')?.split(';')[0]||'');
check('join intent cannot bypass company onboarding validation',(await onboarding.POST(onboardReq('Incomplete Ltd'))).status===400,{});
const minimalUser=await auth.getChatGPTUser();check('join intent grants no workspace or platform role',!!minimalUser&&(await accessModule.getCompanyAccess(minimalUser)).blocked===true&&!await (await import('../app/operator-access')).operatorRole(minimalUser),{});
check('invited member draft never replaces company settings',!sql.prepare('SELECT owner FROM settings WHERE owner=?').get(staffAuth!.userId),{});
ip++;const repeatRegistration=await ar('sign-up/email',{email,password,firstName:'Changed',surname:'Attacker',businessName:'Changed company'});check('repeat signup remains generic and cannot replace verified profile',repeatRegistration.status===200&&sql.prepare('SELECT first_name FROM auth_user WHERE email=?').get(email)?.first_name==='Synthetic',{});
const privateSession=await runtime.customerAuth().api.getSession({headers:(globalThis as any).__testHeaders});check('session response does not expose business draft fields',!!privateSession&&!('abn' in privateSession.user)&&!('phone' in privateSession.user)&&!('rec' in privateSession.user),{});
writeFileSync(out+'/results.json',JSON.stringify({baseline:'2fa2b4ec0a8c66d4cec2a66de6db185d0388b3d6',isolation:{database:'in-memory SQLite with real migrations',objects:'in-memory synthetic R2 adapter',identity:'explicit Sites fixture plus real Better Auth cookie sessions and auth email Worker with synthetic provider transport',network:'global fetch throws',productionSecrets:'none loaded'},results},null,2));console.log(JSON.stringify({passed:results.filter(r=>r.result==='PASS').length,failed:results.filter(r=>r.result==='FAIL').length}));

process.exitCode=results.some(r=>r.result==='FAIL')?1:0;
