import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {getCompanyAccess,companyDb} from '@/app/company-access';
import {canAccess} from '@/app/permissions';
const permission=(kind:string)=>kind==='time'?'Time':kind==='purchase-order'?'Purchase Orders':'';
const error=(message:string,status=400)=>NextResponse.json({error:message},{status});
const validDate=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;
export async function GET(req:NextRequest){const u=await getChatGPTUser();if(!u)return error('Sign in required.',401);const a=await getCompanyAccess(u),kind=req.nextUrl.searchParams.get('kind')||'',tab=permission(kind);if(!tab||!canAccess(a,tab))return error('Access is not available.',403);const db=companyDb();const projects=(await db.prepare('SELECT id,name,status FROM projects WHERE owner=? ORDER BY name').bind(a.owner).all()).results;const rows=(await db.prepare('SELECT r.id,r.project_id AS projectId,r.title,r.status,r.data,r.created,p.name AS projectName FROM projects p JOIN records r ON r.project_id=p.id AND r.owner=p.owner WHERE p.owner=? AND r.kind=? ORDER BY r.created DESC').bind(a.owner,kind).all<any>()).results.map(r=>({...r,data:JSON.parse(r.data)}));const colours=kind==='time'?await db.prepare('SELECT staff_colours FROM settings WHERE owner=?').bind(a.owner).first<any>():null;return NextResponse.json({projects,rows,colours:JSON.parse(colours?.staff_colours||'{}')});}
export async function POST(req:NextRequest){try{const u=await getChatGPTUser();if(!u)return error('Sign in required.',401);const a=await getCompanyAccess(u),b:any=await req.json(),tab=permission(b.kind);if(!tab||!canAccess(a,tab,true))return error('You do not have edit access.',403);const db=companyDb();const p=await db.prepare('SELECT id FROM projects WHERE id=? AND owner=?').bind(String(b.projectId||''),a.owner).first();if(!p)return error('Project unavailable.',404);let old:any=null;if(b.id){old=await db.prepare('SELECT * FROM records WHERE id=? AND owner=? AND project_id=? AND kind=?').bind(String(b.id),a.owner,b.projectId,b.kind).first();if(!old)return error('Record unavailable.',404);if(b.version!==Number(JSON.parse(old.data).version||0))return error('This record changed. Refresh and try again.',409);}
const d=b.data||{},str=(v:any,n=300)=>String(v||'').trim().slice(0,n);let data:any,status='',title='';if(!validDate(d.date))return error('Choose a valid date.');if(b.kind==='time'){const hours=Number(d.hours),rate=Number(d.rate);if(!str(d.employee)||!Number.isFinite(hours)||hours<=0||hours>24||!Number.isFinite(rate)||rate<0||rate>100000)return error('Enter a staff name, hours between 0 and 24, and a valid hourly cost.');data={employee:str(d.employee),date:d.date,hours,rate,package:str(d.package),notes:str(d.notes,4000)};title=data.employee;}
else {status=str(b.status);if(!['Draft','Issued','Received','Cancelled'].includes(status))return error('Choose a valid order status.');if(!str(d.supplier)||!Array.isArray(d.items)||!d.items.length||d.items.length>100)return error('Enter a supplier and at least one order item.');let cents=0;const items=[];for(const line of d.items){const quantity=Number(line.quantity),rate=Number(line.rate);if(!str(line.description)||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(rate)||rate<0)return error('Each item needs a description, positive quantity and valid price.');cents+=Math.round(quantity*rate*100);items.push({description:str(line.description),quantity,rate});}if(!Number.isSafeInteger(cents)||cents>1e14)return error('Order amount is too large.');if(d.requiredBy&&!validDate(d.requiredBy))return error('Choose a valid delivery date.');data={number:old?JSON.parse(old.data).number:'PO-'+crypto.randomUUID().slice(0,8).toUpperCase(),supplier:str(d.supplier),date:d.date,requiredBy:d.requiredBy||'',deliveryAddress:str(d.deliveryAddress,1000),notes:str(d.notes,4000),items,amount:cents/100};title=data.number+' · '+data.supplier;}
data.version=old?Number(JSON.parse(old.data).version||0)+1:1;data.updated=new Date().toISOString();data.updatedBy=u.fullName||u.email;const id=old?.id||crypto.randomUUID();if(old){const r=await db.prepare('UPDATE records SET title=?,status=?,data=? WHERE id=? AND owner=? AND data=?').bind(title,status,JSON.stringify(data),id,a.owner,old.data).run();if(!r.meta.changes)return error('This record changed. Refresh and try again.',409);}else await db.prepare('INSERT INTO records(id,owner,project_id,kind,title,status,data,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,a.owner,b.projectId,b.kind,title,status,JSON.stringify(data),new Date().toISOString()).run();return NextResponse.json({id});}catch(e){console.error('Workspace register',e);return error('Could not save this record. Please try again.',500);}}
