import {canAccessProject} from '@/app/project-access';
import {NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess} from '@/app/company-access';
import {canAccess} from '@/app/permissions';
import {melbourneDay} from '@/app/daily-review-model';
import {staffKey} from '@/app/calendar-model';
export async function GET(){const user=await getChatGPTUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});try{const a=await getCompanyAccess(user);if(a.blocked)return NextResponse.json({error:'Company access unavailable.'},{status:403});const db=companyDb(),day=melbourneDay(),prefs=a.appSettings?.reminders||{},items:any[]=[];
const kinds=[prefs.overdueTasks&&canAccess(a,'Tasks')?'task':'',prefs.pendingVariations&&canAccess(a,'Variations')?'variation':'',prefs.unansweredRfis&&canAccess(a,'RFIs')?'rfi':''].filter(Boolean);
if(kinds.length){const rows=(await db.prepare("SELECT r.*,p.name AS project_name FROM records r JOIN projects p ON p.id=r.project_id AND p.owner=r.owner WHERE r.owner=? AND p.status IN ('Active','On hold') AND r.kind IN ("+kinds.map(()=>'?').join(',')+") ORDER BY r.created DESC LIMIT 2000").bind(a.owner,...kinds).all<any>()).results;for(const r of rows){if(!canAccessProject(a,r.project_id))continue;let d:any={};try{d=JSON.parse(r.data)}catch{}let text='',tab='';if(r.kind==='task'&&!['Complete','Cancelled'].includes(r.status)&&d.due&&d.due<day){if(a.role==='member'&&d.assigneeKey!=='user:'+user.userId&&d.assigneeKey!=='email:'+user.email.toLowerCase())continue;text='Overdue task';tab='Tasks'}if(r.kind==='variation'&&r.status==='Pending'){text='Variation awaiting approval';tab='Variations'}if(r.kind==='rfi'&&['Issued','In Review','In review','Open','Sent'].includes(r.status)){text='RFI awaiting a response';tab='RFIs'}if(text)items.push({id:r.id,title:r.title||text,description:r.project_name+' · '+text,projectId:r.project_id,tab})}}
if(prefs.missingTimesheets&&canAccess(a,'Time')&&canAccess(a,'Schedule',true)){const from=new Date(day+'T12:00:00Z');from.setUTCDate(from.getUTCDate()-7);const start=from.toISOString().slice(0,10);const shifts=(await db.prepare("SELECT worker_name,project_id,project_name,date FROM schedule_entries WHERE owner=? AND kind='work' AND worker_key<>'' AND date>=? AND date<? ORDER BY date DESC LIMIT 500").bind(a.owner,start,day).all<any>()).results;const times=(await db.prepare("SELECT project_id,data FROM records WHERE owner=? AND kind='time' AND json_extract(data,'$.date')>=? AND json_extract(data,'$.date')<?").bind(a.owner,start,day).all<any>()).results;const logged=new Set(times.map(t=>{const d=JSON.parse(t.data);return [staffKey(d.employee||''),t.project_id,d.date].join('|')})),seen=new Set<string>();for(const s of shifts){if(!canAccessProject(a,s.project_id))continue;const key=[staffKey(s.worker_name),s.project_id,s.date].join('|');if(!logged.has(key)&&!seen.has(key)){seen.add(key);items.push({id:'time-'+key,title:s.worker_name+' · '+s.date,description:s.project_name+' · Scheduled work has no matching time entry',projectId:s.project_id,tab:'Time'})}}}
return NextResponse.json({items:items.slice(0,10),total:items.length,day},{headers:{'Cache-Control':'private, no-store'}});}catch(e){console.error('App reminders',e);return NextResponse.json({error:'Could not load reminders.'},{status:500});}}
