import {NextRequest,NextResponse} from 'next/server';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess,hashInvite} from '@/app/company-access';
import {subscriptionPlans} from '@/app/subscription-plans';
const config=()=>env as unknown as Record<string,string>;
const reply=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
async function access(){const u=await getChatGPTUser();if(!u)return null;const a=await getCompanyAccess(u);return {...a,email:u.email};}
// Live charging remains locked until webhook delivery and entitlement enforcement are commissioned.
function ready(){const c=config();return !!(c.STRIPE_SECRET_KEY?.startsWith('sk_test_')&&c.STRIPE_PORTAL_CONFIGURATION&&subscriptionPlans.every(p=>c['STRIPE_PRICE_'+p.id.replaceAll('-','_').toUpperCase()]));}
async function stripe(path:string,body?:Record<string,string>,key?:string){const r=await fetch('https://api.stripe.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${config().STRIPE_SECRET_KEY}`,'Stripe-Version':'2025-02-24.acacia',...(body?{'Content-Type':'application/x-www-form-urlencoded'}:{}),...(key?{'Idempotency-Key':key}:{})},body:body?new URLSearchParams(body):undefined});const d:any=await r.json();if(!r.ok)throw new Error('Stripe could not complete this request. Please try again or contact your administrator.');return d;}
const priceId=(id:string)=>config()['STRIPE_PRICE_'+id.replaceAll('-','_').toUpperCase()];
async function account(owner:string){return companyDb().prepare('SELECT customer_id FROM billing_accounts WHERE owner=?').bind(owner).first<{customer_id:string}>();}
async function subscriptions(customer:string){return (await stripe('subscriptions?customer='+encodeURIComponent(customer)+'&status=all&limit=100')).data.filter((s:any)=>!['canceled','incomplete_expired'].includes(s.status));}
export async function GET(req:NextRequest){const a=await access();if(!a)return reply({error:'Sign in required'},401);if(a.blocked||a.role==='member')return reply({error:'Administrator access required'},403);try{if(!ready())return reply({configured:false,mode:'not_connected',invoices:[],subscription:null});const row=await account(a.owner);if(!row)return reply({configured:true,mode:'test',invoices:[],subscription:null});const cursor=req.nextUrl.searchParams.get('after');if(cursor&&!/^in_[a-zA-Z0-9]+$/.test(cursor))return reply({error:'Invalid invoice page'},400);const [subs,inv]=await Promise.all([subscriptions(row.customer_id),stripe('invoices?customer='+encodeURIComponent(row.customer_id)+'&limit=20'+(cursor?'&starting_after='+encodeURIComponent(cursor):''))]);const s=subs[0];return reply({configured:true,mode:'test',customer:true,subscription:s?{status:s.status,plan:subscriptionPlans.find(p=>priceId(p.id)===s.items.data[0]?.price.id)?.name||'Subscription',cancelAtPeriodEnd:s.cancel_at_period_end}:null,invoices:inv.data.filter((i:any)=>i.status!=='draft').map((i:any)=>({id:i.id,number:i.number,date:i.created,status:i.status,total:i.total,currency:i.currency,pdf:i.invoice_pdf,url:i.hosted_invoice_url,description:i.lines?.data?.[0]?.description||'Stima subscription'})),hasMore:inv.has_more,next:inv.data.at(-1)?.id});}catch{return reply({error:'Billing could not be loaded. Please try again.'},502);}}
export async function POST(req:NextRequest){const a=await access();if(!a)return reply({error:'Sign in required'},401);if(a.blocked||a.role==='member')return reply({error:'Administrator access required'},403);if(req.headers.get('origin')!==req.nextUrl.origin)return reply({error:'Invalid request origin'},403);if(!ready())return reply({error:'Stripe setup is not complete. Payments are not available yet.'},503);try{const b:any=await req.json();if(!['checkout','portal'].includes(b.action))return reply({error:'Unknown billing action'},400);const p=subscriptionPlans.find(p=>p.id===b.plan);if(b.action==='checkout'&&!p)return reply({error:'Select a valid package'},400);let row=await account(a.owner);const ownerHash=await hashInvite(a.owner);if(!row){const c=await stripe('customers',{'email':a.email,'metadata[stima_owner]':a.owner},'stima-test-customer-'+ownerHash);await companyDb().prepare('INSERT INTO billing_accounts(owner,customer_id) VALUES(?,?) ON CONFLICT(owner) DO NOTHING').bind(a.owner,c.id).run();row=await account(a.owner);}if(!row)throw new Error('Account unavailable');const returnUrl=req.nextUrl.origin+'/?billing=return';const subs=await subscriptions(row.customer_id);if(b.action==='portal'||subs.length){const portal=await stripe('billing_portal/sessions',{customer:row.customer_id,configuration:config().STRIPE_PORTAL_CONFIGURATION,return_url:returnUrl});return reply({url:portal.url});}
const price=await stripe('prices/'+encodeURIComponent(priceId(p!.id)));if(price.currency!=='aud'||price.unit_amount!==p!.price*100||price.recurring?.interval!=='month'||price.recurring?.interval_count!==1||price.tax_behavior!=='exclusive'||!price.active)return reply({error:'This package is not configured correctly. Contact your administrator.'},503);
// Reuse one open session per company, even across concurrent clicks or different plan selections.
const lock=await companyDb().prepare('UPDATE billing_accounts SET checkout_lock=? WHERE owner=? AND (checkout_lock IS NULL OR checkout_lock < ?) RETURNING customer_id').bind(Date.now()+60000,a.owner,Date.now()).first();if(!lock)return reply({error:'Checkout is already opening. Please retry shortly.'},409);
try{const open=await stripe('checkout/sessions?customer='+encodeURIComponent(row.customer_id)+'&status=open&limit=100');for(const s of open.data){if(s.metadata?.stima_plan===p!.id)return reply({url:s.url});await stripe('checkout/sessions/'+s.id+'/expire',{});}const session=await stripe('checkout/sessions',{customer:row.customer_id,mode:'subscription','line_items[0][price]':priceId(p!.id),'line_items[0][quantity]':'1','payment_method_types[0]':'card','automatic_tax[enabled]':'true','customer_update[address]':'auto',billing_address_collection:'required',success_url:returnUrl,cancel_url:req.nextUrl.origin+'/?billing=cancelled','metadata[stima_plan]':p!.id,'subscription_data[metadata][stima_owner]':a.owner});return reply({url:session.url});}finally{await companyDb().prepare('UPDATE billing_accounts SET checkout_lock=NULL WHERE owner=?').bind(a.owner).run();}
}catch{return reply({error:'Stripe could not open billing. Please try again.'},502);}}
