import {limitMessage} from '@/app/account-limits';
import {trackUpload} from '@/app/upload-tracking';
import {NextRequest,NextResponse} from 'next/server';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess} from '@/app/company-access';
import {canAccess} from '@/app/permissions';
async function context(id:string,edit=false){const u=await getChatGPTUser();if(!u)return null;const a=await getCompanyAccess(u);if(a.blocked||!canAccess(a,'Drawings',edit))return null;const f:any=await companyDb().prepare("SELECT * FROM files WHERE id=? AND owner=? AND category='plans'").bind(id,a.owner).first();return f?{a,f}:null;}
export async function GET(req:NextRequest){const c=await context(req.nextUrl.searchParams.get('fileId')||'');if(!c)return NextResponse.json({error:'Drawing unavailable'},{status:403});const {results}=await companyDb().prepare('SELECT * FROM plan_revisions WHERE file_id=? ORDER BY number DESC').bind(c.f.id).all();return NextResponse.json({revisions:results.length?results:[{id:c.f.id,file_id:c.f.id,number:1,label:'Original',note:'',name:c.f.name,mime:c.f.mime,size:c.f.size,created:c.f.created}],latestId:c.f.current_revision_id||c.f.id});}
async function uploadRequest(req:NextRequest){const form=await req.formData();const c=await context(String(form.get('fileId')||''),true);if(!c)return NextResponse.json({error:'Drawing unavailable or permission denied'},{status:403});if(c.f.archived)return NextResponse.json({error:'Restore the drawing before adding a revision.'},{status:400});const file=form.get('file');if(!(file instanceof File)||!file.size||file.size>20*1024*1024||!['application/pdf','image/png','image/jpeg','image/webp'].includes(file.type))return NextResponse.json({error:'Choose a PDF, PNG, JPEG or WebP under 20 MB.'},{status:400});const label=String(form.get('label')||'').trim().slice(0,60);if(!label)return NextResponse.json({error:'Enter a revision label.'},{status:400});const id=crypto.randomUUID(),now=new Date().toISOString(),db=companyDb(),f=c.f;await (env as any).FILES.put(`${c.a.owner}/${id}`,await file.arrayBuffer(),{httpMetadata:{contentType:file.type}});try{await db.batch([db.prepare('INSERT OR IGNORE INTO plan_revisions (id,file_id,number,label,note,name,mime,size,created) VALUES (?,?,1,?,?,?,?,?,?)').bind(f.id,f.id,'Original','',f.name,f.mime,f.size,f.created),db.prepare('INSERT INTO plan_revisions (id,file_id,number,label,note,name,mime,size,created) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,f.id,f.revision_number+1,label,String(form.get('note')||'').slice(0,2000),file.name,file.type,file.size,now),db.prepare('UPDATE files SET current_revision_id=?,revision_number=?,mime=?,size=? WHERE id=? AND revision_number=?').bind(id,f.revision_number+1,file.type,file.size,f.id,f.revision_number)]);return NextResponse.json({id});}catch(e){await (env as any).FILES.delete(`${c.a.owner}/${id}`);return NextResponse.json({error:limitMessage(e)||'The drawing changed while uploading. Refresh and try again.'},{status:409});}}

export async function POST(req:NextRequest){let response:Response;try{response=await uploadRequest(req)}catch(e){console.error("Upload request failed",e);response=NextResponse.json({error:"Upload failed. Please try again."},{status:500})}await trackUpload("plan-revisions",response.status);return response;}
