import {projectStages,validateStages,type ProjectStage} from './project-stages';
export const moduleGroups=[
 {name:'Workspace',items:[{id:'myTasks',name:'My Tasks',description:'Personal tasks across projects.',tabs:['My Tasks']},{id:'dailyReview',name:'Daily review',description:'Review project changes and create follow-ups.',tabs:['Daily Review']},{id:'schedule',name:'Staff scheduling',description:'Plan shifts and leave across the team.',tabs:['Schedule']}]},
 {name:'Site work',items:[{id:'drawings',name:'Drawings',description:'Drawing folders, revisions, overlays and markups.',tabs:['Drawings']},{id:'sld',name:'Single line diagrams',description:'Switchboard schematics and SLD uploads.',tabs:['SLD']},{id:'specifications',name:'Specifications',description:'Project specifications.',tabs:['Specifications']},{id:'tasks',name:'Project tasks',description:'Assigned work and progress tracking.',tabs:['Tasks']},{id:'photos',name:'Photos',description:'Progress photos and folders.',tabs:['Photos']},{id:'diary',name:'Site diary',description:'Daily site records and calendar.',tabs:['Site Diary']}]},
 {name:'Management',items:[{id:'budgeting',name:'Budgeting & profitability',description:'Contract values, costs, budgets and profit reporting.',tabs:['Budget Overview','Costs']},{id:'time',name:'Time sheets & time tracking',description:'Actual staff hours, calendars and payroll review.',tabs:['Time']},{id:'rfis',name:'RFIs',description:'Project questions and responses.',tabs:['RFIs']},{id:'variations',name:'Variations',description:'Changes to scope and approval tracking.',tabs:['Variations']},{id:'purchaseOrders',name:'Purchase orders',description:'Project purchasing and order registers.',tabs:['Purchase Orders']}]},
 {name:'Documents & safety',items:[{id:'files',name:'Files',description:'General project files.',tabs:['Files']},{id:'om',name:'O&M manuals',description:'Handover manuals and exports.',tabs:['O&M Manuals']},{id:'coes',name:'COES',description:'Electrical safety certificate uploads.',tabs:['COES']},{id:'siteDocs',name:'Site Docs',description:'Reusable safety forms and project documents.',tabs:['Site Docs']},{id:'testTag',name:'Test & Tag register',description:'Equipment inspection records.',tabs:['Test & Tag Register']},{id:'equipment',name:'Equipment checks',description:'Daily checks and operator sign-off.',tabs:['EWP']}]},
] as const;
export const modules=moduleGroups.flatMap(g=>[...g.items]);
export const projectViews=['Overview','Project Setup','Drawings','SLD','Tasks','Time','Budget Overview','Costs','RFIs','Variations','Purchase Orders','Photos','Specifications','Files','Site Diary','Site Docs','Test & Tag Register','EWP','COES','O&M Manuals'];
export type AppSettings={modules:Record<string,boolean>;colour:string;theme:string;density:string;defaultView:string;dailyHours:number;workingDays:number[];shiftStart:string;stages:ProjectStage[];reminders:Record<string,boolean>};
export function defaultAppSettings():AppSettings{return {modules:Object.fromEntries(modules.map(m=>[m.id,true])),colour:'#2563ff',theme:'Light',density:'Comfortable',defaultView:'Overview',dailyHours:7.6,workingDays:[1,2,3,4,5],shiftStart:'07:00',stages:projectStages.map(s=>({...s})),reminders:{overdueTasks:true,pendingVariations:true,unansweredRfis:true,missingTimesheets:true}};}
export function normaliseAppSettings(raw:any,legacy:any={}):AppSettings{const d=defaultAppSettings();let v=raw;try{if(typeof v==='string')v=JSON.parse(v)}catch{v={}}v=v&&typeof v==='object'?v:{};return {...d,modules:Object.fromEntries(modules.map(m=>[m.id,v.modules?.[m.id]!==false])),colour:/^#[0-9a-f]{6}$/i.test(v.colour||legacy.colour||'')?(v.colour||legacy.colour):d.colour,theme:['Light','Dark','System'].includes(v.theme||legacy.theme)?v.theme||legacy.theme:d.theme,density:v.density==='Compact'?'Compact':'Comfortable',defaultView:projectViews.includes(v.defaultView)?v.defaultView:d.defaultView,dailyHours:Number.isFinite(v.dailyHours)&&v.dailyHours>0&&v.dailyHours<=16?v.dailyHours:d.dailyHours,workingDays:Array.isArray(v.workingDays)&&v.workingDays.length&&v.workingDays.every((n:any)=>Number.isInteger(n)&&n>=0&&n<=6)?[...new Set(v.workingDays)] as number[]:d.workingDays,shiftStart:/^([01]\d|2[0-3]):[0-5]\d$/.test(v.shiftStart)?v.shiftStart:d.shiftStart,stages:validateStages(v.stages)?v.stages:d.stages,reminders:Object.fromEntries(Object.keys(d.reminders).map(k=>[k,v.reminders?.[k]!==false]))};}
export function disabledTabs(config:AppSettings):string[]{return modules.filter(m=>config.modules[m.id]===false).flatMap(m=>[...m.tabs]);}
export function validateAppSettings(v:any){if(!v||typeof v!=='object'||!v.modules||modules.some(m=>typeof v.modules[m.id]!=='boolean')||Object.keys(v.modules).some(k=>!modules.some(m=>m.id===k)))throw new Error('Choose valid section settings.');if(!/^#[0-9a-f]{6}$/i.test(v.colour)||!['Light','Dark','System'].includes(v.theme)||!['Comfortable','Compact'].includes(v.density))throw new Error('Choose a valid appearance.');if(!projectViews.includes(v.defaultView)||disabledTabs(v).includes(v.defaultView))throw new Error('Choose an enabled default project view.');if(!Number.isFinite(v.dailyHours)||v.dailyHours<=0||v.dailyHours>16)throw new Error('Standard daily hours must be greater than zero and no more than 16.');if(!Array.isArray(v.workingDays)||!v.workingDays.length||new Set(v.workingDays).size!==v.workingDays.length||v.workingDays.some((n:any)=>!Number.isInteger(n)||n<0||n>6))throw new Error('Select at least one working day.');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(v.shiftStart)||Number(v.shiftStart.slice(0,2))*60+Number(v.shiftStart.slice(3))+v.dailyHours*60+30>=1440)throw new Error('The default shift must finish on the same day, including a 30-minute break.');if(!validateStages(v.stages))throw new Error('Use up to 40 uniquely named project stages.');if(!v.reminders||Object.keys(defaultAppSettings().reminders).some(k=>typeof v.reminders[k]!=='boolean'))throw new Error('Choose valid reminder settings.');return normaliseAppSettings(v);}
