'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Check,CreditCard,FileText} from 'lucide-react';
import {subscriptionPlans,subscriptionFeatures} from './subscription-plans';
import {SubscriptionComparison} from './subscription-comparison';
export function BillingSettings({invoices=false,admin}:{invoices?:boolean;admin:boolean}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(after?:string){setBusy(true);setError('');try{const r=await fetch('/api/billing'+(after?'?after='+encodeURIComponent(after):''),{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setData((old:any)=>after?{...d,invoices:[...old.invoices,...d.invoices]}:d);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(admin)load()},[admin]);
 async function open(action:string,plan?:string){setBusy(true);setError('');try{const r=await fetch('/api/billing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,plan})}),d:any=await r.json();if(!r.ok)throw new Error(d.error);const u=new URL(d.url);if(u.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(u.hostname))throw new Error('Invalid billing link');window.location.assign(u.href);}catch(e:any){setError(e.message);setBusy(false)}}
 if(!admin)return <section className="panel"><h2>Company billing</h2><p>Your company administrator manages subscriptions and invoices.</p></section>;
 return <>{error&&<div className="error" role="alert">{error} <Button variant="outline" disabled={busy} onClick={()=>load()}>Retry</Button></div>}{!data?<p>Loading billing…</p>:<>
 {!data.configured&&<div className="settings-notice"><strong>Stripe setup pending</strong><p>Online payments and card management will be available once billing setup is complete. No payment has been taken.</p></div>}{data.mode==='test'&&<div className="settings-notice"><strong>Stripe test mode</strong><p>Test payments only. No real money is charged and package limits are not enforced yet.</p></div>}
 {invoices?<section className="panel"><div className="site-docs-heading"><div><h2>Subscription invoices</h2><p>Invoices for your Stima package, including GST where applicable.</p></div><Button variant="outline" disabled={busy} onClick={()=>load()}>Refresh</Button></div>{data.invoices.length?<><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Date</th><th>Package</th><th>Total</th><th>Status</th><th>Documents</th></tr></thead><tbody>{data.invoices.map((i:any)=><tr key={i.id}><td>{i.number||i.id}</td><td>{new Date(i.date*1000).toLocaleDateString('en-AU')}</td><td>{i.description}</td><td>{new Intl.NumberFormat('en-AU',{style:'currency',currency:i.currency}).format(i.total/100)}</td><td>{i.status}</td><td>{i.url&&<a href={i.url} target="_blank" rel="noopener noreferrer">View invoice</a>}{i.pdf&&<> · <a href={i.pdf} target="_blank" rel="noopener noreferrer">Download PDF</a></>}</td></tr>)}</tbody></table></div>{data.hasMore&&<Button variant="outline" disabled={busy} onClick={()=>load(data.next)}>Load more</Button>}</>:<div className="empty-hero compact"><FileText size={28}/><h3>No subscription invoices yet</h3><p>Your invoices will appear here after Stripe billing is connected and an invoice is issued.</p></div>}</section>:<>
 <section className="panel subscription-current"><div><h2>Current subscription</h2><strong>{data.subscription?.plan||'No active subscription'}</strong><p>{data.subscription?.status||'Not activated'}{data.subscription?.cancelAtPeriodEnd?' · Cancels at period end':''} · AUD</p></div><Button className="primary" disabled={!data.configured||!data.customer||busy} onClick={()=>open('portal')}>Manage subscription</Button></section>
 <section className="panel"><h2><CreditCard size={20}/> Payment method & billing details</h2><p>Add or update cards, manage saved payment methods and change billing details securely through Stripe.</p><Button variant="outline" disabled={!data.configured||!data.customer||busy} onClick={()=>open('portal')}>Manage payment methods</Button><p className="site-docs-note">Choose a package below to add your first payment method at checkout. Stripe may require a replacement card before removing the one used by an active subscription.</p></section>
 <div className="subscription-grid">{subscriptionPlans.map(p=><section className="panel plan-card" key={p.id}><h3>{p.name}</h3><div className="plan-price">${p.price}<span> AUD / month · ex GST</span></div><div className="plan-limits"><span><strong>{p.users}</strong> users</span><span><strong>{p.projects}</strong> active projects</span><span><strong>{p.storage} GB</strong> storage</span></div><ul className="plan-feature-list">{subscriptionFeatures.filter(f=>p.level>=f.level).map(f=><li key={f.label}><Check size={16}/><span>{f.label}</span></li>)}</ul><Button className={p.id==='pro'?'primary':''} variant={p.id==='pro'?'default':'outline'} disabled={!data.configured||busy||data.subscription?.plan===p.name} onClick={()=>open('checkout',p.id)}>{data.subscription?.plan===p.name?'Current package':data.subscription?'Change package in Stripe':'Select '+p.name}</Button></section>)}</div><SubscriptionComparison/><p className="site-docs-note">Prices are in AUD per month, excluding GST. Review the final amount in Stripe before confirming. Package restrictions are not active yet.</p></>}
 </>}</>;
}
