'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowRight,Wallet,Clock3,FileText,SlidersHorizontal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import type {BudgetSummary} from './budget-math';
import {canAccess,type Access} from './permissions';
const money=(n:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(n);
const date=(s:string)=>new Date(s).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'});
export function BudgetOverview({projectId,access,onGo}:{projectId:string;access:Access;onGo:(tab:string)=>void}){
 const [data,setData]=useState<BudgetSummary|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[budget,setBudget]=useState(''),[saving,setSaving]=useState(false);
 const [updated,setUpdated]=useState<Date|null>(null),[refreshing,setRefreshing]=useState(false);
 const request=useRef<AbortController|null>(null);
 const load=useCallback(async(quiet=false)=>{request.current?.abort();const controller=new AbortController();request.current=controller;if(!quiet)setLoading(true);setRefreshing(true);try{const r=await fetch('/api/budget?project='+encodeURIComponent(projectId),{cache:'no-store',signal:controller.signal}),d:any=await r.json();if(!r.ok)throw new Error(d.error||'Could not refresh financials');if(controller.signal.aborted)return;setData(d);setUpdated(new Date());setError('')}catch(e:any){if(!controller.signal.aborted)setError(e.message)}finally{if(!controller.signal.aborted){setLoading(false);setRefreshing(false)}}},[projectId]);
 useEffect(()=>{setData(null);setUpdated(null);load();const refresh=()=>{if(document.visibilityState==='visible')load(true)};const timer=window.setInterval(refresh,30000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);request.current?.abort()}},[load]);
 const go=(tab:string,label:string)=>canAccess(access,tab)?<button className="budget-link" onClick={()=>onGo(tab)}>{label}<ArrowRight size={15}/></button>:null;
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch('/api/budget',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,costBudget:Number(budget)})}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setEditing(false);await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 return <div className="budget-overview"><div className="section-title module-heading"><div><h2>Budget Overview</h2><span>Project financials · AUD, excluding GST</span></div>{canAccess(access,'Budget Overview',true)&&<Button className="primary" disabled={!data} onClick={()=>{setBudget(data?.costBudget===null?'':String(data?.costBudget));setError('');setEditing(true)}}><SlidersHorizontal size={16}/>{data?.costBudget===null?'Set cost budget':'Edit cost budget'}</Button>}</div>{error&&!editing&&<div className="error" role="alert">{error}<button onClick={()=>load()}>Retry</button></div>}{loading?<div className="loading">Loading project financials…</div>:data&&<>
 <section className="profit-live-card" aria-label="Actual costs versus contract sum"><div className="profit-live-heading"><div><h3>Project profit</h3><p>Actual costs vs contract sum</p></div><div className="profit-refresh"><span role="status">{error?'Refresh failed · showing last loaded figures':refreshing?'Updating…':updated?`Updated ${updated.toLocaleTimeString('en-AU',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`:'Loading…'}</span><Button type="button" variant="outline" disabled={refreshing} onClick={()=>load(true)}>Refresh</Button></div></div><div className="profit-live-layout"><div className="profit-ring" role="img" aria-label={data.actualMargin===null?'Profit margin unavailable: set a positive contract sum':`${data.actualMargin.toFixed(1)}% profit margin to date; actual costs ${money(data.totalCost)}; contract sum ${money(data.revisedContract)}`}><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="48" fill="none" stroke="#34475a" strokeWidth="15"/>{data.actualMargin!==null&&<><circle cx="60" cy="60" r="48" fill="none" stroke={data.actualMargin<0?'#fb7b78':'#4bd19b'} strokeWidth="15"/>{data.actualMargin>=0&&<circle cx="60" cy="60" r="48" fill="none" stroke="#628cff" strokeWidth="15" pathLength="100" strokeDasharray={`${Math.max(0,Math.min(100,data.costShare||0))} 100`} transform="rotate(-90 60 60)"/>}</>}</svg><div><strong className={data.actualMargin!==null&&data.actualMargin<0?'profit-loss':''}>{data.actualMargin===null?'—':`${data.actualMargin.toFixed(1)}%`}</strong><span>{data.actualMargin!==null&&data.actualMargin<0?'Loss margin':'Profit margin'}</span><small>to date</small></div></div><div className="profit-live-values"><div><span>Contract sum <small>incl. approved variations</small></span><strong>{money(data.revisedContract)}</strong></div><div><span><i style={{background:'#628cff'}}/>Actual costs <small>labour + expenses</small></span><strong>{money(data.totalCost)}</strong></div><div className="profit-live-total"><span><i style={{background:data.contractRemaining<0?'#fb7b78':'#4bd19b'}}/>{data.contractRemaining<0?'Loss to date':'Profit remaining to date'}</span><strong className={data.contractRemaining<0?'profit-loss':''}>{money(data.contractRemaining)}</strong></div></div></div><p className="profit-live-note">{data.actualMargin===null?'Set a positive contract sum in Project Setup to calculate the margin. ':'Margin = (contract sum − actual costs) ÷ contract sum. '}Based on recorded costs only; future costs are excluded. Refreshes every 30 seconds while this page is visible.</p></section>
 {data.unpricedHours>0&&<p className="settings-notice">{data.unpricedHours.toFixed(2)} logged hours have no hourly cost. Labour costs are incomplete until rates are entered.</p>}
 <div className="budget-grid"><div className="budget-column"><section className="panel budget-card"><h3>Budget vs actual costs</h3><div className="budget-chart" role="img" aria-label={`Cost budget: ${data.costBudget===null?'not set':money(data.costBudget)}; actual costs: ${money(data.totalCost)}`}>
 {[{label:'Cost budget',value:data.costBudget,colour:'var(--brand)'},{label:'Actual costs',value:data.totalCost,colour:'#f28a16'}].map(bar=><div className="budget-chart-column" key={bar.label}><strong>{bar.value===null?'Not set':money(bar.value)}</strong><div className="budget-chart-track"><div style={{height:bar.value===null?'0':`${Math.max(0,bar.value)/Math.max(1,data.costBudget||0,data.totalCost)*100}%`,background:bar.colour}}/></div><span>{bar.label}</span></div>)}</div><p className="budget-muted">Actual costs include logged labour and recorded expenses.</p></section><section className="panel budget-card"><h3>Cost budget remaining</h3><strong className={'budget-value '+(data.budgetRemaining!==null&&data.budgetRemaining<0?'budget-negative':'')}>{data.budgetRemaining===null?'Not set':money(data.budgetRemaining)}</strong>{data.costBudget===null?<p className="budget-muted">Set the planned total cost of delivering this project to track remaining budget.</p>:<><p className="budget-muted">{data.budgetRemaining!<0?'Over budget':'Available budget'} · Budget {money(data.costBudget)}</p>{data.budgetUsed!==null&&<><Progress value={Math.max(0,Math.min(100,data.budgetUsed))} aria-label="Cost budget used"/><p className="budget-muted">{data.budgetUsed.toFixed(1)}% used</p></>}</>}</section><section className="panel budget-card"><h3>Planned gross margin</h3><strong className="budget-value">{data.plannedMargin===null?'—':`${data.plannedMargin.toFixed(1)}%`}</strong><p className="budget-muted">Based on revised contract less the full cost budget. This is a budget estimate, not realised profit.</p></section></div>
 <div className="budget-column"><section className="panel budget-card"><h3>Contract & variations</h3><div className="budget-row"><span>Original contract</span><strong>{money(data.contract)}</strong></div><div className="budget-row"><span>Approved variations</span><strong>{money(data.approvedVariations)}</strong></div><div className="budget-row budget-total"><span>Revised contract</span><strong>{money(data.revisedContract)}</strong></div><div className="budget-row"><span>Pending approval</span><strong>{money(data.pendingVariations)}</strong></div><p className="budget-muted">Pending variations are excluded from the revised contract.</p>{go('Variations','View variations')}</section><section className="panel budget-card"><h3>Cost breakdown</h3>{data.categories.map(c=><div className="budget-row" key={c.name}><span>{c.name}</span><strong>{money(c.value)}</strong></div>)}<div className="budget-row budget-total"><span>Total costs to date</span><strong>{money(data.totalCost)}</strong></div>{go('Costs','View costs')}</section><section className="panel budget-card"><h3>Invoices & payments</h3><FileText size={25} className="budget-empty-icon"/><strong className="budget-invoice-title">Invoice tracking is not connected</strong><p className="budget-muted">Invoiced amounts, unpaid balances and invoice-based profit will appear here once invoice tracking is added.</p></section></div>
 <div className="budget-column"><section className="panel budget-card"><h3>Largest expenses</h3>{data.largestCosts.length?data.largestCosts.map(row=><div className="budget-expense" key={row.id}><div><strong>{row.title||'Expense'}</strong><span>{money(row.amount)}</span></div><small>{[row.supplier,date(row.date)].filter(Boolean).join(' · ')}</small></div>):<p className="budget-muted">No expenses recorded yet.</p>}{data.expenseCount>0&&<p className="budget-muted">Showing {data.largestCosts.length} of {data.expenseCount} expenses. Logged labour is shown separately.</p>}{go('Costs','View expense register')}</section><section className="panel budget-card"><h3><Clock3 size={18}/>Time recorded</h3><strong className="budget-value">{Math.floor(data.hours)}<span>h </span>{String(Math.round(data.hours*60)%60).padStart(2,'0')}<span>m</span></strong><div className="budget-row"><span>Budget hours</span><strong>{data.budgetHours>0?data.budgetHours.toFixed(1)+' h':'Not set'}</strong></div>{data.budgetHours>0&&<><Progress value={Math.min(100,Math.max(0,data.hours/data.budgetHours*100))} aria-label="Labour hours budget used"/><p className="budget-muted">{Math.abs(data.budgetHours-data.hours).toFixed(1)} hours {data.hours>data.budgetHours?'over budget':'remaining'}</p></>}<div className="budget-row"><span>Labour cost</span><strong>{money(data.labour)}</strong></div>{go('Time','View time records')}</section></div></div></>}
 <Dialog open={editing} onOpenChange={v=>{if(!saving)setEditing(v)}}><DialogContent><DialogHeader><DialogTitle>Project cost budget</DialogTitle><DialogDescription>Enter the planned total cost to deliver this project, including labour, materials, subcontractors and other expenses. Exclude GST.</DialogDescription></DialogHeader>{error&&<p className="error" role="alert">{error}</p>}<form className="form-grid" onSubmit={save}><label className="field"><span>Total cost budget (AUD, ex GST)</span><input type="number" min="0" max="1000000000000" step="0.01" required value={budget} onChange={e=>setBudget(e.target.value)}/></label><div className="modal-actions"><Button type="button" variant="outline" disabled={saving} onClick={()=>setEditing(false)}>Cancel</Button><Button className="primary" disabled={saving}>{saving?'Saving…':'Save budget'}</Button></div></form></DialogContent></Dialog></div>
}
