'use client';
import {BillingSettings} from './billing-settings';
import {FeedbackInbox} from './feedback-inbox';
import {useEffect,useState,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Users,Plus,Copy,Check,ShieldCheck} from 'lucide-react';
import {permissionTabs,normalisePermissions,type Access,type Permissions} from './permissions';
type Member={id:string;name:string;email:string;role:string;permissions:string;status:string;expires:string|null};
export function CompanySettings({children,user,onChanged}:{children:ReactNode;user:string;onChanged:()=>void}){
 const [tab,setTab]=useState('company'),[data,setData]=useState<{access:Access;members:Member[];subscription:any}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Member|null|undefined>(undefined),[name,setName]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('member'),[permissions,setPermissions]=useState<Permissions>(normalisePermissions({})),[link,setLink]=useState(''),[copied,setCopied]=useState(false),[message,setMessage]=useState(''),[disable,setDisable]=useState<Member|null>(null);
 async function load(){try{const r=await fetch('/api/company',{cache:'no-store'}),v:any=await r.json();if(!r.ok)throw new Error(v.error);setData(v)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load();if(new URLSearchParams(window.location.search).has('billing'))setTab('subscription')},[]);
 async function action(body:any){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/company',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v:any=await r.json();if(!r.ok)throw new Error(v.error);if(v.token){setLink(`${window.location.origin}/?invite=${encodeURIComponent(v.token)}`);setCopied(false)}await load();onChanged();return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 function edit(member:Member|null){setEditing(member);setName(member?.name||'');setEmail(member?.email||'');setRole(member?.role||'member');setPermissions(normalisePermissions(member?JSON.parse(member.permissions):{}));setError('')}
 const admin=data&&data.access.role!=='member';
 return <><div className="page-heading"><div><div className="eyebrow">WORKSPACE</div><h1>Settings</h1><p>Company details, team access and subscription.</p></div></div>{error&&<div className="error" role="alert">{error}<button onClick={()=>{setError('');load()}}>Retry</button></div>}{message&&<p role="status" className="settings-notice">{message}</p>}{loading?<p>Loading settings…</p>:!data?<Button onClick={load}>Reload settings</Button>:<Tabs value={tab} onValueChange={setTab}><TabsList className="company-settings-tabs"><TabsTrigger value="company">Company</TabsTrigger>{admin&&<TabsTrigger value="users">Users & permissions</TabsTrigger>}<TabsTrigger value="subscription">Subscription</TabsTrigger><TabsTrigger value="invoices">Invoices</TabsTrigger>{admin&&<TabsTrigger value="feedback">Feedback inbox</TabsTrigger>}</TabsList><TabsContent value="company">{admin?children:<section className="panel"><h2>Your account</h2><p>Signed in as {user}.</p><p>Your company administrator manages company details and permissions.</p></section>}</TabsContent>
 {admin&&<TabsContent value="users"><div className="site-docs-heading"><div><h2>Company users</h2><p>Choose which project tabs each person can view or edit.</p></div><Button className="primary" onClick={()=>edit(null)}><Plus size={17}/>Add user</Button></div><div className="settings-notice"><strong>Joining the company</strong><p>Create a user, then share their invitation link. They must sign in with the same email address. This private app also needs to be shared with them through its sharing settings before they can open the link. No email is sent automatically.</p></div><div className="settings-owner"><ShieldCheck size={20}/><div><strong>Company owner</strong><p>Full access to all tabs, team management and subscription.</p></div></div>{data.members.length?<div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.members.map(m=><tr key={m.id}><td><strong>{m.name}</strong><small className="member-email">{m.email}</small></td><td>{m.role==='admin'?'Administrator':'Team member'}</td><td>{m.status==='pending'&&m.expires&&new Date(m.expires)<new Date()?'Invitation expired':m.status==='pending'?'Awaiting acceptance':m.status==='active'?'Active':'Disabled'}</td><td><div className="member-actions"><Button variant="outline" disabled={busy} onClick={()=>edit(m)}>Edit</Button><Button variant="outline" disabled={busy} onClick={async()=>{if(await action({action:'invite',id:m.id}))setMessage(m.status==='disabled'?'Access updated.':'New invitation link created.')}}>{m.status==='disabled'?'Reactivate':m.status==='pending'?'New link':'Refresh access'}</Button>{m.status!=='disabled'&&<Button variant="outline" disabled={busy} onClick={()=>setDisable(m)}>Disable</Button>}</div></td></tr>)}</tbody></table></div>:<div className="empty-hero compact"><Users size={28}/><h3>Add your first team member</h3><p>Give site staff access to the tools they need.</p></div>}</TabsContent>}
 {admin&&<TabsContent value="feedback"><FeedbackInbox/></TabsContent>}<TabsContent value="subscription"><BillingSettings admin={!!admin}/></TabsContent><TabsContent value="invoices"><BillingSettings invoices admin={!!admin}/></TabsContent></Tabs>}
 <Dialog open={editing!==undefined} onOpenChange={open=>{if(!open&&!busy)setEditing(undefined)}}><DialogContent className="member-dialog"><DialogHeader><DialogTitle>{editing?'Edit user':'Add company user'}</DialogTitle><DialogDescription>Administrators have full company access. Team members receive only the permissions you select.</DialogDescription></DialogHeader>{error&&<p className="error" role="alert">{error}</p>}<form className="form-grid" onSubmit={async e=>{e.preventDefault();if(await action({action:editing?'update':'add',id:editing?.id,name,email,role,permissions})){setEditing(undefined);setMessage('User saved.')}}}><label className="field"><span>Name</span><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Email</span><input type="email" required disabled={!!editing} value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Role</span><Select value={role} onValueChange={setRole}><SelectTrigger aria-label="User role"><SelectValue/></SelectTrigger><SelectContent position="popper" align="start" sideOffset={6}><SelectItem value="member">Team member</SelectItem><SelectItem value="admin">Administrator</SelectItem></SelectContent></Select></label>{role==='member'?<div className="permission-matrix"><div className="permission-line"><strong>Project tab</strong><strong>View</strong><strong>Edit</strong></div>{permissionTabs.map(t=><div className="permission-line" key={t}><span>{t}</span><Checkbox aria-label={`View ${t}`} checked={permissions[t].view} onCheckedChange={v=>setPermissions({...permissions,[t]:{view:v===true,edit:v===true&&permissions[t].edit}})}/><Checkbox aria-label={`Edit ${t}`} checked={permissions[t].edit} onCheckedChange={v=>setPermissions({...permissions,[t]:{view:permissions[t].view||v===true,edit:v===true}})}/></div>)}</div>:<p className="settings-notice">Full access to all projects, company details, users and subscription requests.</p>}<div className="modal-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setEditing(undefined)}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Saving…':'Save user'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!link} onOpenChange={v=>{if(!v)setLink('')}}><DialogContent><DialogHeader><DialogTitle>Invitation link ready</DialogTitle><DialogDescription>Share this link with the user. It expires in seven days. Make sure they also have access to this private app.</DialogDescription></DialogHeader><input className="invite-link" readOnly value={link} aria-label="Invitation link" onFocus={e=>e.target.select()}/><Button onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true)}catch{setMessage('Select the link and copy it manually.')}}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'Copied':'Copy invitation link'}</Button></DialogContent></Dialog>
 <Dialog open={!!disable} onOpenChange={v=>{if(!v)setDisable(null)}}><DialogContent><DialogHeader><DialogTitle>Disable {disable?.name}?</DialogTitle><DialogDescription>Their company access will stop. Their saved work will remain available.</DialogDescription></DialogHeader><Button disabled={busy} onClick={async()=>{if(await action({action:'disable',id:disable?.id}))setDisable(null)}}>Disable access</Button></DialogContent></Dialog>

 </>;
}
export function CompanyInvitation({onJoined}:{onJoined:()=>void}){const [token,setToken]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{setToken(new URLSearchParams(window.location.search).get('invite')||'')},[]);return <Dialog open={!!token}><DialogContent showCloseButton={false}><DialogHeader><DialogTitle>Join your company</DialogTitle><DialogDescription>Accept this invitation using the email address your administrator added. This account will use the company workspace and its assigned permissions.</DialogDescription></DialogHeader>{error&&<p role="alert">{error}</p>}<Button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/company',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'accept',token})}),d:any=await r.json();if(!r.ok)throw new Error(d.error);history.replaceState(null,'',window.location.pathname);setToken('');onJoined()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{busy?'Joining…':'Accept invitation'}</Button><Button variant="outline" disabled={busy} onClick={()=>{history.replaceState(null,'',window.location.pathname);setToken('')}}>Cancel</Button></DialogContent></Dialog>}
