import {canAccess,fileTab,recordTab,type Access} from './permissions';
export const reviewCategories=['record:task','record:time','record:cost','record:rfi','record:variation','record:diary','record:ewp','record:test-tag','file:plans','file:sld','file:photos','file:task-photo','file:specifications','file:files','file:coes','file:om-document','file:om-logo','file:ewp-photo','file:site-swms','file:site-prestart','file:site-permits','file:site-msds','file:site-ohs','safety','om'];
export function reviewTab(category:string){return category.startsWith('record:')?recordTab(category.slice(7)):category.startsWith('file:')?fileTab(category.slice(5)):category==='safety'?'Site Docs':category==='om'?'O&M Manuals':''}
export function reviewAllowed(a:Access,category:string){return canAccess(a,'Tasks')&&canAccess(a,reviewTab(category))}
export function melbourneDay(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Melbourne',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
export function validDay(day:string){return /^\d{4}-\d{2}-\d{2}$/.test(day)&&!isNaN(Date.parse(day))&&new Date(day).toISOString().slice(0,10)===day}
export function dayBounds(day:string){function midnight(d:string){const target=Date.parse(d+'T00:00:00Z');let guess=target;for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Australia/Melbourne',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(guess));const p=Object.fromEntries(parts.map(v=>[v.type,v.value]));const actual=Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute,+p.second);guess+=target-actual;}return new Date(guess).toISOString();}const next=new Date(Date.parse(day)+86400000).toISOString().slice(0,10);return {start:midnight(day),end:midnight(next)}}
const parse=(s:string|null)=>{try{return s?JSON.parse(s):null}catch{return null}};
const money=(n:any)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(n)||0);
export function reviewItem(row:any){const before=parse(row.before_data),after=parse(row.after_data),current=after||before||{},d=current.data||{},prev=before?.data||{},tab=reviewTab(row.category);let title='Review '+(row.title||tab),fact=`${row.title||tab} was ${row.operation==='insert'?'added':row.operation==='delete'?'removed':'updated'}.`,suggestion='Check the recorded change and confirm whether follow-up is needed.',priority='Normal';
 if(row.category==='record:time'){title='Verify time entry'+(d.employee?' · '+d.employee:'');fact=before&&after&&prev.hours!==d.hours?`Hours changed from ${prev.hours??'not recorded'} to ${d.hours??'not recorded'}.`:`${d.hours??'Unspecified'} hours recorded${d.employee?' for '+d.employee:''}${d.date?' on '+d.date:''}.`;suggestion='Confirm the hours and work package with the site record.';}
 if(row.category==='record:cost'){title=d.invoice?'Check invoice '+d.invoice:'Check expense · '+row.title;fact=`${money(d.amount)} ex GST${d.supplier?' · '+d.supplier:''}${d.invoice?' · Invoice '+d.invoice:''}.`;suggestion='Check the amount, supplier and invoice reference against the order or delivery. Review does not authorise payment.';}
 if(row.category==='record:rfi'){title='Review RFI · '+row.title;fact=`Status: ${current.status||'Not recorded'}${d.due?' · Response due '+d.due:''}.`;suggestion=['Closed','Responded'].includes(current.status)?'Check the response and whether related work can proceed.':'Check whether a response or follow-up with the recipient is needed.';if(d.due&&d.due<=melbourneDay()&&!['Closed','Responded','Draft'].includes(current.status))priority='High';}
 if(row.category==='file:plans'||row.category==='file:sld'){title='Review drawing · '+row.title;fact=before&&after&&before.revision!==after.revision?`Revision changed from ${before.revision} to ${after.revision}.`:`${row.title} · Revision ${current.revision||1}.`;suggestion='Compare the drawing with the previous revision, check for scope changes and confirm the site team has the current version.';}
 if(row.category==='safety'){title='Review Site Doc · '+row.title;fact=`Status: ${current.status||'Not recorded'}.`;suggestion='Check the form details, required fields and sign-off before relying on it for site work.';if(current.status==='Ready for review')priority='High';}
 if(row.category==='record:ewp'){title='Review equipment check · '+row.title;fact=`${d.signedAt?'Signed':'Not signed'}${d.hasDefects?' · Defects recorded':''}.`;suggestion=d.hasDefects?'Review the reported defects and arrange the appropriate action before equipment use.':'Check the daily inspection and operator sign-off.';if(d.hasDefects)priority='High';}
 if(row.category==='record:variation'){fact=`Variation status: ${current.status||'Not recorded'}.`;suggestion='Review the scope, price and approval status. Check for a related RFI.';}
 if(row.category==='record:diary'){suggestion='Check work completed, reported delays and any follow-up required.';}
 if(row.operation==='delete'){fact='This source record was deleted. The last saved snapshot is retained below.';suggestion='Confirm the deletion was intended and check whether any related work needs follow-up.';title='Review removal · '+(row.title||tab);}
 const details:Record<string,string>={};if(Array.isArray(d.fields))details['form fields']=d.fields.map((f:any)=>String(f.label||'Field')+': '+String(f.value||'Not entered')).join('\n').slice(0,10000);if(Array.isArray(d.checks))details['checklist']=d.checks.map((f:any)=>String(f.label||f.text||'Check')+': '+String(f.result||f.value||'Not recorded')).join('\n').slice(0,10000);for(const [k,v]of Object.entries(current)){if(k!=='data'&&v!==null&&typeof v!=='object')details[k]=String(v)}for(const [k,v]of Object.entries(d)){if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')details[k]=String(v).slice(0,5000)}
 return {id:row.id,projectId:row.project_id,projectName:row.projectName,sourceType:row.source_type,sourceId:row.source_id,category:row.category,tab,title,fact,suggestion,priority,occurred:row.occurred,operation:row.operation,details,decision:row.decision||null,actor:row.actor||null,decided:row.decided||null,taskId:row.task_id||null};}
