'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {ArrowDown,ArrowUp,GripVertical,LayoutDashboard,RotateCcw,Save} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {defaultDashboardLayout,normaliseDashboardLayout,moveDashboardWidget,type DashboardLayout,type DashboardWidgetId} from './dashboard-layout-model';
export type DashboardWidget={id:DashboardWidgetId;label:string;content:ReactNode};
export function DashboardEditor({widgets}:{widgets:DashboardWidget[]}){
 const [saved,setSaved]=useState(defaultDashboardLayout),[draft,setDraft]=useState(defaultDashboardLayout),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[dragging,setDragging]=useState<DashboardWidgetId|null>(null),[target,setTarget]=useState<DashboardWidgetId|null>(null);
 async function load(signal?:AbortSignal){setLoading(true);setError('');try{const r=await fetch('/api/dashboard-layout',{cache:'no-store',signal});const d=await r.json() as {layout:DashboardLayout;version:number;error?:string};if(!r.ok)throw Error(d.error||'Could not load your layout.');if(signal?.aborted)return;const layout=normaliseDashboardLayout(d.layout);setSaved(layout);setDraft(layout);setVersion(d.version);}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Could not load your layout.');}finally{if(!signal?.aborted)setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[]);
 const dirty=JSON.stringify(draft)!==JSON.stringify(saved);
 useEffect(()=>{if(!editing||!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editing,dirty]);
 const current=editing?draft:saved,available=new Map(widgets.map(w=>[w.id,w]));const shown=current.order.filter(id=>available.has(id)&&!current.hidden.includes(id));
 function move(id:DashboardWidgetId,to:DashboardWidgetId){setDraft(d=>moveDashboardWidget(d,id,to));setMessage(`${available.get(id)?.label} moved.`);}
 function step(id:DashboardWidgetId,delta:number){const index=shown.indexOf(id),to=shown[index+delta];if(to)move(id,to);}
 async function save(){if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/dashboard-layout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({layout:draft,version})});const d=await r.json() as {layout:DashboardLayout;version:number;error?:string};if(!r.ok)throw Error(d.error||'Could not save your layout.');const layout=normaliseDashboardLayout(d.layout);setSaved(layout);setDraft(layout);setVersion(d.version);setEditing(false);setMessage('Dashboard layout saved for your account.');}catch(e){setError(e instanceof Error?e.message:'Could not save your layout.');}finally{setBusy(false);}}
 function cancel(){setDraft(saved);setEditing(false);setError('');setMessage('Layout changes discarded.');setDragging(null);setTarget(null);void load();}
 return <section className={'dashboard-customisation '+(editing?'is-editing':'')} aria-label="Dashboard widgets">
 <div className="dashboard-edit-toolbar"><div>{editing&&<><h2>Edit widgets</h2><p>Your layout · saved for your account in this company</p><small>{dirty?'Unsaved changes':'No unsaved changes'}</small></>}</div><div className="member-actions">{editing?<><Button variant="ghost" disabled={busy} onClick={()=>{setDraft(defaultDashboardLayout());setMessage('Default layout restored in your draft. Save layout to keep it.');}}><RotateCcw size={16}/>Reset to default</Button><Button variant="outline" disabled={busy} onClick={cancel}>Cancel</Button><Button disabled={busy} onClick={()=>void save()}><Save size={16}/>{busy?'Saving…':'Save layout'}</Button></>:<Button variant="outline" disabled={loading||!!error} onClick={()=>{setDraft(saved);setEditing(true);setMessage('');}}><LayoutDashboard size={16}/>Edit widgets</Button>}</div></div>
 {error&&<div className="error" role="alert"><span>{error}</span>{!editing&&<Button variant="outline" onClick={()=>void load()}>Retry layout</Button>}</div>}
 <p className="dashboard-layout-status" role="status">{loading?'Loading your layout…':message}</p>
 {editing&&<p className="dashboard-edit-hint">Drag the handles, or use the move buttons. On a focused handle, press the up or down arrow. Leaving this page discards unsaved changes.</p>}
 <div className="dashboard-edit-body"><div className="dashboard-widget-grid">{shown.map((id,index)=>{const w=available.get(id)!;return <section className={'dashboard-widget dashboard-widget-'+id+(target===id?' drop-target':'')+(dragging===id?' is-dragging':'')} key={id} data-dashboard-widget={id} aria-label={w.label} onDragOver={e=>{if(editing&&dragging&&!busy){e.preventDefault();e.dataTransfer.dropEffect='move';setTarget(id);}}} onDrop={e=>{e.preventDefault();if(dragging&&!busy)move(dragging,id);setDragging(null);setTarget(null);}}>
 {editing&&<div className="dashboard-widget-controls"><span>{w.label}</span><button type="button" className="dashboard-drag-handle" draggable={!busy} disabled={busy} aria-label={`Move ${w.label}; use up and down arrow keys`} onDragStart={e=>{e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',id);setDragging(id);}} onDragEnd={()=>{setDragging(null);setTarget(null);}} onKeyDown={e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();step(id,e.key==='ArrowUp'?-1:1);}}}><GripVertical size={18}/></button><Button variant="outline" size="icon" disabled={busy||index===0} aria-label={`Move ${w.label} earlier`} onClick={()=>step(id,-1)}><ArrowUp size={16}/></Button><Button variant="outline" size="icon" disabled={busy||index===shown.length-1} aria-label={`Move ${w.label} later`} onClick={()=>step(id,1)}><ArrowDown size={16}/></Button></div>}
 {target===id&&dragging!==id&&<div className="dashboard-drop-label">Drop to move here</div>}{w.content}</section>;})}{!shown.length&&<div className="empty-hero"><h2>No widgets selected</h2><p>Use Edit widgets to restore the sections you want to see.</p></div>}</div>
 {editing&&<aside className="dashboard-manage" aria-label="Manage widgets"><h3>Manage widgets</h3><p>Choose what appears on your dashboard.</p><small>{shown.length} of {widgets.length} visible</small>{draft.order.filter(id=>available.has(id)).map(id=><label key={id}><span>{available.get(id)!.label}</span><input type="checkbox" role="switch" aria-label={`Show ${available.get(id)!.label}`} checked={!draft.hidden.includes(id)} disabled={busy} onChange={e=>{const checked=e.target.checked;setDraft(d=>({...d,hidden:checked?d.hidden.filter(v=>v!==id):[...d.hidden,id]}));}}/></label>)}<p>Just for you. Your teammates keep their own layouts.</p></aside>}</div></section>;
}
