'use client';
import type {ReactNode} from 'react';
import {ArrowRight,FolderOpen,Plus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {DashboardEditor,type DashboardWidget} from './dashboard-editor';
import {DashboardInsights} from './dashboard-insights';
import {projectStatuses} from './project-statuses';
export function DashboardHome({userName,projects,search,admin,showCosts,showHours,onOpen,onNew,onProjects,reminders}:{userName:string;projects:any[];search:string;admin:boolean;showCosts:boolean;showHours:boolean;onOpen:(id:string)=>void;onNew:()=>void;onProjects:()=>void;reminders?:ReactNode}){
 const rows=[...projects].sort((a,b)=>(b.lastActivity||b.created).localeCompare(a.lastActivity||a.created)||a.name.localeCompare(b.name)).filter(p=>['Active','On hold'].includes(p.status)&&`${p.name} ${p.builder} ${p.client} ${p.number}`.toLowerCase().includes(search.toLowerCase())).slice(0,3);
 const money=(v:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(v||0);
 const widgets:DashboardWidget[]=[...(showCosts?[{id:'portfolio' as const,label:'Contract portfolio',content:<DashboardInsights projects={projects} showCosts={true} onOpen={onOpen} widget="portfolio"/>}]:[]),{id:'activity',label:'Project activity',content:<DashboardInsights projects={projects} showCosts={false} onOpen={onOpen} widget="activity"/>},{id:'status',label:'Project status',content:<div className="overview-ribbon dashboard-status-ribbon">{projectStatuses.map(status=><div className={'stat status-stat '+status.toLowerCase().replace(' ','-')} key={status}><span>{status}</span><strong>{projects.filter(p=>p.status===status).length}</strong><small>{{Active:'Currently underway','On hold':'Temporarily paused',Closed:'Completed jobs',Archived:'Stored for reference'}[status]}</small></div>)}</div>},{id:'recent',label:'Recently updated projects',content:<><div className="section-title"><div><h2>Recently updated projects</h2><span>Your three most recently updated active or on-hold jobs</span></div><Button variant="outline" onClick={onProjects}>View all projects <ArrowRight size={16}/></Button></div>{!rows.length?<div className="empty-hero"><FolderOpen size={28}/><h2>{projects.length?'No projects in this view':'Create your first project'}</h2><p>{projects.length?'Change the search or open the full project list.':'Add a job to start managing its plans, tasks and documents.'}</p>{projects.length>0&&<Button variant="outline" onClick={onProjects}>View all projects</Button>}</div>:<div className="project-grid">{rows.map(p=><button key={p.id} className="project-card builder-project-card" style={{borderLeftColor:p.builderColour||'var(--border)'}} onClick={()=>onOpen(p.id)}><div className="card-top"><span className="project-icon"><FolderOpen size={23}/></span><span className={'status '+(p.status==='On hold'?'on-hold':'')}><i/>{p.status}</span></div><h3>{p.name}</h3><p><span className="builder-project-badge"><i style={{background:p.builderColour||'var(--muted-foreground)'}}/>{p.builder||p.client||p.address||'Project workspace'}</span></p><div className="card-rule"/><div className="card-metrics">{showCosts&&<div><small>CONTRACT VALUE</small><strong>{money(p.contract)}</strong></div>}{showHours&&<div><small>BUDGET HOURS</small><strong>{p.budgetHours||'—'}</strong></div>}</div><div className="card-footer"><span>Updated {new Date(p.lastActivity||p.created).toLocaleString('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}</span><ArrowRight size={17}/></div></button>)}</div>}</>},...(reminders?[{id:'reminders' as const,label:'Needs attention',content:reminders}]:[])];
 return <><div className="page-heading"><div><div className="eyebrow">PLAN.FLO / WORKSPACE</div><h1 className="dashboard-greeting">{userName.trim()?`Welcome, ${userName.trim()}`:'Welcome back'}</h1><p>Your latest project activity at a glance.</p></div>{admin&&<Button className="primary" onClick={onNew}><Plus size={18}/>New project</Button>}</div><DashboardEditor widgets={widgets}/></>;
}
