'use client';
import {useCallback,useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {feedbackStatuses,type FeedbackItem} from './feedback-model';
export function FeedbackInbox(){
 const [items,setItems]=useState<FeedbackItem[]>([]),[filter,setFilter]=useState('All'),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/feedback?status=${encodeURIComponent(filter)}&offset=${offset}`,{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.items);setMore(d.hasMore)}catch(e:any){setError(e.message)}finally{setLoading(false)}},[filter,offset]);
 useEffect(()=>{load();window.addEventListener('planwire-feedback',load);return()=>window.removeEventListener('planwire-feedback',load)},[load]);
 async function status(item:FeedbackItem,value:string){setBusy(item.id);setError('');try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status',id:item.id,version:item.version,status:value})}),d:any=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <section className="feedback-inbox"><div className="site-docs-heading"><div><h2>Feedback inbox</h2><p>Messages from your company’s users.</p></div><div className="feedback-inbox-tools"><Select value={filter} onValueChange={v=>{setFilter(v);setOffset(0)}}><SelectTrigger aria-label="Filter feedback status"><SelectValue/></SelectTrigger><SelectContent position="popper" sideOffset={6}>{['All',...feedbackStatuses].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Button variant="outline" disabled={loading} onClick={load}>Refresh</Button></div></div>{error&&<p role="alert" className="error">{error}</p>}{loading?<p>Loading feedback…</p>:items.length?<div className="feedback-items">{items.map(item=><article key={item.id} className="panel feedback-item"><div className="feedback-item-top"><div><div className="feedback-meta"><span>{item.type}</span>{item.impact&&<span className={item.impact==='Blocking work'?'feedback-blocking':''}>{item.impact}</span>}<small>#{item.id.slice(0,8).toUpperCase()}</small></div><h3>{item.subject}</h3></div><Select value={item.status} disabled={!!busy} onValueChange={v=>status(item,v)}><SelectTrigger aria-label={`Status for ${item.subject}`}><SelectValue/></SelectTrigger><SelectContent position="popper" sideOffset={6}>{feedbackStatuses.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div><p className="feedback-message">{item.message}</p><footer><span>{item.sender_name} · {item.sender_email}</span><span>{new Date(item.created).toLocaleString('en-AU')}</span>{(item.section||item.project_name)&&<span>{[item.project_name,item.section].filter(Boolean).join(' · ')}</span>}</footer></article>)}</div>:<div className="subempty">{filter==='All'?'No feedback yet. Submissions from the Feedback button will appear here.':'No feedback with this status.'}</div>}<div className="feedback-pagination"><Button variant="outline" disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</Button><span>Page {offset/50+1}</span><Button variant="outline" disabled={loading||!more} onClick={()=>setOffset(offset+50)}>Next</Button></div></section>
}
