'use client';
import {useState} from 'react';
import {MessageSquare,Bug,Lightbulb,HelpCircle,Heart,CheckCircle2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {feedbackTypes,feedbackImpacts} from './feedback-model';
const icons=[Bug,Lightbulb,HelpCircle,Heart];
export function FeedbackButton({projectId,projectName,section,disabled=false}:{projectId:string;projectName:string;section:string;disabled?:boolean}){
 const [open,setOpen]=useState(false),[type,setType]=useState('Problem'),[impact,setImpact]=useState('Slowing work'),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[include,setInclude]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState(''),[id,setId]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'submit',id,type,impact,subject,message,projectId:include?projectId:'',section:include?section:''})});const result:any=await response.json();if(!response.ok)throw new Error(result.error);setReceipt(result.id);setSubject('');setMessage('');window.dispatchEvent(new Event('planwire-feedback'))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><Button type="button" className="feedback-launch" variant="outline" disabled={disabled} onClick={()=>{if(receipt||!id){setId(crypto.randomUUID());setReceipt('')}setOpen(true)}}><MessageSquare size={17}/><span>Feedback</span></Button><Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogContent className="feedback-dialog"><DialogHeader><DialogTitle>Help improve PLAN.FLO</DialogTitle><DialogDescription>Share what happened, what you need, or what is working well. Your company administrators can review it in Settings.</DialogDescription></DialogHeader>{receipt?<div className="feedback-success"><CheckCircle2 size={40}/><h3>Feedback received</h3><p>Your message has been saved to the feedback inbox.</p><small>Reference: {receipt.slice(0,8).toUpperCase()}</small><Button className="primary" onClick={()=>setOpen(false)}>Done</Button></div>:<form onSubmit={submit} className="form-grid"><fieldset disabled={busy} className="feedback-fields"><legend className="sr-only">Feedback details</legend><RadioGroup aria-label="Feedback category" value={type} onValueChange={setType} className="feedback-types">{feedbackTypes.map((value,i)=>{const Icon=icons[i];return <label key={value} className={type===value?'selected':''}><RadioGroupItem value={value}/><Icon size={18}/><span>{value}</span></label>})}</RadioGroup>{type==='Problem'&&<label className="field"><span>How is this affecting your work?</span><Select value={impact} onValueChange={setImpact}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent position="popper" sideOffset={6}>{feedbackImpacts.map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></label>}<label className="field"><span>Short title</span><input required maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What would you like us to know?"/></label><label className="field"><span>Details</span><textarea required maxLength={5000} rows={5} value={message} onChange={e=>setMessage(e.target.value)} placeholder={type==='Problem'?'What were you doing, what happened, and what did you expect?':'Tell us more about your feedback.'}/><small>{message.length}/5,000 characters</small></label><label className="feedback-context"><Checkbox checked={include} onCheckedChange={v=>setInclude(v===true)}/><span>Include current page: {section}{projectName?` · ${projectName}`:''}</span></label><p className="feedback-identity">Your signed-in name and email are included so administrators know who submitted it.</p></fieldset>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Close</Button><Button type="submit" className="primary" disabled={busy||!subject.trim()||!message.trim()}>{busy?'Sending…':'Send feedback'}</Button></div></form>}</DialogContent></Dialog></>
}
