'use client';
import {useState} from 'react';
import {Folder,FolderPlus,Pencil,FolderInput} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type FileFolder={id:string;category:string;name:string};
export type FolderFile={id:string;name:string;folderId?:string;category:string};
export function inFolder(file:FolderFile,folder:string){return folder==='all'||(folder==='unfiled'?!file.folderId:file.folderId===folder)}
export function FolderToolbar({folders,files,value,onChange,editable,onSave}:{folders:FileFolder[];files:FolderFile[];value:string;onChange:(id:string)=>void;editable:boolean;onSave:(body:any)=>Promise<boolean>}){
 const [mode,setMode]=useState(''),[name,setName]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const current=folders.find(f=>f.id===value);
 return <div className="folder-organiser"><div className="folder-organiser-top"><div><strong>Folders</strong><span>{current?current.name:value==='unfiled'?'Unfiled':'All files'}</span></div>{editable&&<div className="folder-actions"><Button variant="outline" onClick={()=>{setError('');setName('');setMode('create')}}><FolderPlus size={16}/>New folder</Button>{current&&<Button variant="outline" onClick={()=>{setError('');setName(current.name);setMode('rename')}}><Pencil size={15}/>Rename folder</Button>}</div>}</div><div className="folder-list" aria-label="File folders">{[{id:'all',name:'All files'},{id:'unfiled',name:'Unfiled'},...folders].map(folder=><button key={folder.id} className={'folder-filter '+(value===folder.id?'selected':'')} aria-pressed={value===folder.id} onClick={()=>onChange(folder.id)}><Folder size={17}/><span>{folder.name}</span><small>{files.filter(f=>inFolder(f,folder.id)).length}</small></button>)}</div><Dialog open={!!mode} onOpenChange={open=>{if(!open&&!saving)setMode('')}}><DialogContent><DialogHeader><DialogTitle>{mode==='rename'?'Rename folder':'New folder'}</DialogTitle><DialogDescription>{mode==='rename'?'Files in this folder will stay in place.':'Choose a custom group, such as Architectural, Electrical or Elevations.'}</DialogDescription></DialogHeader>{error&&<p className="error" role="alert">{error}</p>}<form className="form-grid" onSubmit={async e=>{e.preventDefault();setSaving(true);setError('');try{if(await onSave({action:mode,folderId:current?.id,name}))setMode('')}catch(e:any){setError(e.message||'Could not save the change.')}finally{setSaving(false)}}}><label className="field"><span>Folder name</span><input autoFocus required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><div className="modal-actions"><Button variant="outline" type="button" disabled={saving} onClick={()=>setMode('')}>Cancel</Button><Button className="primary" disabled={saving||!name.trim()}>{saving?'Saving…':'Save folder'}</Button></div></form></DialogContent></Dialog></div>
}
export function MoveFile({file,folders,onSave}:{file:FolderFile;folders:FileFolder[];onSave:(body:any)=>Promise<boolean>}){
 const [open,setOpen]=useState(false),[target,setTarget]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 return <><Button variant="outline" size="sm" onClick={()=>{setError('');setTarget(file.folderId||'');setOpen(true)}} aria-label={`Move ${file.name} to a folder`}><FolderInput size={15}/>Move</Button><Dialog open={open} onOpenChange={v=>{if(!saving)setOpen(v)}}><DialogContent><DialogHeader><DialogTitle>Move to folder</DialogTitle><DialogDescription>{file.name}</DialogDescription></DialogHeader>{error&&<p className="error" role="alert">{error}</p>}<form className="form-grid" onSubmit={async e=>{e.preventDefault();setSaving(true);setError('');try{if(await onSave({action:'move',fileId:file.id,folderId:target}))setOpen(false)}catch(e:any){setError(e.message||'Could not save the change.')}finally{setSaving(false)}}}><label className="field"><span>Destination</span><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Unfiled</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label><div className="modal-actions"><Button variant="outline" type="button" disabled={saving} onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={saving||target===(file.folderId||'')}>{saving?'Moving…':'Move file'}</Button></div></form></DialogContent></Dialog></>
}
