'use client';
import {useState} from 'react';
import {Archive,ArchiveRestore,FolderInput,Pencil} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {FileFolder,FolderFile} from './file-folders';
export function FileManagement({files,selected,onSelect,archived,onArchiveView,editable,folders,onSave}:{files:FolderFile[];selected:string[];onSelect:(ids:string[])=>void;archived:boolean;onArchiveView:(v:boolean)=>void;editable:boolean;folders:FileFolder[];onSave:(body:any)=>Promise<boolean>}){
 const [action,setAction]=useState(''),[target,setTarget]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const one=files.find(f=>f.id===selected[0]),extension=one?.name.match(/\.[^.]+$/)?.[0]||'';
 function open(a:string){setError('');setTarget('');setName(one?.name.slice(0,one.name.length-extension.length)||'');setAction(a)}
 return <><div className="file-management"><Tabs value={archived?'archived':'active'} onValueChange={v=>onArchiveView(v==='archived')}><TabsList aria-label="File status"><TabsTrigger value="active">Active files</TabsTrigger><TabsTrigger value="archived">Archived</TabsTrigger></TabsList></Tabs>{editable&&<div className="file-bulk-actions"><label className="file-select-all"><Checkbox checked={files.length>0&&files.slice(0,50).every(f=>selected.includes(f.id))} disabled={!files.length} onCheckedChange={checked=>onSelect(checked===true?files.slice(0,50).map(f=>f.id):[])}/>{files.length>50?'Select first 50':'Select all'}</label><span aria-live="polite">{selected.length} selected</span><Button variant="outline" disabled={!selected.length} onClick={()=>open('move')}><FolderInput size={15}/>Move</Button><Button variant="outline" disabled={selected.length!==1} onClick={()=>open('rename')}><Pencil size={15}/>Rename</Button><Button variant="outline" disabled={!selected.length} onClick={()=>open(archived?'restore':'archive')}>{archived?<ArchiveRestore size={15}/>:<Archive size={15}/>} {archived?'Restore':'Archive'}</Button></div>}</div>{archived&&<p className="file-archive-note">Archived files are kept with their folders and markups. Restore them to show them in active files again.</p>}
 <Dialog open={!!action} onOpenChange={v=>{if(!v&&!busy)setAction('')}}><DialogContent><DialogHeader><DialogTitle>{action==='rename'?'Rename file':`${action==='move'?'Move':action==='archive'?'Archive':'Restore'} ${selected.length} file${selected.length===1?'':'s'}`}</DialogTitle><DialogDescription>{action==='archive'?'These files will leave the active list. You can restore them from Archived at any time.':action==='restore'?'Files will return to their original folders in the active list.':action==='rename'?'The file extension and existing plan markups are preserved.':'Choose a destination for all selected files.'}</DialogDescription></DialogHeader>{error&&<p role="alert" className="error">{error}</p>}<form className="form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{if(await onSave({action,ids:selected,folderId:target,name})){setAction('');onSelect([])}}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{action==='move'&&<label className="field"><span>Destination folder</span><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Unfiled</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}{action==='rename'&&<label className="field"><span>File name</span><div className="file-rename-field"><input autoFocus required maxLength={250-extension.length} value={name} onChange={e=>setName(e.target.value)}/><span>{extension}</span></div></label>}<div className="modal-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setAction('')}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Saving…':action==='rename'?'Save name':action==='move'?'Move files':action==='archive'?'Archive files':'Restore files'}</Button></div></form></DialogContent></Dialog></>
}
export type UploadResult={name:string;status:'waiting'|'uploading'|'done'|'failed';error?:string};
export function UploadStatus({rows,busy,onClose}:{rows:UploadResult[];busy:boolean;onClose:()=>void}){return <Dialog open={rows.length>0} onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent showCloseButton={!busy}><DialogHeader><DialogTitle>{busy?'Uploading files':'Upload results'}</DialogTitle><DialogDescription>{rows.filter(r=>r.status==='done').length} of {rows.length} files uploaded. Maximum 20 MB per file.</DialogDescription></DialogHeader><div className="upload-results" aria-live="polite">{rows.map((row,i)=><div key={i}><strong>{row.name}</strong><span className={row.status==='failed'?'upload-failed':''}>{row.status==='done'?'Uploaded':row.status==='uploading'?'Uploading…':row.status==='waiting'?'Waiting':row.error||'Upload failed'}</span></div>)}</div>{!busy&&<><p className="file-archive-note">{rows.some(r=>r.status==='failed')?'Successful files are saved. Choose only failed files to try again.':'All files are saved to your selected destination.'}</p><Button className="primary" onClick={onClose}>Done</Button></>}</DialogContent></Dialog>}
