'use client';
import {useEffect,useState} from 'react';
import {IntegrationSetup} from './integration-setup';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
export function GmailIntegration(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/gmail',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{load().catch(e=>setError(e.message));const result=new URLSearchParams(window.location.search).get('gmail');if(result)setMessage(result==='connected'?'Gmail connected. Enable invoice matching when you are ready.':'Gmail was not connected. Try again when you are ready.');},[]);
 async function action(action:string,extra:any={}){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/gmail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})}),d:any=await r.json();if(!r.ok)throw Error(d.error);if(d.url){window.location.assign(d.url);return;}await load();setMessage(d.message||(action==='sync'?`${d.imported||0} invoices added for review.${d.hasMore?' More emails remain; sync again to continue.':''}`:'Gmail settings saved.'));window.dispatchEvent(new Event('invoices-updated'));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel invoice-integration"><div className="section-title"><div><div className="eyebrow">INTEGRATIONS</div><h2>Gmail · supplier invoices</h2><p>Match supplier invoices to projects using their purchase order reference.</p></div><span className="status">{data?.connected?'Connected':data?.ready?'Ready to connect':'Setup required'}</span></div><ol className="invoice-flow"><li>Add a PO reference in Project Setup.</li><li>Ask suppliers to include it on invoices.</li><li>Review matched invoices in Expenses or My Tasks before adding costs.</li></ol>{data?.connected?<><p><strong>{data.email}</strong></p><label className="invoice-sync-toggle"><Switch checked={data.enabled} disabled={busy||!data.canUseCosts} onCheckedChange={enabled=>action('enable',{enabled})}/>Automatically check for invoices while PLAN.FLO is open</label><p className="muted-text">Checks every five minutes when an administrator has the app open. The first sync checks the past 30 days. Background syncing while the app is closed is not enabled.</p><div className="member-actions"><Button disabled={busy||!data.enabled} onClick={()=>action('sync')}>{busy?'Working…':data.hasMore?'Continue sync':'Sync now'}</Button><Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Disconnect Gmail? Imported invoices will remain available.'))action('disconnect')}}>Disconnect</Button></div>{data.lastSync&&<p>Last completed sync: {new Date(data.lastSync).toLocaleString('en-AU')}</p>}{data.lastError&&<p className="error">{data.lastError}</p>}</>:<><div className="member-actions">{data?.ready&&<Button disabled={busy} onClick={()=>action('connect')}>Connect Gmail</Button>}<IntegrationSetup provider="Gmail" setup={data?.setup} onRefresh={load} onConnect={()=>action('connect')} busy={busy}/></div><p className="muted-text">{data?.ready?'Connect your company invoice mailbox when you are ready. Gmail access is read-only.':'Open Set up Gmail to see the remaining steps and check when account linking is ready.'}</p></>}{data&&!data.canUseCosts&&<p>Enable Costs in App settings to use invoice matching.</p>}{error&&<p className="error" role="alert">{error}<Button variant="outline" onClick={()=>load().catch(e=>setError(e.message))}>Retry</Button></p>}{message&&<p role="status" className="settings-notice">{message}</p>}</section>;
}
export function GmailAutoSync({enabled}:{enabled:boolean}){useEffect(()=>{if(!enabled)return;let stopped=false,running=false;const sync=async()=>{if(stopped||running||document.visibilityState!=='visible')return;running=true;try{const status=await fetch('/api/gmail',{cache:'no-store'});if(!status.ok)return;const d:any=await status.json();if(d.connected&&d.enabled&&!stopped){const r=await fetch('/api/gmail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sync'})});if(r.ok)window.dispatchEvent(new Event('invoices-updated'));}}catch{/* The integration panel reports sync failures. */}finally{running=false}};sync();const timer=setInterval(sync,300000);return()=>{stopped=true;clearInterval(timer)};},[enabled]);return null;}
