import {env} from 'cloudflare:workers';
import {integrationConfig,integrationSetup} from './integration-config';
import {companyDb,hashInvite} from './company-access';
import {decodeGmail,messageParts,messageText,matchInvoice,invoiceFields,type Reference} from './invoice-matching';
import {extractText,getDocumentProxy} from 'unpdf';
const scope='https://www.googleapis.com/auth/gmail.readonly';
export function gmailConfig(){return integrationConfig('gmail')}
export function gmailReady(){return integrationSetup('gmail').ready}
const b64=(b:Uint8Array)=>btoa(String.fromCharCode(...b));
async function key(){const bytes=decodeGmail(gmailConfig().encryptionKey);if(bytes.length!==32)throw new Error('Gmail encryption setup is incomplete.');return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt']);}
export async function encryptToken(value:string,owner:string){const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(owner)},await key(),new TextEncoder().encode(value));return b64(iv)+'.'+b64(new Uint8Array(bytes));}
export async function decryptToken(value:string,owner:string){const [iv,data]=value.split('.');const bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:decodeGmail(iv),additionalData:new TextEncoder().encode(owner)},await key(),decodeGmail(data));return new TextDecoder().decode(bytes);}
export async function googleToken(fields:Record<string,string>){const c=gmailConfig();const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,...fields}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Gmail authorisation expired or failed. Reconnect the account.');return r.json() as Promise<any>;}
export async function gmailRequest(path:string,token:string){const r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+path,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(r.status===401?'Gmail access expired. Reconnect the account.':r.status===429?'Gmail is busy. Try syncing again shortly.':'Gmail could not be read. Try again or reconnect.');return r.json() as Promise<any>;}
export async function beginGmail(owner:string,userId:string){if(!gmailReady())throw new Error('Gmail connection setup is not available yet.');const state=crypto.randomUUID()+crypto.randomUUID(),verifier=crypto.randomUUID()+crypto.randomUUID();const challenge=b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');await companyDb().prepare('DELETE FROM gmail_oauth_states WHERE expires<? OR owner=?').bind(Date.now(),owner).run();await companyDb().prepare('INSERT INTO gmail_oauth_states(state_hash,owner,user_id,verifier,expires) VALUES(?,?,?,?,?)').bind(await hashInvite(state),owner,userId,await encryptToken(verifier,owner),Date.now()+600000).run();const c=gmailConfig();return 'https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({client_id:c.clientId,redirect_uri:c.redirectUri,response_type:'code',scope,access_type:'offline',prompt:'consent select_account',state,code_challenge:challenge,code_challenge_method:'S256'});}
export async function completeGmail(owner:string,userId:string,state:string,code:string){const db=companyDb(),saved:any=await db.prepare('DELETE FROM gmail_oauth_states WHERE state_hash=? AND owner=? AND user_id=? AND expires>? RETURNING verifier').bind(await hashInvite(state),owner,userId,Date.now()).first();if(!saved)throw new Error('The connection request expired. Start again in Integrations.');const c=gmailConfig(),token=await googleToken({code,grant_type:'authorization_code',redirect_uri:c.redirectUri,code_verifier:await decryptToken(saved.verifier,owner)});if(!token.refresh_token||!String(token.scope||'').split(' ').includes(scope))throw new Error('Read-only Gmail access was not granted. Please reconnect and allow invoice reading.');const profile=await gmailRequest('profile',token.access_token);if(!profile.emailAddress)throw new Error('Gmail account details were unavailable.');await db.prepare("INSERT INTO gmail_connections(owner,email,refresh_token,enabled,updated) VALUES(?,?,?,0,?) ON CONFLICT(owner) DO UPDATE SET email=excluded.email,refresh_token=excluded.refresh_token,enabled=0,last_sync='',last_error='',cursor='',scan_after='',scan_before='',lock_until=0,updated=excluded.updated").bind(owner,profile.emailAddress,await encryptToken(token.refresh_token,owner),new Date().toISOString()).run();}
async function references(owner:string):Promise<Reference[]>{const db=companyDb();const projects=(await db.prepare("SELECT id,name,purchase_order_number FROM projects WHERE owner=? AND status IN ('Active','On hold')").bind(owner).all<any>()).results;const orders=(await db.prepare("SELECT r.project_id,json_extract(r.data,'$.number') AS number FROM records r JOIN projects p ON p.id=r.project_id AND p.owner=r.owner WHERE r.owner=? AND r.kind='purchase-order' AND r.status IN ('Issued','Received') AND p.status IN ('Active','On hold')").bind(owner).all<any>()).results;return [...projects.filter(p=>p.purchase_order_number).map(p=>({projectId:p.id,projectName:p.name,reference:p.purchase_order_number})),...orders.map(o=>({projectId:o.project_id,projectName:projects.find(p=>p.id===o.project_id)?.name||'',reference:String(o.number||'')}))];}
async function importMessage(owner:string,connection:any,message:any,token:string,refs:Reference[]){const db=companyDb(),parts=messageParts(message.payload),headers=message.payload?.headers||[];const header=(name:string)=>String(headers.find((h:any)=>h.name.toLowerCase()===name)?.value||'');const subject=header('Subject').slice(0,500),sender=header('From').slice(0,500),body=messageText(parts);const attachments=parts.filter(p=>p.filename&&p.body&&(p.mimeType==='application/pdf'||/\.pdf$/i.test(p.filename)||/^image\//.test(p.mimeType)));const pdfs=attachments.filter(p=>p.mimeType==='application/pdf'||/\.pdf$/i.test(p.filename));const images=attachments.filter(p=>/^image\/(png|jpeg)$/.test(p.mimeType)&&Number(p.body.size)>10000);const chosen=pdfs.length?pdfs:images;const candidates=chosen.length?chosen:[null];let count=0;
 for(const [index,part] of candidates.entries()){
 const sourceKey=connection.email.toLowerCase()+':'+message.id+':'+(part?.partId||String(index));if(await db.prepare('SELECT id FROM supplier_invoices WHERE owner=? AND source_key=?').bind(owner,sourceKey).first())continue;
 let bytes:Uint8Array|undefined,text='',warning='',fileId='';const id=crypto.randomUUID();
 if(part){if(Number(part.body.size)>8*1024*1024)warning='Attachment exceeds the 8 MB import limit. Open the original email to review it.';else{const attachment=part.body.data?part.body:await gmailRequest(`messages/${encodeURIComponent(message.id)}/attachments/${encodeURIComponent(part.body.attachmentId)}`,token);bytes=decodeGmail(attachment.data||'');if(bytes.length>8*1024*1024){bytes=undefined;warning='Attachment exceeds the import limit.';}else if(part.mimeType==='application/pdf'||/\.pdf$/i.test(part.filename)){let pdf;try{pdf=await getDocumentProxy(bytes.slice());if(pdf.numPages>50)throw new Error('Too many pages');const extracted=await extractText(pdf,{mergePages:true});text=String(extracted.text||'').slice(0,100000);if(!text.trim())warning='Scanned PDF: enter the reference and amounts manually.';}catch{warning='PDF text could not be read. Review the original invoice manually.';}finally{await pdf?.loadingTask.destroy();}}else warning='Photo invoice: enter the reference and amounts manually.';}}
 const combined=[subject,body,text,part?.filename||''].join('\n');const match=matchInvoice(combined,refs),fields=invoiceFields(text||body);
 const contentHash=bytes?Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(bytes)))).map(b=>b.toString(16).padStart(2,'0')).join(''):'';
 const duplicate:any=await db.prepare("SELECT id FROM supplier_invoices WHERE owner=? AND status<>'Ignored' AND ((?<>'' AND json_extract(data,'$.contentHash')=?) OR (?<>'' AND json_extract(data,'$.invoiceNumber')=? AND json_extract(data,'$.sender')=?)) LIMIT 1").bind(owner,contentHash,contentHash,fields.invoiceNumber,fields.invoiceNumber,sender).first();
 const now=new Date().toISOString(),data={...fields,supplier:sender,subject,sender,received:new Date(Number(message.internalDate)||Date.now()).toISOString(),references:match.references,warning:[warning,fields.warning,duplicate?'Possible duplicate invoice. Confirm before approving.':''].filter(Boolean).join(' '),duplicateOf:duplicate?.id||'',contentHash,filename:part?.filename||'',excerpt:(text||body).slice(0,12000)};
 try{const statements=[];if(bytes?.length){fileId=crypto.randomUUID();await (env as any).FILES.put(`${owner}/${fileId}`,bytes,{httpMetadata:{contentType:part.mimeType==='application/pdf'||/\.pdf$/i.test(part.filename)?'application/pdf':part.mimeType}});statements.push(db.prepare("INSERT INTO files(id,owner,project_id,category,name,mime,size,created) VALUES(?,?,?,'invoice',?,?,?,?)").bind(fileId,owner,match.projectId,String(part.filename).slice(0,250),part.mimeType==='application/pdf'||/\.pdf$/i.test(part.filename)?'application/pdf':part.mimeType,bytes.length,now));}
 statements.push(db.prepare('INSERT INTO supplier_invoices(id,owner,source_key,mailbox,message_id,project_id,status,match_reason,data,file_id,created) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,owner,sourceKey,connection.email,message.id,match.projectId,match.projectId?'Needs review':'Unmatched',match.reason,JSON.stringify(data),fileId,now));await db.batch(statements);count++;}catch(e){if(fileId)await (env as any).FILES.delete(`${owner}/${fileId}`);throw e;}
 }return count;
}
export async function syncGmail(owner:string){const db=companyDb(),connection:any=await db.prepare('SELECT * FROM gmail_connections WHERE owner=?').bind(owner).first();if(!connection?.refresh_token||!connection.enabled)return {imported:0,skipped:true};const until=Date.now()+240000;const locked=await db.prepare('UPDATE gmail_connections SET lock_until=? WHERE owner=? AND lock_until<? AND enabled=1').bind(until,owner,Date.now()).run();if(!locked.meta.changes)return {imported:0,busy:true};try{
 const token=await googleToken({grant_type:'refresh_token',refresh_token:await decryptToken(connection.refresh_token,owner)});const after=connection.cursor?connection.scan_after:String(Math.floor((connection.last_sync?Date.parse(connection.last_sync)-86400000:Date.now()-30*86400000)/1000));const before=connection.cursor?connection.scan_before:String(Math.floor(Date.now()/1000));
 const query=`in:inbox -in:sent -in:spam -in:trash after:${after} before:${before} {invoice filename:pdf}`;const params=new URLSearchParams({q:query,maxResults:'10',...(connection.cursor?{pageToken:connection.cursor}:{})});const listed=await gmailRequest('messages?'+params,token.access_token);const refs=await references(owner);let imported=0;
 for(const entry of listed.messages||[]){const still:any=await db.prepare('SELECT enabled,refresh_token FROM gmail_connections WHERE owner=? AND lock_until=?').bind(owner,until).first();if(!still?.enabled||still.refresh_token!==connection.refresh_token)break;const message=await gmailRequest(`messages/${encodeURIComponent(entry.id)}?format=full`,token.access_token);imported+=await importMessage(owner,connection,message,token.access_token,refs);}
 await db.prepare("UPDATE gmail_connections SET cursor=?,scan_after=?,scan_before=?,last_sync=?,last_error='',lock_until=0 WHERE owner=? AND lock_until=?").bind(listed.nextPageToken||'',listed.nextPageToken?after:'',listed.nextPageToken?before:'',listed.nextPageToken?connection.last_sync:new Date(Number(before)*1000).toISOString(),owner,until).run();return {imported,hasMore:!!listed.nextPageToken};
 }catch(e:any){await db.prepare('UPDATE gmail_connections SET last_error=?,lock_until=0 WHERE owner=? AND lock_until=?').bind(String(e.message||'Sync failed').slice(0,500),owner,until).run();throw e;}}
