'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function IntegrationSetup({provider,setup,onRefresh,onConnect,busy=false}:{provider:'Gmail'|'Xero';setup:any;onRefresh:()=>Promise<unknown>;onConnect:()=>void;busy?:boolean}){
 const [open,setOpen]=useState(false),[checking,setChecking]=useState(false),[error,setError]=useState('');
 async function refresh(){setChecking(true);setError('');try{await onRefresh()}catch{setError('Could not check setup. Please try again.')}finally{setChecking(false)}}
 return <><Button variant="outline" onClick={()=>setOpen(true)}>Set up {provider}</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="modal integration-setup"><DialogHeader><DialogTitle>Set up {provider}</DialogTitle><DialogDescription>Complete the PLAN.FLO connection setup, then authorise your company account.</DialogDescription></DialogHeader>
 <ol><li><strong>Prepare the provider app</strong><p>The PLAN.FLO operator registers the app with {provider==='Gmail'?'Google and enables the Gmail API and consent screen':'Xero as a web app'}. Your company administrator then signs in to choose the account to link.</p><a href={provider==='Gmail'?'https://console.cloud.google.com/auth/overview':'https://developer.xero.com/app/manage'} target="_blank" rel="noreferrer">Open {provider==='Gmail'?'Google Cloud':'Xero developer portal'} ↗</a></li><li><strong>Finish secure setup</strong><p>The operator configures app credentials and encrypted connection storage in PLAN.FLO hosting. Credentials never go into this form.</p>{setup?.callbackUrl&&<label>Return address to register<input readOnly value={setup.callbackUrl} onFocus={e=>e.target.select()}/></label>}</li><li><strong>Check readiness</strong><ul>{setup?.checks?.map((c:any)=><li key={c.label}>{c.ready?'✓':'○'} {c.label} — {c.ready?'Ready':'Setup needed'}</li>)}</ul>{!setup&&<p>Check setup to load the current status.</p>}</li><li><strong>Link your account</strong><p>{provider==='Gmail'?'Choose your invoice mailbox and approve read-only Gmail access. Invoice checking stays off until you enable it.':'Authorise Xero and choose the organisation for this PLAN.FLO company. This connection reads payroll matching details; it does not send timesheets or run payroll.'}</p></li></ol>
 {error&&<p role="alert">{error}</p>}<div className="modal-actions"><Button variant="outline" disabled={checking||busy} onClick={refresh}>{checking?'Checking…':'Check setup again'}</Button>{setup?.ready&&<Button disabled={busy||checking} onClick={onConnect}>Connect {provider}</Button>}</div>{setup&&!setup.ready&&<p>Once the operator completes the items above, check again to enable account linking.</p>}</DialogContent></Dialog></>;
}
