import {PDFDocument,StandardFonts,rgb,type PDFPage} from 'pdf-lib';
import type {OmManual} from './om-model';
type Loader=(id:string)=>Promise<{bytes:ArrayBuffer;mime:string}>;
const clean=(s:unknown)=>String(s||'').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/[\u2013\u2014]/g,'-').replace(/[^\x20-\x7e\u00a0-\u00ff\n]/g,'?');
export async function buildOmPdf(manual:OmManual,load:Loader){
 const d=manual.data,pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);const ink=rgb(.09,.15,.24),blue=rgb(.09,.41,.95),muted=rgb(.38,.45,.55);const generated:PDFPage[]=[];let page:PDFPage,y=0,totalBytes=0;
 const cached=new Map<string,Awaited<ReturnType<Loader>>>();async function get(id:string){if(cached.has(id))return cached.get(id)!;const asset=await load(id);totalBytes+=asset.bytes.byteLength;if(totalBytes>100*1024*1024)throw new Error('The combined attachments exceed 100 MB. Reduce PDF sizes and export again.');cached.set(id,asset);return asset}
 function add(){page=pdf.addPage([595,842]);generated.push(page);y=785;page.drawText('OPERATION & MAINTENANCE',{x:45,y:815,font:bold,size:8,color:blue});return page}
 function line(value:string,size=11,heading=false){if(y<65)add();page.drawText(value,{x:45,y,font:heading?bold:font,size,color:heading?blue:ink});y-=size+7}
 function text(value:unknown,size=11,heading=false){const f=heading?bold:font;for(const paragraph of clean(value).split('\n')){let row='';for(const word of paragraph.split(/\s+/)){for(let start=0;start<word.length;start+=50){const piece=word.slice(start,start+50),next=row?row+' '+piece:piece;if(f.widthOfTextAtSize(next,size)>505){if(row)line(row,size,heading);row=piece;}else row=next}}line(row,size,heading)}}
 function field(label:string,value:string){text(label,9,true);text(value||'Not provided');y-=8}
 add();y=715;text('O&M MANUAL',26,true);y-=12;text(d.projectName,23);text(d.service||'Project handover',14);y-=22;field('REFERENCE / REVISION',`${d.reference||'—'} / ${d.revision||'—'}`);field('STATUS',manual.status);field('BUILDER',d.builder);field('SITE',d.address);field('PRACTICAL COMPLETION',d.completionDate);
 if(y<180)add();const logoY=y-110;const cover=page!;for(const [id,x,label] of [[d.builderLogo,45,'Builder'],[d.architectLogo,315,'Architect']] as const){if(!id)continue;try{const a=await get(id),img=a.mime.includes('png')?await pdf.embedPng(a.bytes):await pdf.embedJpg(a.bytes),scale=Math.min(180/img.width,75/img.height);cover.drawText(label,{x,y:logoY+90,font,size:9,color:muted});cover.drawImage(img,{x,y:logoY,width:img.width*scale,height:img.height*scale})}catch(e){throw new Error(`${label} logo could not be included. Replace it with a valid PNG or JPEG.`)}}
 const count=d.sections.length+3,tocPages:PDFPage[]=[];for(let i=0;i<Math.ceil(count/24);i++)tocPages.push(add());const entries:{title:string;page:number}[]=[];
 function section(title:string){add();entries.push({title,page:pdf.getPageCount()});text(title,18,true);y-=12}
 section('1. General information');field('PROJECT',d.projectName);field('SERVICE / WORK TYPE',d.service);field('SITE ADDRESS',d.address);field('DESCRIPTION',d.description);field('ARCHITECT',d.architectName);field('ARCHITECT PHONE',d.architectPhone);field('ARCHITECT EMAIL',d.architectEmail);field('ARCHITECT ADDRESS',d.architectAddress);
 section('2. Contacts');if(!d.contacts.length)text('No contacts entered.');for(const c of d.contacts){text(c.role||'Contact',13,true);field('NAME / COMPANY',[c.name,c.company].filter(Boolean).join(' / '));field('PHONE / EMAIL',[c.phone,c.email].filter(Boolean).join(' / '));field('ADDRESS',c.address);y-=8}
 section('3. Maintenance schedule');if(!d.maintenance.length)text('No maintenance tasks entered.');for(const [i,m] of d.maintenance.entries()){text(`${i+1}. ${m.equipment||'Equipment / system'}`,13,true);field('TASK',m.task);field('FREQUENCY / INTERVAL',m.frequency);field('RESPONSIBLE',m.responsible);y-=8}
 for(const [i,s] of d.sections.entries()){section(`${i+4}. ${s.title}`);text(s.body||(!s.fileIds.length?'No content entered.':'Supporting documents follow.'));for(const id of s.fileIds){try{const file=await get(id),source=await PDFDocument.load(file.bytes);if(pdf.getPageCount()+source.getPageCount()>1500)throw new Error('Manual exceeds 1,500 pages');const copied=await pdf.copyPages(source,source.getPageIndices());copied.forEach(p=>pdf.addPage(p));}catch(e:any){throw new Error(`Could not include a PDF in “${s.title}”. Check that it opens correctly and is not password-protected. ${e.message?.includes('exceed')?e.message:''}`)}}}
 tocPages.forEach((p,i)=>{p.drawText(i?'CONTENTS (continued)':'CONTENTS',{x:45,y:770,font:bold,size:20,color:blue});entries.slice(i*24,(i+1)*24).forEach((entry,j)=>{let title=clean(entry.title);while(font.widthOfTextAtSize(title,11)>440)title=title.slice(0,-4)+'...';p.drawText(title,{x:45,y:730-j*26,font,size:11,color:ink});p.drawText(String(entry.page),{x:530,y:730-j*26,font,size:11,color:ink})})});
 const all=pdf.getPages();for(const pg of generated){const n=all.indexOf(pg)+1;pg.drawLine({start:{x:45,y:44},end:{x:550,y:44},thickness:.5,color:rgb(.83,.87,.91)});pg.drawText(`Rev ${clean(d.revision).slice(0,40)} | ${manual.status}`,{x:45,y:28,font,size:8,color:muted});pg.drawText(`${n} / ${all.length}`,{x:505,y:28,font,size:8,color:muted})}pdf.setTitle(clean(`${d.projectName} - O&M Manual`));pdf.setSubject(clean(`${d.service} - Revision ${d.revision}`));return pdf.save();
}
