import {staffKey} from './calendar-model';
import {shiftDay,weekDays} from './timesheet-week';
export const payCategories=[{id:'ordinary',name:'Ordinary hours'},{id:'overtime-1.5',name:'Overtime · 1.5×'},{id:'overtime-2',name:'Overtime · 2×'}];
export type PayrollEmployee={id:string;name:string;aliases:string[]};
export type PayrollConfig={frequency:'weekly'|'fortnightly';anchor:string;employees:PayrollEmployee[]};
export function validPayrollDate(day:unknown):day is string{return typeof day==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(day)&&Number.isFinite(Date.parse(day))&&new Date(day).toISOString().slice(0,10)===day&&day>='2000-01-01'&&day<='2100-12-31'}
export function payrollToday(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Melbourne',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
export function defaultPayrollConfig():PayrollConfig{return {frequency:'weekly',anchor:weekDays(payrollToday())[0],employees:[]}}
export function periodFor(day:string,config:PayrollConfig){const length=config.frequency==='fortnightly'?14:7;const difference=Math.round((Date.parse(day)-Date.parse(config.anchor))/86400000);const start=shiftDay(config.anchor,Math.floor(difference/length)*length);return {start,end:shiftDay(start,length-1),length}}
export function validatePayrollConfig(input:any,old:PayrollConfig){if(!input||!['weekly','fortnightly'].includes(input.frequency)||!validPayrollDate(input.anchor))throw Error('Choose a pay frequency and valid period start date.');if(!Array.isArray(input.employees)||input.employees.length>500)throw Error('Use up to 500 employee profiles.');const ids=new Set<string>(),aliases=new Set<string>();const employees=input.employees.map((e:any)=>{if(typeof e.id!=='string'||!/^[a-z0-9-]{8,80}$/i.test(e.id)||ids.has(e.id)||typeof e.name!=='string'||!e.name.trim()||e.name.length>150||!Array.isArray(e.aliases)||e.aliases.length>20)throw Error('Enter a unique employee profile and name.');ids.add(e.id);const names=[...new Set([e.name,...e.aliases].map((x:any)=>{if(typeof x!=='string'||x.length>150)throw Error('Employee names must be under 150 characters.');return x.trim()}).filter(Boolean))];for(const name of new Set(names.map(staffKey))){if(aliases.has(name))throw Error(`The name “${name}” belongs to more than one employee. Use distinct names to avoid incorrect payroll.`);aliases.add(name)}return {id:e.id,name:e.name.trim(),aliases:names}});for(const e of old.employees)if(!ids.has(e.id))throw Error('Existing employee profiles must be retained to preserve links to time entries.');return {frequency:input.frequency,anchor:input.anchor,employees} as PayrollConfig}
export function resolveEmployee(data:any,config:PayrollConfig){return data.staffId?config.employees.find(e=>e.id===data.staffId):config.employees.find(e=>e.aliases.some(a=>staffKey(a)===staffKey(data.employee||'')))}
export function reviewLines(rows:any[],config:PayrollConfig,start:string,end:string){return rows.flatMap(r=>{const d=typeof r.data==='string'?JSON.parse(r.data):r.data;const date=validPayrollDate(d.date)?d.date:r.created.slice(0,10);if(date<start||date>end)return [];const employee=resolveEmployee(d,config),category=payCategories.find(c=>c.id===d.payCategory);const issues:string[]=[];if(!validPayrollDate(d.date))issues.push('Check date');if(!employee)issues.push('Match employee');if(!category)issues.push('Choose pay category');if(!Number.isFinite(Number(d.hours))||Number(d.hours)<=0||Number(d.hours)>24)issues.push('Check hours');return [{...r,data:d,date,employeeId:employee?.id||'',employee:employee?.name||d.employee||'Unassigned',payCategory:category?.id||'',payCategoryName:category?.name||'Not classified',hours:Number(d.hours)||0,issues}]})}
