'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {payCategories,type PayrollConfig} from './payroll-model';
import {staffKey} from './calendar-model';
export function PayrollSettings(){
const [data,setData]=useState<any>(null),[config,setConfig]=useState<PayrollConfig|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
async function load(){try{const r=await fetch('/api/payroll',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setConfig(d.config);setDirty(false);setError('')}catch(e:any){setError(e.message)}}
useEffect(()=>{load()},[]);
function change(next:PayrollConfig){setConfig(next);setDirty(true);setMessage('')}
function add(name=''){if(!config)return;change({...config,employees:[...config.employees,{id:crypto.randomUUID(),name,aliases:name?[name]:[]}]})}
async function save(){if(!config)return;setBusy(true);setError('');try{const r=await fetch('/api/payroll',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'configure',config,version:data.version})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage('Payroll setup saved. Existing approvals will need review if their setup has changed.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
return <div className="payroll-settings"><section className="panel payroll-connection"><div><div className="eyebrow">INTEGRATIONS</div><h2>Xero Payroll</h2><p>Prepare employee matching and pay-period reviews for Australian payroll.</p></div><span className="payroll-status">Not connected</span><Button disabled>Connect Xero</Button><p className="payroll-note">Connection setup is still required. Employee and earnings-rate matching will unlock after Xero authorisation. No payroll information is sent from this screen.</p></section>{error&&<div className="error" role="alert">{error}<Button variant="outline" onClick={load}>Reload</Button></div>}{message&&<p className="settings-notice" role="status">{message}</p>}{!config?<p>Loading payroll setup…</p>:<><fieldset className="project-permission-surface" disabled={busy}><section className="panel payroll-panel"><h3>Pay periods</h3><p>Use the start date of one real pay period. Reviews will follow that cycle, including earlier dates.</p><div className="two"><label className="field">Frequency<select value={config.frequency} onChange={e=>change({...config,frequency:e.target.value as any})}><option value="weekly">Weekly · 7 days</option><option value="fortnightly">Fortnightly · 14 days</option></select></label><label className="field">Known pay-period start<input type="date" value={config.anchor} onChange={e=>change({...config,anchor:e.target.value})}/></label></div></section>
<section className="panel payroll-panel"><div className="section-title"><div><h3>Employee matching</h3><p>Create one payroll profile per person. List any names used on older time entries under that same person.</p></div><Button variant="outline" onClick={()=>add()}>Add employee</Button></div>{data.candidates?.filter((name:string)=>!config.employees.some(e=>[e.name,...e.aliases].some(a=>staffKey(a)===staffKey(name)))).length>0&&<div className="payroll-candidates"><span>Names found in your workspace:</span>{data.candidates.filter((name:string)=>!config.employees.some(e=>[e.name,...e.aliases].some(a=>staffKey(a)===staffKey(name)))).map((name:string)=><Button key={name} size="sm" variant="outline" onClick={()=>add(name)}>Add {name}</Button>)}</div>}
<div className="table-wrap"><table><thead><tr><th>PLAN.FLO employee</th><th>Names used in time entries</th><th>Xero employee</th></tr></thead><tbody>{config.employees.map((employee,i)=><tr key={employee.id}><td><input aria-label={`Employee ${i+1} name`} value={employee.name} onChange={e=>change({...config,employees:config.employees.map((x,j)=>i===j?{...x,name:e.target.value}:x)})}/></td><td><input aria-label={`Other names for ${employee.name}`} value={employee.aliases.join(', ')} placeholder="Rob, Robert De Angelis" onChange={e=>change({...config,employees:config.employees.map((x,j)=>i===j?{...x,aliases:e.target.value.split(',').map(a=>a.trimStart())}:x)})}/></td><td><select disabled aria-label={`Xero match for ${employee.name}`}><option>Connect Xero to match</option></select>{!data.config.employees.some((x:any)=>x.id===employee.id)&&<Button size="sm" variant="outline" onClick={()=>change({...config,employees:config.employees.filter((_,j)=>j!==i)})}>Remove unsaved profile</Button>}</td></tr>)}</tbody></table></div>{!config.employees.length&&<p>No payroll profiles yet. Add your workers above.</p>}<p className="payroll-note">New time entries can select a permanent employee profile. Older entries match only the names you assign here. Different people must not share a matching name.</p></section>
<section className="panel payroll-panel"><h3>Pay categories</h3><p>Choose the category on each time entry. These labels do not calculate pay or determine overtime eligibility.</p><div className="table-wrap"><table><thead><tr><th>PLAN.FLO category</th><th>Xero earnings rate</th></tr></thead><tbody>{payCategories.map(c=><tr key={c.id}><td>{c.name}</td><td><select disabled aria-label={`Xero earnings rate for ${c.name}`}><option>Connect Xero to match</option></select></td></tr>)}</tbody></table></div><p className="payroll-note">Project work packages and hourly project costs remain separate. Entries without a pay category must be classified before approval.</p></section></fieldset><div className="modal-actions"><Button className="primary" disabled={busy||(!dirty&&data.version>0)} onClick={save}>{busy?'Saving…':'Save payroll setup'}</Button></div></>}
<section className="panel payroll-panel"><h3>Before live syncing</h3><ol><li>Register the PLAN.FLO integration with Xero and configure secure connection credentials.</li><li>Authorise your company, then match employees, earnings rates and the Xero pay calendar.</li><li>Test draft timesheets, corrections and duplicate protection before enabling Send to Xero.</li></ol><p className="payroll-note">Local approval is available in Time Sheets → Review payroll. It does not approve or run payroll in Xero.</p></section></div>
}
