'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {payCategories,payrollToday} from './payroll-model';
import {shiftDay} from './timesheet-week';
export function PayrollReview({headerActions}:{headerActions?:React.ReactNode}){
const [day,setDay]=useState(payrollToday()),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(false);
async function load(date=day){setLoading(true);setChecked(false);setError('');try{const r=await fetch('/api/payroll?date='+encodeURIComponent(date),{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e:any){setError(e.message);setData(null)}finally{setLoading(false)}}
useEffect(()=>{load(day)},[day]);
async function action(action:string){setBusy(true);setError('');try{const r=await fetch('/api/payroll',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,date:day,version:data.reviewVersion,fingerprint:data.fingerprint})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
async function classify(line:any,key:string,value:string){setBusy(true);setError('');try{const next={...line.data,staffId:line.data.staffId||line.employeeId,[key]:value};const r=await fetch('/api/workspace-register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:'time',id:line.id,projectId:line.projectId,version:line.data.version||0,data:next})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
return <div className="payroll-review"><div className="section-title module-heading time-register-heading"><div><h2>Payroll review</h2><p>Review hours across all projects for the full pay period. This approval stays in PLAN.FLO.</p></div><div className="time-register-actions">{headerActions}<Button variant="outline" disabled={busy||loading} onClick={()=>load()}>Refresh review</Button></div></div><div className="week-navigation"><div className="member-actions"><Button variant="outline" disabled={busy||loading||!data} onClick={()=>setDay(shiftDay(data.period.start,-data.period.length))}>Previous period</Button><strong>{data?`${data.period.start} — ${data.period.end}`:'Pay period'}</strong><Button variant="outline" disabled={busy||loading||!data} onClick={()=>setDay(shiftDay(data.period.start,data.period.length))}>Next period</Button><Button variant="outline" disabled={busy||loading} onClick={()=>{const today=payrollToday();if(today===day)load();else setDay(today)}}>Current period</Button></div><label>Jump to date<input type="date" value={day} disabled={busy||loading} onChange={e=>{if(e.target.value)setDay(e.target.value)}}/></label></div>{error&&<div className="error" role="alert">{error}</div>}{loading?<p>Loading pay-period review…</p>:data&&<><div className="contract-summary"><section className="panel"><span>Period hours</span><strong>{data.totalHours.toFixed(2)} h</strong><small>{data.lines.length} time entries · all projects</small></section><section className="panel"><span>Local approval</span><strong>{data.status}</strong>{data.approval&&<small>Last action by {data.approval.actor} · {new Date(data.approval.date).toLocaleString('en-AU')}</small>}</section><section className="panel"><span>Xero sync</span><strong>{data.syncStatus}</strong><small>Not connected · sending disabled</small></section></div>{!data.configVersion&&<p className="settings-notice">Save your pay cycle and employee profiles in Settings → Integrations → Xero first.</p>}{data.status==='Changed since approval'&&<p className="error">The entries or payroll setup have changed since approval. Review and approve this period again.</p>}{data.issues.length>0&&<details className="settings-notice" open><summary>{data.issues.length} checks to resolve</summary><ul>{data.issues.map((issue:string,i:number)=><li key={i}>{issue}</li>)}</ul></details>}
<div className="table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Project</th><th>Hours</th><th>Payroll employee</th><th>Pay category</th></tr></thead><tbody>{data.lines.map((line:any)=><tr key={line.id}><td>{line.data.employee}</td><td>{line.date}</td><td>{line.projectName}</td><td>{line.hours.toFixed(2)}</td><td><select aria-label={`Payroll employee for ${line.data.employee} on ${line.date}`} disabled={busy} value={line.employeeId} onChange={e=>classify(line,'staffId',e.target.value)}><option value="" disabled>Match employee</option>{data.config.employees.map((e:any)=><option key={e.id} value={e.id}>{e.name}</option>)}</select></td><td><select aria-label={`Pay category for ${line.employee} on ${line.date}`} disabled={busy} value={line.payCategory} onChange={e=>classify(line,'payCategory',e.target.value)}><option value="" disabled>Choose category</option>{payCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></td></tr>)}</tbody></table></div>{!data.lines.length&&<p className="settings-notice">No recorded hours in this pay period.</p>}
{data.status!=='Approved'&&<label className="payroll-confirm"><input type="checkbox" checked={checked} disabled={busy||!data.canApprove} onChange={e=>setChecked(e.target.checked)}/>I have checked the employees, dates, hours and pay categories for this period.</label>}<div className="member-actions">{data.status==='Approved'?<Button variant="outline" disabled={busy} onClick={()=>action('reopen')}>Reopen review</Button>:<Button className="primary" disabled={busy||!checked||!data.canApprove} onClick={()=>action('approve')}>{busy?'Saving…':'Approve hours in PLAN.FLO'}</Button>}<Button disabled title="Xero must be configured, matched and tested first">Send to Xero</Button></div><p className="payroll-note">Project cost rates are not payroll pay rates. Sending remains disabled until Xero is connected, employee and earnings-rate matching is complete, and the integration is tested.</p>{data.approval?.history?.length>0&&<details className="panel payroll-panel"><summary>Review history</summary>{[...data.approval.history].reverse().map((h:any,i:number)=><p key={i}>{h.action==='approve'?'Approved':'Reopened'} by {h.actor} · {new Date(h.date).toLocaleString('en-AU')}</p>)}</details>}</>}</div>
}
