'use client';
import {useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
export type Revision={id:string;number:number;label:string;note:string;name:string;mime:string;created:string};
export function PlanRevisions({plan,plans,editable,onChange,onSaved}:{plan:any;plans:any[];editable:boolean;onChange:(r:Revision|null)=>void;onSaved:()=>Promise<void>}){
 const [revisions,setRevisions]=useState<Revision[]>([]),[selected,setSelected]=useState(''),[upload,setUpload]=useState(false),[overlay,setOverlay]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=async()=>{const res=await fetch(`/api/plan-revisions?fileId=${plan.id}`);const data:any=await res.json();if(!res.ok)throw new Error(data.error);setRevisions(data.revisions);setSelected(data.latestId);onChange(data.revisions.find((r:Revision)=>r.id===data.latestId));};
 useEffect(()=>{let active=true;setRevisions([]);setSelected('');onChange(null);fetch(`/api/plan-revisions?fileId=${plan.id}`).then(async res=>{const d:any=await res.json();if(!res.ok)throw new Error(d.error);if(active){setRevisions(d.revisions);setSelected(d.latestId);onChange(d.revisions.find((r:Revision)=>r.id===d.latestId));}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[plan.id,plan.currentRevisionId]);
 const current=revisions.find(r=>r.id===selected);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);form.set('fileId',plan.id);setBusy(true);setError('');try{const res=await fetch('/api/plan-revisions',{method:'POST',body:form});const d:any=await res.json();if(!res.ok)throw new Error(d.error);await onSaved();await refresh();setUpload(false);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="revision-panel"><div className="revision-actions"><label>Drawing version <select aria-label="Drawing version" value={selected} onChange={e=>{setSelected(e.target.value);onChange(revisions.find(r=>r.id===e.target.value)||null)}}>{revisions.map((r,i)=><option key={r.id} value={r.id}>{r.label} · Version {r.number}{i===0?' · Latest':' · Previous'}</option>)}</select></label><span className={selected===revisions[0]?.id?'revision-latest':'revision-previous'}>{selected===revisions[0]?.id?'Latest version':'Previous version'}</span><Button variant="outline" disabled={!revisions.length} onClick={()=>setOverlay(true)}>Compare / overlay</Button>{editable&&!plan.archived&&<Button className="primary" onClick={()=>{setError('');setUpload(true)}}>Upload revision</Button>}</div>{current&&<p>{new Date(current.created).toLocaleDateString()} · {current.name}{current.note&&` — ${current.note}`} · <a href={`/api/file/${plan.id}?revision=${current.id}`} target="_blank" rel="noreferrer">Open this version</a></p>}{error&&!upload&&<p role="alert">{error}</p>}
 <Dialog open={upload} onOpenChange={v=>{if(!busy)setUpload(v)}}><DialogContent><DialogHeader><DialogTitle>Upload drawing revision</DialogTitle></DialogHeader><form className="revision-form" onSubmit={submit}><p>{plan.name} — previous versions will remain available.</p><label>Revision label<input name="label" required maxLength={60} placeholder="e.g. Rev B — For construction"/></label><label>Drawing file<input name="file" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" required/></label><label>Revision notes<textarea name="note" maxLength={2000} placeholder="What changed?"/></label>{error&&<p role="alert">{error}</p>}<Button type="submit" className="primary" disabled={busy}>{busy?'Uploading…':'Save revision'}</Button></form></DialogContent></Dialog>
 <Dialog open={overlay} onOpenChange={setOverlay}><DialogContent className="overlay-dialog"><DialogHeader><DialogTitle>Plan overlay</DialogTitle></DialogHeader>{overlay&&<PlanOverlay plan={plan} plans={plans} revisions={revisions}/>}</DialogContent></Dialog></div>
}
function Layer({url,mime,page,onPages,onError,style}:{url:string;mime:string;page:number;onPages:(n:number)=>void;onError:(s:string)=>void;style?:React.CSSProperties}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{let cancelled=false;let task:any,render:any,doc:any;const canvas=ref.current!;const ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,1400,1000);onError('');(async()=>{if(mime==='application/pdf'){const pdf=await import('pdfjs-dist');pdf.GlobalWorkerOptions.workerSrc=workerUrl;task=pdf.getDocument({url});doc=await task.promise;if(cancelled)return;onPages(doc.numPages);const p=await doc.getPage(Math.min(page,doc.numPages));const v=p.getViewport({scale:1});const viewport=p.getViewport({scale:Math.min(1400/v.width,1000/v.height)});const temp=document.createElement('canvas');temp.width=Math.ceil(viewport.width);temp.height=Math.ceil(viewport.height);render=p.render({canvas:temp,canvasContext:temp.getContext('2d')!,viewport});await render.promise;if(!cancelled)ctx.drawImage(temp,(1400-temp.width)/2,(1000-temp.height)/2);}else{onPages(1);const img=new Image();img.src=url;await img.decode();if(cancelled)return;const scale=Math.min(1400/img.width,1000/img.height);ctx.drawImage(img,(1400-img.width*scale)/2,(1000-img.height*scale)/2,img.width*scale,img.height*scale);}})().catch(e=>{if(!cancelled)onError('Unable to render this drawing. Try a supported PDF or image.');});return()=>{cancelled=true;render?.cancel();task?.destroy();};},[url,mime,page]);return <canvas width={1400} height={1000} ref={ref} style={style}/>}
function PlanOverlay({plan,plans,revisions}:{plan:any;plans:any[];revisions:Revision[]}){const options=[...revisions.map(r=>({key:r.id,url:`/api/file/${plan.id}?revision=${r.id}`,mime:r.mime,label:`${r.label} · Version ${r.number}`})),...plans.filter(p=>p.id!==plan.id&&!p.archived).map(p=>({key:p.id,url:`/api/file/${p.id}`,mime:p.mime,label:p.name+' · Latest'}))];const [base,setBase]=useState(options[0]?.key||''),[top,setTop]=useState(options[1]?.key||options[0]?.key||''),[opacity,setOpacity]=useState(50),[x,setX]=useState(0),[y,setY]=useState(0),[scale,setScale]=useState(100),[rotation,setRotation]=useState(0),[pageA,setPageA]=useState(1),[pageB,setPageB]=useState(1),[pagesA,setPagesA]=useState(1),[pagesB,setPagesB]=useState(1),[errorA,setErrorA]=useState(''),[errorB,setErrorB]=useState('');const a=options.find(o=>o.key===base)!,b=options.find(o=>o.key===top)!;function reset(){setX(0);setY(0);setScale(100);setRotation(0);setOpacity(50)}return <><p>Compare revisions or drawings. Adjust the top layer to align matching points. Alignment is manual; original files are unchanged.</p><div className="overlay-controls"><label>Base drawing<select value={base} onChange={e=>{setBase(e.target.value);setPageA(1)}}>{options.map(o=><option key={o.key} value={o.key}>{o.label}</option>)}</select></label><label>Top drawing<select value={top} onChange={e=>{setTop(e.target.value);setPageB(1);reset()}}>{options.map(o=><option key={o.key} value={o.key}>{o.label}</option>)}</select></label><label>Base page ({pagesA})<input type="number" min={1} max={pagesA} value={pageA} onChange={e=>setPageA(Math.max(1,Math.min(pagesA,+e.target.value)))}/></label><label>Top page ({pagesB})<input type="number" min={1} max={pagesB} value={pageB} onChange={e=>setPageB(Math.max(1,Math.min(pagesB,+e.target.value)))}/></label><label>Top opacity {opacity}%<input type="range" min={0} max={100} value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label>{[['Horizontal %',x,setX,-100,100],['Vertical %',y,setY,-100,100],['Scale %',scale,setScale,10,400],['Rotation °',rotation,setRotation,-180,180]].map(([label,value,set,min,max]:any)=><label key={label}>{label}<input type="number" step="0.1" min={min} max={max} value={value} onChange={e=>set(Math.max(min,Math.min(max,+e.target.value)))}/></label>)}<Button variant="outline" onClick={reset}>Reset alignment</Button></div>{base===top&&<p>Select a different top drawing to compare versions.</p>}{(errorA||errorB)&&<p role="alert">{errorA||errorB}</p>}<div className="overlay-stage"><Layer url={a.url} mime={a.mime} page={pageA} onPages={setPagesA} onError={setErrorA}/><Layer url={b.url} mime={b.mime} page={pageB} onPages={setPagesB} onError={setErrorB} style={{opacity:opacity/100,transform:`translate(${x}%,${y}%) scale(${scale/100}) rotate(${rotation}deg)`}}/></div></>}
