import {platformDb} from './platform-store';
import {subscriptionPlans} from './subscription-plans';
const day=(offset:number)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)};
export async function analytics(){
 const db=platformDb(),start=day(-29),previous=day(-59),end=day(1),week=day(-6),iso=(d:string)=>d+'T00:00:00.000Z';
 const all=async(sql:string,args:any[]=[])=> (await db.prepare(sql).bind(...args).all<any>()).results;
 const first=async(sql:string,args:any[]=[])=>await db.prepare(sql).bind(...args).first<any>();
 const [growth,trend,cohort,followup,usage,retention,actions,storage,tickets,resolutions,topics,outcomes,tracking]=await Promise.all([
 first(`SELECT COUNT(*) AS total,SUM(CASE WHEN created>=? AND created<? THEN 1 ELSE 0 END) AS newlyRecorded,SUM(CASE WHEN created>=? AND created<? THEN 1 ELSE 0 END) AS previousRecorded FROM platform_accounts`,[iso(start),iso(end),iso(previous),iso(start)]),
 all(`SELECT substr(created,1,10) AS day,COUNT(*) AS count FROM platform_accounts WHERE created>=? AND created<? GROUP BY substr(created,1,10) ORDER BY day`,[iso(start),iso(end)]),
 first(`SELECT COUNT(*) AS total,SUM(EXISTS(SELECT 1 FROM projects p WHERE p.owner=a.owner)) AS projects,SUM(EXISTS(SELECT 1 FROM files f WHERE f.owner=a.owner AND f.category='plans')) AS drawings,SUM(EXISTS(SELECT 1 FROM company_members m WHERE m.owner=a.owner AND m.user_id IS NOT NULL AND m.status='active')) AS teammates FROM platform_accounts a WHERE created>=? AND created<?`,[iso(start),iso(end)]),
 all(`SELECT a.owner,COALESCE(NULLIF(s.company,''),u.name,'Unnamed company') AS name,a.created,(SELECT MAX(day) FROM platform_usage pu WHERE pu.owner=a.owner) AS lastActivity,CASE WHEN NOT EXISTS(SELECT 1 FROM projects p WHERE p.owner=a.owner) THEN 'No project created' ELSE 'No recent activity' END AS reason FROM platform_accounts a LEFT JOIN settings s ON s.owner=a.owner LEFT JOIN platform_users u ON u.id=a.owner WHERE a.status='Active' AND ((a.created<? AND NOT EXISTS(SELECT 1 FROM projects p WHERE p.owner=a.owner)) OR ((SELECT MAX(day) FROM platform_usage pu WHERE pu.owner=a.owner)<?)) ORDER BY a.created LIMIT 50`,[iso(day(-7)),day(-14)]),
 first(`SELECT COUNT(DISTINCT owner) AS companies,COUNT(DISTINCT user_id) AS users,COUNT(DISTINCT CASE WHEN day>=? THEN owner END) AS weeklyCompanies,COUNT(DISTINCT CASE WHEN day>=? THEN user_id END) AS weeklyUsers,SUM(views) AS views FROM platform_usage WHERE day>=? AND day<?`,[week,week,start,end]),
 first(`SELECT COUNT(*) AS previousCompanies,SUM(EXISTS(SELECT 1 FROM platform_usage c WHERE c.owner=p.owner AND c.day>=? AND c.day<?)) AS returned FROM (SELECT DISTINCT owner FROM platform_usage WHERE day>=? AND day<?) p`,[start,end,previous,start]),
 all(`SELECT category,operation,COUNT(*) AS count FROM review_activity WHERE occurred>=? AND occurred<? AND operation='insert' GROUP BY category,operation`,[iso(start),iso(end)]),
 all(`SELECT f.owner,COALESCE(NULLIF(s.company,''),'Unnamed company') AS name,SUM(CASE WHEN f.category='plans' AND EXISTS(SELECT 1 FROM plan_revisions r WHERE r.file_id=f.id) THEN (SELECT COALESCE(SUM(size),0) FROM plan_revisions r WHERE r.file_id=f.id) ELSE f.size END) AS bytes,sub.plan,sub.requested_plan FROM files f LEFT JOIN settings s ON s.owner=f.owner LEFT JOIN subscriptions sub ON sub.owner=f.owner GROUP BY f.owner ORDER BY bytes DESC`),
 all(`SELECT f.status,f.type,f.impact,f.created,f.resolved_at,COALESCE(t.priority,CASE f.impact WHEN 'Blocking work' THEN 'Urgent' WHEN 'Slowing work' THEN 'High' ELSE 'Normal' END) AS priority,COALESCE(t.assignee,'') AS assignee FROM feedback f LEFT JOIN support_tickets t ON t.feedback_id=f.id WHERE f.status NOT IN ('Resolved','Closed') OR (f.created>=? AND f.created<?)`,[iso(start),iso(end)]),
 all(`SELECT (julianday(resolved_at)-julianday(created))*24 AS hours FROM feedback WHERE resolved_at>=? AND resolved_at<? AND status IN ('Resolved','Closed') AND resolved_at>=created ORDER BY hours`,[iso(start),iso(end)]),
 all(`SELECT t.topic,COUNT(*) AS count FROM support_tickets t JOIN feedback f ON f.id=t.feedback_id WHERE t.topic<>'' AND f.created>=? AND f.created<? GROUP BY t.topic ORDER BY count DESC LIMIT 8`,[iso(start),iso(end)]),
 first(`SELECT COUNT(*) AS attempts,SUM(CASE WHEN status>=400 THEN 1 ELSE 0 END) AS failed,SUM(CASE WHEN status>=500 THEN 1 ELSE 0 END) AS serverErrors,MIN(created) AS firstRecorded FROM upload_outcomes WHERE created>=? AND created<?`,[iso(start),iso(end)]),
 first(`SELECT (SELECT MIN(day) FROM platform_usage) AS usageStarted,(SELECT MIN(created) FROM platform_accounts) AS accountsStarted,(SELECT value FROM review_config WHERE key='tracking_started') AS actionsStarted`)
 ]);
 const adoption=await Promise.all([
 ['Drawings','drawings',['Drawings']],['Time sheets','time',['Time','Time Sheets']],['Site Docs','siteDocs',['Site Docs']],['Scheduling','schedule',['Schedule']],['Budgeting','budgeting',['Budget Overview','Costs']]
 ].map(async([name,module,sections]:any)=>{const result=await first(`SELECT COUNT(*) AS eligible,SUM(EXISTS(SELECT 1 FROM platform_usage v WHERE v.owner=p.owner AND v.day>=? AND v.day<? AND v.section IN (${sections.map(()=>'?').join(',')}))) AS used FROM (SELECT DISTINCT owner FROM platform_usage WHERE day>=? AND day<?) p LEFT JOIN app_settings s ON s.owner=p.owner WHERE COALESCE(json_extract(CASE WHEN json_valid(s.data) THEN s.data ELSE '{}' END,?),1)<>0`,[start,end,...sections,start,end,'$.modules.'+module]);return {name,eligible:Number(result.eligible||0),used:Number(result.used||0)}}));
 const approved=await first(`SELECT COUNT(DISTINCT source_id) AS count FROM review_activity WHERE category='record:variation' AND occurred>=? AND occurred<? AND operation IN ('insert','update') AND json_extract(after_data,'$.status')='Approved' AND COALESCE(json_extract(before_data,'$.status'),'')<>'Approved'`,[iso(start),iso(end)]);
 const open=tickets.filter(t=>!['Resolved','Closed'].includes(t.status));const ages=[0,0,0,0];for(const t of open){const age=(Date.now()-Date.parse(t.created))/86400000;ages[age<1?0:age<4?1:age<8?2:3]++}
 const received=tickets.filter(t=>t.created>=iso(start)&&t.created<iso(end));const counts:Record<string,number>={};for(const t of received)counts[t.type]=(counts[t.type]||0)+1;
 const n=resolutions.length,median=n?(n%2?resolutions[Math.floor(n/2)].hours:(resolutions[n/2-1].hours+resolutions[n/2].hours)/2):null;
 return {period:{start,end:day(0),previousStart:previous,previousEnd:day(-30),timezone:'UTC'},tracking,growth,trend,cohort,followup,usage,retention,adoption,actions,approvedVariations:approved.count,storage:storage.map(s=>{const plan=subscriptionPlans.find(p=>p.id===s.plan)||subscriptionPlans.find(p=>p.id===s.requested_plan);const limit=plan?plan.storage*1e9:null;return {owner:s.owner,name:s.name,bytes:s.bytes,plan:plan?.name||null,requested:!subscriptionPlans.some(p=>p.id===s.plan),limit,percent:limit?s.bytes/limit*100:null}}),support:{open:open.length,urgent:open.filter(t=>['High','Urgent'].includes(t.priority)).length,unassigned:open.filter(t=>!t.assignee).length,ages,received:counts,resolutionHours:median,resolutionCount:n,topics},uploads:outcomes,revenue:{connected:false}};
}
