import {env} from 'cloudflare:workers';
import {platformDb} from './platform-store';
import {requestedBilling,invoiceRow,subscriptionRow} from './platform-billing-model';
export function billingMode(){const key=(env as unknown as Record<string,string>).STRIPE_SECRET_KEY||'';return /^(sk|rk)_test_/.test(key)?'test':/^(sk|rk)_live_/.test(key)?'live':'not_connected'}
async function stripe(path:string){const key=(env as unknown as Record<string,string>).STRIPE_SECRET_KEY;const r=await fetch('https://api.stripe.com/v1/'+path,{headers:{Authorization:'Bearer '+key,'Stripe-Version':'2025-02-24.acacia'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('Stripe billing could not be loaded. Check the connection and try again.');return await r.json() as any;}
const owners=`WITH owners AS (SELECT owner FROM platform_accounts UNION SELECT owner FROM subscriptions UNION SELECT owner FROM billing_accounts UNION SELECT owner FROM settings)`;
export async function billingList(q:string,offset:number){const db=platformDb(),like='%'+q+'%';const [items,counts]=await Promise.all([db.prepare(owners+` SELECT o.owner,COALESCE(NULLIF(s.company,''),u.name,'Unnamed company') AS company,COALESCE(NULLIF(s.email,''),u.email,'') AS email,COALESCE(a.status,'Active') AS accountStatus,sub.plan,sub.status AS recordedStatus,sub.requested_plan,sub.requested_at,sub.requested_configuration,b.customer_id FROM owners o LEFT JOIN settings s ON s.owner=o.owner LEFT JOIN platform_users u ON u.id=o.owner LEFT JOIN platform_accounts a ON a.owner=o.owner LEFT JOIN subscriptions sub ON sub.owner=o.owner LEFT JOIN billing_accounts b ON b.owner=o.owner WHERE COALESCE(s.company,'') LIKE ? OR COALESCE(u.name,'') LIKE ? OR COALESCE(s.email,'') LIKE ? OR COALESCE(u.email,'') LIKE ? ORDER BY COALESCE(s.company,u.name,''),o.owner LIMIT 51 OFFSET ?`).bind(like,like,like,like,offset).all<any>(),db.prepare(owners+` SELECT (SELECT COUNT(*) FROM owners) AS accounts,(SELECT COUNT(*) FROM subscriptions WHERE requested_plan IS NOT NULL) AS selections,(SELECT COUNT(*) FROM billing_accounts) AS linked`).first()]);return {mode:billingMode(),counts,items:items.results.slice(0,50).map(r=>({...r,request:requestedBilling(r.requested_configuration),requested_configuration:undefined})),hasMore:items.results.length>50};}
export async function billingDetail(owner:string,status:string,after:string){const db=platformDb();const row=await db.prepare(owners+` SELECT o.owner,COALESCE(NULLIF(s.company,''),u.name,'Unnamed company') AS company,COALESCE(NULLIF(s.email,''),u.email,'') AS email,COALESCE(a.status,'Active') AS accountStatus,sub.plan,sub.status AS recordedStatus,sub.requested_plan,sub.requested_at,sub.requested_configuration,b.customer_id FROM owners o LEFT JOIN settings s ON s.owner=o.owner LEFT JOIN platform_users u ON u.id=o.owner LEFT JOIN platform_accounts a ON a.owner=o.owner LEFT JOIN subscriptions sub ON sub.owner=o.owner LEFT JOIN billing_accounts b ON b.owner=o.owner WHERE o.owner=?`).bind(owner).first<any>();if(!row)return null;const mode=billingMode(),common={...row,requested_configuration:undefined,request:requestedBilling(row.requested_configuration),mode,invoices:[],subscriptions:[],hasMore:false,next:null};if(mode==='not_connected'||!row.customer_id)return common;if(!/^cus_[A-Za-z0-9]+$/.test(row.customer_id))throw new Error('The stored Stripe customer link needs attention.');
const query=new URLSearchParams({customer:row.customer_id,limit:'25'});if(status!=='all')query.set('status',status);if(after)query.set('starting_after',after);
const [invoices,subscriptions]=await Promise.all([stripe('invoices?'+query),stripe('subscriptions?'+new URLSearchParams({customer:row.customer_id,status:'all',limit:'100'}))]);
// Only the server-stored customer mapping may select billing records.
const customerId=(v:any)=>typeof v==='string'?v:v?.id;
if([...invoices.data,...subscriptions.data].some(r=>customerId(r.customer)!==row.customer_id||r.livemode!==(mode==='live')))throw new Error('Stripe returned records that do not match this account or billing mode.');
return {...common,invoices:invoices.data.map(invoiceRow),subscriptions:subscriptions.data.map(subscriptionRow),hasMore:invoices.has_more,next:invoices.data.at(-1)?.id||null,subscriptionsHasMore:subscriptions.has_more,dashboardUrl:`https://dashboard.stripe.com/${mode==='test'?'test/':''}customers/${encodeURIComponent(row.customer_id)}`};}
