'use client';
import {ArrowRight,CalendarDays,Camera,ClipboardList,FileQuestion,Image as ImageIcon} from 'lucide-react';
type Project={setup:string;budgetHours:number};type RecordItem={kind:string;status:string;created:string;title:string;data:string};type FileItem={id:string;name:string;category:string;created:string};
function data(r:RecordItem){try{return JSON.parse(r.data)}catch{return {}}}
function format(s:string){if(!s)return 'Not set';const d=new Date(s+'T12:00:00');return Number.isNaN(d.getTime())?'Not set':d.toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})}
export function ProjectProgress({project,records,files,onGo}:{project:Project;records:RecordItem[];files:FileItem[];onGo:(s:string)=>void}){
 let setup:any={};try{setup=JSON.parse(project.setup||'{}')}catch{}
 const tasks=records.filter(r=>r.kind==='task'),complete=tasks.filter(r=>r.status==='Complete').length,rfis=records.filter(r=>r.kind==='rfi'&&r.status!=='Closed'),overdue=rfis.filter(r=>{const d=data(r);return d.due&&new Date(d.due+'T23:59:59').getTime()<Date.now()&&!['Draft','Responded','Closed'].includes(r.status)}),photos=files.filter(f=>f.category==='photos'),diary=records.filter(r=>r.kind==='diary').sort((a,b)=>b.created.localeCompare(a.created)),start=setup.startDate?new Date(setup.startDate+'T00:00:00').getTime():0,due=setup.dueDate?new Date(setup.dueDate+'T23:59:59').getTime():0,elapsed=start&&due>start?Math.min(100,Math.max(0,Math.round((Date.now()-start)/(due-start)*100))):null;
 return <section className="progress-section"><div className="progress-heading"><div><h2>Site progress</h2><p>Current stage and the records coming in from site.</p></div><button onClick={()=>onGo('Project Setup')}>Edit project setup <ArrowRight size={15}/></button></div><div className="progress-grid"><article className="progress-card stage-card"><span className="progress-label">PROJECT STAGE</span><strong className="stage-value">{setup.projectStatus||'Not set'}</strong><div className="progress-date-row"><span><CalendarDays size={15}/> Start: {format(setup.startDate)}</span><span>Due: {format(setup.dueDate)}</span></div>{elapsed!==null?<><div className="progress-track"><div style={{width:`${elapsed}%`}}/></div><small>{elapsed}% of scheduled time elapsed · based on dates, not work completed</small></>:<p className="progress-empty">Set start and due dates to see the job timeline.</p>}</article><article className="progress-card"><span className="progress-label">TASKS COMPLETED</span><strong className="progress-number">{tasks.length?`${complete} / ${tasks.length}`:'—'}</strong><div className="progress-track"><div style={{width:`${tasks.length?Math.round(complete/tasks.length*100):0}%`}}/></div><small>{tasks.length?`${Math.round(complete/tasks.length*100)}% of recorded tasks complete`:'No tasks added yet'}</small><button className="progress-link" onClick={()=>onGo('Tasks')}>View tasks <ArrowRight size={14}/></button></article><article className="progress-card"><span className="progress-label">RFIS AWAITING RESOLUTION</span><strong className="progress-number">{rfis.length}</strong><small>{overdue.length?`${overdue.length} overdue response${overdue.length===1?'':'s'}`:'No overdue responses'}</small><button className="progress-link" onClick={()=>onGo('RFIs')}>View RFI register <ArrowRight size={14}/></button></article><article className="progress-card"><span className="progress-label">SITE RECORDS</span><div className="progress-split"><div><Camera size={17}/><strong>{photos.length}</strong><small>progress photos</small></div><div><ClipboardList size={17}/><strong>{diary.length}</strong><small>diary entries</small></div></div><button className="progress-link" onClick={()=>onGo('Site Diary')}>View site diary <ArrowRight size={14}/></button></article></div>{photos.length>0&&<div className="recent-photos"><div><strong>Recent progress photos</strong><button onClick={()=>onGo('Photos')}>View all photos <ArrowRight size={14}/></button></div><div className="recent-photo-list">{photos.slice(0,4).map(f=><button key={f.id} onClick={()=>onGo('Photos')} title={f.name}><img src={`/api/file/${f.id}`} alt={f.name}/></button>)}</div></div>}{diary.length>0&&<div className="latest-site-update"><strong>Latest site diary · {format(data(diary[0]).date||diary[0].created.slice(0,10))}</strong><p>{data(diary[0]).work||'Work notes not entered.'}</p>{data(diary[0]).delays&&<small>Delay / issue: {data(diary[0]).delays}</small>}</div>}</section>
}
