'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
type Assignments={projects:{id:string;name:string;status:string}[];projectIds:string[];version:number};
export function ProjectAssignments({memberId,name,onChanged}:{memberId:string;name:string;onChanged:()=>Promise<void>}) {
  const [open,setOpen]=useState(false),[data,setData]=useState<Assignments|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function load(){setOpen(true);setBusy(true);setData(null);setError('');try{const r=await fetch('/api/project-members?memberId='+encodeURIComponent(memberId),{cache:'no-store'});const value=await r.json() as Assignments & {error?:string};if(!r.ok)throw new Error(value.error||'Could not load projects.');setData(value)}catch(e){setError(e instanceof Error?e.message:'Could not load projects.')}finally{setBusy(false)}}
  async function save(){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/project-members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({memberId,projectIds:data.projectIds,version:data.version})});const value=await r.json() as {error?:string};if(!r.ok)throw new Error(value.error||'Could not save projects.');await onChanged();setOpen(false)}catch(e){setError(e instanceof Error?e.message:'Could not save projects.')}finally{setBusy(false)}}
  return <><Button variant="outline" onClick={load}>Projects</Button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent><DialogHeader><DialogTitle>Projects for {name}</DialogTitle><DialogDescription>Team members can access only selected projects, using their tab permissions. Company administrators retain access to all company projects.</DialogDescription></DialogHeader>{error&&<p role="alert">{error}</p>}{busy&&!data?<p>Loading…</p>:data?<div style={{maxHeight:'50vh',overflowY:'auto'}}>{data.projects.map(p=><label key={p.id} style={{display:'flex',gap:8,padding:8}}><Checkbox disabled={busy} checked={data.projectIds.includes(p.id)} onCheckedChange={checked=>setData({...data,projectIds:checked===true?[...data.projectIds,p.id]:data.projectIds.filter(id=>id!==p.id)})}/>{p.name} · {p.status}</label>)}{!data.projects.length&&<p>No company projects yet.</p>}</div>:null}<Button disabled={busy||!data} onClick={save}>Save assignments</Button><Button variant="outline" disabled={busy} onClick={load}>Reload</Button></DialogContent></Dialog></>;
}
