'use client';
import {useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {projectStages} from './project-stages';
export function StageProgress({projectId,stages,editable,onChanged}:{projectId:string;stages:Record<string,boolean>;editable:boolean;onChanged:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const count=projectStages.filter(s=>stages[s.id]===true).length,percent=Math.round(count/projectStages.length*100);
 async function toggle(stage:string,complete:boolean){setBusy(true);setError('');try{const response=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'projectStage',projectId,stage,complete})});const result:any=await response.json();if(!response.ok)throw new Error(result.error||'Could not save progress.');await onChanged()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <article className="progress-card stage-checklist-card"><h3>Project progress</h3><div className="stage-progress-layout"><div className="stage-chart-column"><div className="stage-donut" role="img" aria-label={`${percent}% complete; ${count} of 9 stages completed`}><svg viewBox="0 0 120 120" aria-hidden="true">{projectStages.map((stage,i)=><circle key={stage.id} cx="60" cy="60" r="48" fill="none" stroke={stages[stage.id]?stage.colour:'#354556'} strokeWidth="15" pathLength="360" strokeDasharray="37 323" transform={`rotate(${i*40-90} 60 60)`}/>)}</svg><div><strong>{percent}%</strong><span>Complete</span></div></div><p>{count} of 9 stages complete</p><small>Each stage contributes equally.</small></div><div className="stage-checklist">{projectStages.map(stage=><label key={stage.id} className="stage-check-row"><Checkbox checked={stages[stage.id]===true} disabled={busy||!editable} onCheckedChange={v=>toggle(stage.id,v===true)} aria-label={`Complete ${stage.name}`}/><span className="stage-colour" style={{background:stage.colour}}/><span>{stage.name}</span><small>{stages[stage.id]?'Complete':'Not complete'}</small></label>)}</div></div><p className="stage-save-status" aria-live="polite">{busy?'Saving progress…':editable?'Tick a stage when it is complete. Changes save automatically.':'View-only progress. Ask your administrator for Overview edit access.'}</p>{error&&<p role="alert" className="error">{error}</p>}</article>
}
