'use client';
import {useState} from 'react';
import {Checkbox} from '@/components/ui/checkbox';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {projectStages,optionalStages,validateStages,type ProjectStage} from './project-stages';
export function StageProgress({projectId,stages,definitions,version,editable,onChanged}:{projectId:string;stages:Record<string,boolean>;definitions?:ProjectStage[];version:number;editable:boolean;onChanged:()=>Promise<void>}){
 const list=definitions||projectStages;
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[draft,setDraft]=useState<ProjectStage[]>([]),[editVersion,setEditVersion]=useState(0);
 const count=list.filter(s=>stages[s.id]===true).length,percent=list.length?Math.round(count/list.length*100):0,angle=list.length?360/list.length:360;
 async function save(body:any){setBusy(true);setError('');try{const response=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,projectId})});const result:any=await response.json();if(!response.ok)throw new Error(result.error||'Could not save progress.');await onChanged();return true}catch(e:any){setError(e.message);return false}finally{setBusy(false)}}
 function move(i:number,d:number){const next=[...draft];[next[i],next[i+d]]=[next[i+d],next[i]];setDraft(next)}
 return <article className="progress-card stage-checklist-card"><div className="stage-title-row"><h3>Project progress</h3>{editable&&<Button className="stage-edit-button" disabled={busy} onClick={()=>{setDraft(list.map(s=>({...s})));setEditVersion(version);setError('');setEditing(true)}}>Edit stages</Button>}</div><div className="stage-progress-layout"><div className="stage-chart-column"><div className="stage-donut" role="img" aria-label={`${percent}% complete; ${count} of ${list.length} stages completed`}><svg viewBox="0 0 120 120" aria-hidden="true">{!list.length&&<circle cx="60" cy="60" r="48" fill="none" stroke="var(--pf-track)" strokeWidth="15"/>}{list.map((stage,i)=><circle key={stage.id} cx="60" cy="60" r="48" fill="none" stroke={stages[stage.id]?stage.colour:'var(--pf-track)'} strokeWidth="15" pathLength="360" strokeDasharray={`${list.length===1?360:Math.max(1,angle-3)} ${360-(list.length===1?360:Math.max(1,angle-3))}`} transform={`rotate(${i*angle-90} 60 60)`}/>)}</svg><div><strong>{percent}%</strong><span>Complete</span></div></div><p>{count} of {list.length} stages complete</p><small>Each included stage contributes equally.</small></div><div className="stage-checklist">{list.length?list.map(stage=><label key={stage.id} className="stage-check-row"><Checkbox checked={stages[stage.id]===true} disabled={busy||!editable} onCheckedChange={v=>save({action:'projectStage',stage:stage.id,complete:v===true,version})} aria-label={`Complete ${stage.name}`}/><span className="stage-colour" style={{background:stage.colour}}/><span>{stage.name}</span><small>{stages[stage.id]?'Complete':'Not complete'}</small></label>):<p>No stages selected. Add stages for this project using Edit stages.</p>}</div></div><p className="stage-save-status" aria-live="polite">{busy?'Saving progress…':editable?'Tick a stage when it is complete. Changes save automatically.':'View-only progress. Ask your administrator for Overview edit access.'}</p>{error&&!editing&&<p role="alert" className="error">{error}</p>}
 <Dialog open={editing} onOpenChange={v=>{if(!busy)setEditing(v)}}><DialogContent className="stage-editor"><DialogHeader><DialogTitle>Edit project stages</DialogTitle><DialogDescription>Choose the stages for this project. Rename, reorder or remove stages, or add your own. Removing a stage changes the progress percentage.</DialogDescription></DialogHeader>{error&&<p className="error" role="alert">{error}</p>}<div className="stage-editor-list">{draft.map((s,i)=><div className="stage-editor-row" key={s.id}><input type="color" value={s.colour} aria-label={`Colour for ${s.name}`} disabled={busy} onChange={e=>setDraft(draft.map(x=>x.id===s.id?{...x,colour:e.target.value}:x))}/><input value={s.name} maxLength={100} aria-label={`Stage ${i+1} name`} disabled={busy} onChange={e=>setDraft(draft.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/><Button variant="outline" disabled={busy||i===0} aria-label={`Move ${s.name} up`} onClick={()=>move(i,-1)}>↑</Button><Button variant="outline" disabled={busy||i===draft.length-1} aria-label={`Move ${s.name} down`} onClick={()=>move(i,1)}>↓</Button><Button variant="outline" disabled={busy} aria-label={`Remove ${s.name}`} onClick={()=>setDraft(draft.filter(x=>x.id!==s.id))}>Remove</Button></div>)}</div><Button variant="outline" disabled={busy||draft.length>=40} onClick={()=>setDraft([...draft,{id:crypto.randomUUID(),name:'',colour:'#6386ff'}])}>+ Custom stage</Button><strong>Add a suggested stage</strong><div className="stage-suggestions">{[...projectStages,...optionalStages].filter(s=>!draft.some(d=>d.id===s.id)).map(s=><Button variant="outline" key={s.id} disabled={busy||draft.length>=40} onClick={()=>setDraft([...draft,{...s}])}>+ {s.name}</Button>)}</div><small>Existing completion ticks stay with their stage when renamed or reordered. Changes apply only to this project.</small><div className="modal-actions"><Button variant="outline" disabled={busy} onClick={()=>setEditing(false)}>Cancel</Button><Button className="primary" disabled={busy} onClick={async()=>{if(!validateStages(draft)){setError('Give each stage a unique name, up to 100 characters.');return}if(await save({action:'projectStages',stages:draft,version:editVersion}))setEditing(false)}}>{busy?'Saving…':'Save stages'}</Button></div></DialogContent></Dialog></article>
}
