'use client';
import {useState,type ReactNode} from 'react';
import {DashboardHome} from './dashboard-home';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {ArrowRight,FolderOpen,Plus} from 'lucide-react';
import {projectStatuses} from './project-statuses';
export function WorkspaceHome({userName,view,projects,search,setSearch,filter,setFilter,onOpen,onNew,onProjects,admin,showCosts,showHours,reminders}:{userName:string;view:string;projects:any[];search:string;setSearch:(s:string)=>void;filter:string;setFilter:(s:string)=>void;onOpen:(id:string)=>void;onNew:()=>void;onProjects:()=>void;admin:boolean;showCosts:boolean;showHours:boolean;reminders?:ReactNode}){
 const [builderFilter,setBuilderFilter]=useState('All');const builderOptions=Array.from(new Map(projects.filter(p=>p.builderId).map(p=>[p.builderId,{id:p.builderId,name:p.builder,colour:p.builderColour}])).values());
 const dashboard=view==='Dashboard';const sorted=[...projects].sort((a,b)=>(b.lastActivity||b.created).localeCompare(a.lastActivity||a.created)||a.name.localeCompare(b.name));const matches=(p:any)=>`${p.name} ${p.builder} ${p.client} ${p.number}`.toLowerCase().includes(search.toLowerCase())&&(dashboard||builderFilter==='All'||(builderFilter==='unlinked'?!p.builderId:p.builderId===builderFilter));const rows=dashboard?sorted.filter(p=>['Active','On hold'].includes(p.status)&&matches(p)).slice(0,3):sorted.filter(p=>(filter==='All'||p.status===filter)&&matches(p));const stamp=(p:any)=>new Date(p.lastActivity||p.created).toLocaleString('en-AU',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
 if(dashboard)return <DashboardHome userName={userName} projects={projects} search={search} admin={admin} showCosts={showCosts} showHours={showHours} onOpen={onOpen} onNew={onNew} onProjects={onProjects} reminders={reminders}/>;
 return <>
 <div className="page-heading"><div><div className="eyebrow">PLAN.FLO / WORKSPACE</div><h1>Projects</h1><p>Every job, from first drawing to final handover.</p></div>{admin&&<Button className="primary" onClick={onNew}><Plus size={18}/> New project</Button>}</div>
 <div className="section-title"><div><h2>All projects</h2><span>{`${rows.length} shown · ${projects.length} total`}</span></div><label className="workspace-project-search"><span className="sr-only">Search projects</span><input placeholder="Search name, builder or reference" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 <div className="workspace-project-filters"><Select value={builderFilter} onValueChange={setBuilderFilter}><SelectTrigger aria-label="Filter projects by builder"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="All">All builders</SelectItem><SelectItem value="unlinked">Unlinked builders</SelectItem>{builderOptions.map(b=><SelectItem key={b.id} value={b.id}><span className="builder-dot" style={{background:b.colour}}/>{b.name}</SelectItem>)}</SelectContent></Select><Tabs value={filter} onValueChange={setFilter}><TabsList className="workspace-status-tabs">{[...projectStatuses,'All'].map(s=><TabsTrigger key={s} value={s}>{s} <small>{s==='All'?projects.length:projects.filter(p=>p.status===s).length}</small></TabsTrigger>)}</TabsList></Tabs></div>
 {!rows.length?<div className="empty-hero"><FolderOpen size={28}/><h2>{projects.length?'No projects in this view':'Create your first project'}</h2><p>{projects.length?'Change the search or open the full project list.':'Add a job to start managing its plans, tasks and documents.'}</p></div>:<div className="om-table-wrap"><table className="om-table"><thead><tr><th>Project</th><th>Builder</th><th>Status</th><th>Last activity</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td style={{borderLeft:'4px solid '+(p.builderColour||'transparent')}}><button className="om-link" onClick={()=>onOpen(p.id)}>{p.name}</button><small>{p.number||'No reference'}</small></td><td><span className="builder-project-badge"><i style={{background:p.builderColour||'var(--muted-foreground)'}}/>{p.builder||'Not set'}</span></td><td><span className={'status '+(p.status==='Active'?'':p.status==='On hold'?'on-hold':'muted')}>{p.status}</span></td><td>{stamp(p)}</td><td><Button variant="outline" onClick={()=>onOpen(p.id)}>Open <ArrowRight size={15}/></Button></td></tr>)}</tbody></table></div>}</>;
}
