'use client';
import {useEffect,useState} from 'react';
import {ChevronLeft,ChevronRight,Plus,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {localDateKey,staffColour} from './calendar-model';
import {weekDays,shiftDay,workerRows,timeEntryDay} from './timesheet-week';
import {PayrollReview} from './payroll-review';
import {payCategories} from './payroll-model';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {TimesheetGrid} from './timesheet-grid';
const money=(v:number)=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(v);
export function WorkspaceRegister({kind,editable,onOpenProject,projectId}:{projectId?:string;kind:'time'|'purchase-order';editable:boolean;onOpenProject:(id:string,tab:string)=>void}){
const [dailyHours,setDailyHours]=useState(7.6),[showCosts,setShowCosts]=useState(false);
const time=kind==='time',title=time?'Time Sheets':'Purchase Orders';
const [payrollView,setPayrollView]=useState(false),[payrollAdmin,setPayrollAdmin]=useState(false),[payrollEmployees,setPayrollEmployees]=useState<any[]>([]);
const [today,setToday]=useState(localDateKey()),[chosenWeek,setChosenWeek]=useState<string|null>(null),[staff,setStaff]=useState<string[]>([]);
const days=weekDays(chosenWeek||today);
const [colours,setColours]=useState<Record<string,string>>({});
const [rows,setRows]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[project,setProject]=useState(''),[search,setSearch]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[status,setStatus]=useState(''),[draft,setDraft]=useState<any>(null),[saving,setSaving]=useState(false);
async function load(quiet=false){if(!quiet)setLoading(true);try{const r=await fetch('/api/workspace-register?kind='+kind,{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setRows(d.rows);setDailyHours(d.dailyHours||7.6);setShowCosts(d.showCosts===true);setPayrollAdmin(d.payrollAdmin===true);setPayrollEmployees(d.payrollEmployees||[]);setStaff(d.staff||[]);setColours(d.colours||{});setProjects(d.projects);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{load();const refresh=()=>{setToday(localDateKey());if(document.visibilityState==='visible')load(true)};const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[kind]);
const visible=rows.filter(r=>(!(projectId||project)||r.projectId===(projectId||project))&&(!status||r.status===status)&&(time?(timeEntryDay(r)>=days[0]&&timeEntryDay(r)<=days[6]):(!from||timeEntryDay(r)>=from)&&(!to||timeEntryDay(r)<=to))&&(!search||[r.projectName,r.data.employee,r.data.supplier,r.data.number,r.data.package].join(' ').toLowerCase().includes(search.toLowerCase())));
const workers=workerRows(rows,staff).filter(w=>!search||w.name.toLowerCase().includes(search.toLowerCase())||visible.some(r=>(r.data.employee||'Unassigned').trim().toLowerCase()===w.key));
const hours=visible.reduce((s,r)=>s+Number(r.data.hours||0),0),total=visible.reduce((s,r)=>s+(time?Math.round(Number(r.data.hours)*Number(r.data.rate||0)*100)/100:Number(r.data.amount||0)),0);
const selectedProject=projects.find(p=>p.id===(projectId||project));
const draftNumber=draft?.id?draft.data.number:projects.find(p=>p.id===draft?.projectId)?.purchaseOrderNumber||'';
function edit(r?:any){setError('');setDraft(r?{...r,data:{...r.data,items:r.data.items?.map((i:any)=>({...i}))}}:{projectId:projectId||project||projects.find(p=>p.status==='Active')?.id||projects[0]?.id||'',status:'Draft',data:{date:time?(days.includes(today)?today:days[0]):localDateKey(),employee:'',hours:String(dailyHours),rate:'0',package:'General',notes:'',supplier:'',requiredBy:'',deliveryAddress:'',items:[{description:'',quantity:1,rate:0}]}})}
function field(k:string,v:any){setDraft((d:any)=>({...d,data:{...d.data,[k]:v}}))}
async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch('/api/workspace-register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...draft,data:{...draft.data,...(!time&&!draft.id?{number:draftNumber}:{})},kind,version:draft.data.version||0})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setDraft(null);await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
function csv(){const table=time?[['Date','Project','Staff','Work package','Hours',...(showCosts?['Hourly cost','Labour cost']:[])],...visible.map(r=>[r.data.date,r.projectName,r.data.employee,r.data.package,r.data.hours,...(showCosts?[r.data.rate,Math.round(r.data.hours*r.data.rate*100)/100]:[])])]:[['Order','Date','Project','Supplier','Status','Amount ex GST'],...visible.map(r=>[r.data.number,r.data.date,r.projectName,r.data.supplier,r.status,r.data.amount])];const text=table.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=time?'time-sheets.csv':'purchase-orders.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const viewSwitch=time&&payrollAdmin?<Tabs className="time-view-switch" value={payrollView?'payroll':'timesheets'} onValueChange={v=>setPayrollView(v==='payroll')}><TabsList aria-label="Time sheet view"><TabsTrigger value="timesheets">Weekly time sheets</TabsTrigger><TabsTrigger value="payroll">Review payroll</TabsTrigger></TabsList></Tabs>:null;
return <div className="workspace-register">{time&&payrollView&&payrollAdmin?<PayrollReview headerActions={viewSwitch}/>:<>
<div className={time?"page-heading time-register-heading":"page-heading"}><div><div className="eyebrow">{projectId?'PROJECT MANAGEMENT':'WORKSPACE'}</div><h1>{title}</h1><p>{time?'Monday to Sunday, every worker and every project. Browse past weeks to check recorded hours.':(projectId?'Create and track supplier orders for this project.':'Create and track supplier orders against your projects.')}</p></div><div className="time-register-actions">{viewSwitch}<div className="member-actions"><Button variant="outline" disabled={!visible.length} onClick={csv}><Download size={16}/>Export CSV</Button>{editable&&<Button className="primary" disabled={loading||!projects.length} onClick={()=>edit()}><Plus size={16}/>{time?'Log time':'New purchase order'}</Button>}</div></div></div>{error&&<div className="error" role="alert">{error}<Button variant="outline" onClick={()=>load()}>Refresh</Button></div>}
{!time&&!loading&&<div className="settings-notice"><strong>{selectedProject?.purchaseOrderNumber?'Project PO number: '+selectedProject.purchaseOrderNumber:'Generate a purchase order number first'}</strong><p>{selectedProject?.purchaseOrderNumber?'New purchase orders use this number from Project Setup.':'A purchase order number must be generated and saved in Project Setup before you can create an order.'}</p>{selectedProject&&<Button variant="outline" onClick={()=>onOpenProject(selectedProject.id,'Project Setup')}>Open Project Setup</Button>}</div>}
<div className="register-filters">{!projectId&&<label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option value="">All projects</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}<label>{time?'Staff or work package':'Supplier or order'}<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search…"/></label>{!time&&<><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}{!time&&<label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['Draft','Issued','Received','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></label>}<Button variant="outline" onClick={()=>{setProject('');setSearch('');setFrom('');setTo('');setStatus('')}}>Clear</Button></div>
{time&&<div className="week-navigation"><div className="member-actions"><Button variant="outline" aria-label="Previous week" onClick={()=>setChosenWeek(shiftDay(days[0],-7))}><ChevronLeft size={18}/></Button><strong>{new Date(days[0]+'T12:00:00Z').toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})} – {new Date(days[6]+'T12:00:00Z').toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}</strong><Button variant="outline" aria-label="Next week" onClick={()=>setChosenWeek(shiftDay(days[0],7))}><ChevronRight size={18}/></Button><Button variant="outline" onClick={()=>{setToday(localDateKey());setChosenWeek(null)}}>This week</Button></div><label>Jump to week<input type="date" aria-label="Choose any date in the week" value={days[0]} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value))setChosenWeek(e.target.value)}}/></label></div>}
<div className="contract-summary"><section className="panel"><span>{time?'Entries':'Orders'} shown</span><strong>{visible.length}</strong></section><section className="panel"><span>{time?'Total hours':'Order value · ex GST'}</span><strong>{time?hours.toFixed(2)+' h':money(total)}</strong><small>{time?'Based on the selected filters':'Includes all shown statuses'}</small></section>{(!time||showCosts)&&<section className="panel"><span>{time?'Labour cost':'Open orders · ex GST'}</span><strong>{money(time?total:visible.filter(r=>r.status==='Issued').reduce((s,r)=>s+Number(r.data.amount||0),0))}</strong><small>{time?'Hours × hourly cost':'Issued and awaiting receipt'}</small></section>}</div>
{!time&&<p className="settings-notice">Purchase orders track ordered work and materials. They do not add to actual costs automatically; record the supplier invoice under the project’s Costs section. Marking an order Issued does not send an email.</p>}
{loading?<p>Loading {title.toLowerCase()}…</p>:time?<TimesheetGrid rows={visible} workers={workers} days={days} today={today} colours={colours} onEdit={edit}/>:!visible.length?<section className="panel"><h2>{rows.length?'No matching records':'No '+title.toLowerCase()+' yet'}</h2><p>{projects.length?'Use the button above to add your first entry or adjust your filters.':'Create a project first to start recording entries.'}</p></section>:<div className="table-wrap"><table><thead><tr><th>Date</th><th>Project</th><th>{time?'Staff':'Order / supplier'}</th><th>{time?'Work package':'Status'}</th><th>{time?'Hours':'Value ex GST'}</th><th>{time?'Labour cost':'Required by'}</th><th></th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.data.date||r.created.slice(0,10)}</td><td><button className="budget-link" onClick={()=>onOpenProject(r.projectId,time?'Time':'Overview')}>{r.projectName}</button></td><td>{time?<span><i className="staff-dot" style={{background:staffColour(r.data.employee||'',colours)}}/>{r.data.employee}</span>:<><strong>{r.data.number}</strong><small className="member-email">{r.data.supplier}</small></>}</td><td>{time?r.data.package:r.status}</td><td>{time?Number(r.data.hours).toFixed(2):money(r.data.amount)}</td><td>{time?money(Math.round(r.data.hours*r.data.rate*100)/100):r.data.requiredBy||'—'}</td><td><Button variant="outline" onClick={()=>edit(r)}>{editable?'Edit':'View'}</Button></td></tr>)}</tbody></table></div>}
</>}<Dialog open={!!draft} onOpenChange={v=>{if(!v&&!saving)setDraft(null)}}><DialogContent className="register-dialog"><DialogHeader><DialogTitle>{time?'Time entry':draftNumber||'New purchase order'}</DialogTitle><DialogDescription>{time?'Save staff hours to the selected project.':'Item prices exclude GST. Orders remain available in this workspace register.'}</DialogDescription></DialogHeader>{draft&&<form onSubmit={save} className="form-grid">{error&&<p className="error" role="alert">{error}</p>}<fieldset disabled={saving||!editable} className="project-permission-surface"><label className="field">Project<select required disabled={!!draft.id||!!projectId} value={draft.projectId} onChange={e=>setDraft({...draft,projectId:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{!time&&<><label className="field">Purchase order number<input readOnly value={draftNumber} placeholder="Generate in Project Setup"/></label>{!draft.id&&<p className="settings-notice">{draftNumber?'This number comes from Project Setup and will be saved with this order.':'Generate and save a purchase order number in Project Setup before creating this order.'}{draft.projectId&&<Button type="button" variant="outline" onClick={()=>{setDraft(null);onOpenProject(draft.projectId,'Project Setup')}}>Open Project Setup</Button>}</p>}</>}<div className="two"><label className="field">Date<input type="date" required value={draft.data.date} onChange={e=>field('date',e.target.value)}/></label><label className="field">{time?'Staff name':'Supplier'}<input required disabled={time&&!!draft.data.staffId} maxLength={300} value={time?draft.data.employee:draft.data.supplier} onChange={e=>field(time?'employee':'supplier',e.target.value)}/></label></div>
{time?<><div className="two"><label className="field">Payroll employee<select value={draft.data.staffId||''} onChange={e=>{const selected=payrollEmployees.find(p=>p.id===e.target.value);setDraft({...draft,data:{...draft.data,staffId:e.target.value,...(selected?{employee:selected.name}:{})}})}}><option value="">Not linked · use staff name</option>{payrollEmployees.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">Pay category<select value={draft.data.payCategory||''} onChange={e=>field('payCategory',e.target.value)}><option value="">Not classified</option>{payCategories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="two"><label className="field">Hours<input required type="number" min="0.01" max="24" step="0.01" value={draft.data.hours} onChange={e=>field('hours',e.target.value)}/></label>{showCosts&&<label className="field">Hourly cost ($)<input required type="number" min="0" max="100000" step="0.01" value={draft.data.rate} onChange={e=>field('rate',e.target.value)}/></label>}</div><label className="field">Work package<input value={draft.data.package} onChange={e=>field('package',e.target.value)}/></label></>:<><div className="two"><label className="field">Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{['Draft','Issued','Received','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Required by<input type="date" value={draft.data.requiredBy} onChange={e=>field('requiredBy',e.target.value)}/></label></div><label className="field">Delivery address<input value={draft.data.deliveryAddress} onChange={e=>field('deliveryAddress',e.target.value)}/></label><h3>Order items</h3>{draft.data.items.map((item:any,i:number)=><div key={i} className="order-line">{['description','quantity','rate'].map(k=><label key={k}>{k==='rate'?'Unit price ($)':k==='quantity'?'Quantity':'Description'}<input required type={k==='description'?'text':'number'} min={k==='quantity'?'0.01':'0'} step="any" value={item[k]} onChange={e=>field('items',draft.data.items.map((x:any,j:number)=>j===i?{...x,[k]:e.target.value}:x))}/></label>)}<Button type="button" variant="outline" disabled={draft.data.items.length===1} onClick={()=>field('items',draft.data.items.filter((_:any,j:number)=>j!==i))}>Remove</Button></div>)}<Button type="button" variant="outline" onClick={()=>field('items',[...draft.data.items,{description:'',quantity:1,rate:0}])}>Add item</Button><p><strong>Total ex GST: {money(draft.data.items.reduce((s:number,i:any)=>s+Math.round(Number(i.quantity||0)*Number(i.rate||0)*100)/100,0))}</strong></p></>}
<label className="field">Notes<textarea rows={3} value={draft.data.notes} onChange={e=>field('notes',e.target.value)}/></label></fieldset><div className="modal-actions"><Button type="button" variant="outline" disabled={saving} onClick={()=>setDraft(null)}>Close</Button>{editable&&<Button className="primary" disabled={saving||(!time&&!draft.id&&!draftNumber)} type="submit">{saving?'Saving…':'Save'}</Button>}</div></form>}</DialogContent></Dialog></div>
}
