'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {IntegrationSetup} from './integration-setup';
import {payCategories} from './payroll-model';
export function XeroIntegration(){
 const [data,setData]=useState<any>(null),[mapping,setMapping]=useState<any>({}),[tenant,setTenant]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){const r=await fetch('/api/xero',{cache:'no-store'}),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setMapping(d.mapping||{});setTenant(d.tenantId||'')}
 useEffect(()=>{const refresh=()=>{load().catch(e=>setError(e.message))};refresh();window.addEventListener('payroll-config-updated',refresh);const result=new URLSearchParams(window.location.search).get('xero');if(result)setMessage(result==='authorised'?'Xero authorised. Choose the organisation to link to this company.':result==='cancelled'?'Xero authorisation was cancelled. You can try again.':'Xero could not be linked. Check setup and try again.');return()=>window.removeEventListener('payroll-config-updated',refresh)},[]);
 async function action(action:string,extra:any={}){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/xero',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,version:data?.version,...extra})}),d:any=await r.json();if(!r.ok)throw Error(d.error);if(d.url){window.location.assign(d.url);return}await load();setMessage(d.message||(action==='select'?'Organisation linked. Load matching options to continue.':action==='refresh'?'Xero matching options loaded.':'Xero settings saved.'));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const choices=(items:any[],selected:string)=>[<option key="empty" value="">Choose a match</option>,...(selected&&!items.some(e=>e.id===selected)?[<option key="missing" value={selected}>Previous match unavailable — choose again</option>]:[]),...items.map(e=><option key={e.id} value={e.id}>{e.name}</option>)];
 return <section className="panel xero-integration"><div className="section-title"><div><div className="eyebrow">INTEGRATIONS</div><h2>Xero Payroll</h2><p>Link your organisation and match employees and earnings rates.</p></div><span className="payroll-status">{data?.connected?'Connected':data?.authorised?'Choose organisation':data?.setup?.ready?'Ready to connect':'Setup required'}</span></div><div className="member-actions">{data?.setup?.ready&&!data?.authorised&&<Button disabled={busy} onClick={()=>action('connect')}>Connect Xero</Button>}<IntegrationSetup provider="Xero" setup={data?.setup} onRefresh={load} onConnect={()=>action('connect')} busy={busy}/>{data?.authorised&&<><Button variant="outline" disabled={busy} onClick={()=>action('connect')}>Reconnect Xero</Button><Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Disconnect Xero from this PLAN.FLO company? Local payroll reviews will remain.'))action('disconnect')}}>Disconnect Xero</Button></>}</div>
 {data?.authorised&&<div className="integration-organisation"><label className="field">Xero organisation<select aria-label="Xero organisation" value={tenant} onChange={e=>setTenant(e.target.value)} disabled={busy}><option value="">Choose the organisation for this company</option>{data.choices.map((c:any)=><option key={c.tenantId} value={c.tenantId}>{c.name}</option>)}</select></label><Button disabled={busy||!tenant||tenant===data.tenantId} onClick={()=>{if(!data.tenantId||window.confirm('Change the linked organisation? Existing Xero matches will be cleared.'))action('select',{tenantId:tenant})}}>Link organisation</Button></div>}
 {data?.connected&&<><p><strong>{data.tenantName}</strong></p><Button variant="outline" disabled={busy} onClick={()=>action('refresh')}>{busy?'Working…':'Load matching options'}</Button>{data.catalog?.updated&&<fieldset disabled={busy} className="integration-matching"><legend>Xero matching</legend>{data.profiles.length===0&&<p>Save employee profiles below, then return here to match them.</p>}{data.profiles.map((e:any)=><label className="field" key={e.id}>{e.name}<select aria-label={`Xero employee for ${e.name}`} value={mapping.employees?.[e.id]||''} onChange={v=>setMapping({...mapping,employees:{...mapping.employees,[e.id]:v.target.value}})}>{choices(data.catalog.employees||[],mapping.employees?.[e.id]||'')}</select></label>)}{payCategories.map(c=><label className="field" key={c.id}>{c.name}<select aria-label={`Xero earnings rate for ${c.name}`} value={mapping.rates?.[c.id]||''} onChange={v=>setMapping({...mapping,rates:{...mapping.rates,[c.id]:v.target.value}})}>{choices(data.catalog.rates||[],mapping.rates?.[c.id]||'')}</select></label>)}<label className="field">Pay calendar<select aria-label="Xero pay calendar" value={mapping.calendar||''} onChange={e=>setMapping({...mapping,calendar:e.target.value})}>{choices(data.catalog.calendars||[],mapping.calendar||'')}</select></label><Button onClick={()=>action('mapping',{mapping})}>Save Xero matching</Button></fieldset>}</>}
 <p className="payroll-note">Account linking and matching use read-only Xero access. Sending timesheets and running payroll are not enabled.</p>{error&&<div className="error" role="alert">{error}<Button variant="outline" disabled={busy} onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>Retry</Button></div>}{message&&<p role="status">{message}</p>}</section>
}
