import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {platformDb,operatorEmails} from '@/app/platform-store';
import {operatorRole,allOperatorEmails,logAdmin,type OperatorRole} from '@/app/operator-access';
import {cleanText,validEmail} from '@/app/platform-model';
import {categories,canSales,taskStates,priorities,leadStages,melbourneTime} from '@/app/staff-work-model';
import {validDay,melbourneDay,dayBounds} from '@/app/daily-review-model';
const json=(v:unknown,status=200)=>NextResponse.json(v,{status,headers:{'Cache-Control':'private, no-store'}});
async function context(){const user=await getChatGPTUser(),role=user?await operatorRole(user):null;return user&&role?{user,role,db:platformDb()}:null}
async function team(){return operatorEmails().map(email=>({email,role:'owner'}))}
const offsetFor=(value:string|null)=>{const n=Number(value||0);return Number.isSafeInteger(n)&&n>=0&&n<=100000?n:null};
async function eligible(email:string,category:string){return !email||(await team()).some(u=>u.email===email&&categories(u.role as OperatorRole).includes(category))}
async function generated(item:any){const db=platformDb(),now=new Date().toISOString();return db.prepare("INSERT INTO staff_tasks(id,title,details,category,status,priority,assignee,due,company_owner,source_type,source_id,source_key,fingerprint,source_state,created,updated) SELECT ?,?,?,?,'Review',?,?,?,?,?,?,?,?,?,?,? WHERE (?='' OR NOT EXISTS(SELECT 1 FROM deletion_requests WHERE owner=? AND status IN ('Purging','Purged'))) ON CONFLICT(source_key) DO UPDATE SET title=excluded.title,details=excluded.details,fingerprint=excluded.fingerprint,source_state=excluded.source_state,status=CASE WHEN staff_tasks.status IN ('Done','Dismissed') THEN 'Review' ELSE staff_tasks.status END,version=staff_tasks.version+1,updated=excluded.updated WHERE staff_tasks.fingerprint<>excluded.fingerprint").bind(crypto.randomUUID(),item.title,item.details,item.category,item.priority||'Normal',item.assignee||'',item.due||'',item.owner||'',item.type,item.id,item.type+':'+item.id,String(item.fingerprint),item.state||'',now,now,item.owner||'',item.owner||'')}
async function leadTask(l:any){return generated({title:'Follow up · '+l.name,details:`${l.company||'Company not recorded'} · ${l.email||'No email'}\nStage: ${l.stage}. Review the enquiry and agree the next step.`,category:'Leads',type:'lead',id:l.id,fingerprint:l.version,state:l.stage,assignee:l.assignee,due:l.follow_up})}
async function demoTask(d:any){return generated({title:'Demo follow-up · '+d.title,details:`${d.status} · ${new Date(d.start).toLocaleString('en-AU',{timeZone:'Australia/Melbourne'})} Melbourne time.\nCheck preparation, confirm arrangements separately, and record the next step. This diary entry is not synced to Google Calendar.`,category:'Leads',type:'demo',id:d.id,fingerprint:d.version,state:d.status,assignee:d.assignee,due:melbourneDay(new Date(d.start))})}
export async function GET(req:NextRequest){try{const c=await context();if(!c)return json({error:'PLAN.FLO staff access required.'},403);const {db,role,user}=c,view=req.nextUrl.searchParams.get('view')||'tasks',allowed=categories(role),offset=offsetFor(req.nextUrl.searchParams.get('offset'));if(offset===null)return json({error:'Invalid page.'},400);
if(view==='tasks'){const conditions=[`t.category IN (${allowed.map(()=>'?').join(',')})`],args:any[]=[...allowed],status=req.nextUrl.searchParams.get('status')||'Active',category=req.nextUrl.searchParams.get('category')||'All',assignment=req.nextUrl.searchParams.get('assignment')||'All',q=cleanText(req.nextUrl.searchParams.get('q'),200);if(category!=='All'){if(!allowed.includes(category))return json({error:'Category unavailable.'},403);conditions.push('t.category=?');args.push(category)}if(status==='Active')conditions.push("t.status NOT IN ('Done','Dismissed')");else if(status!=='All'){if(!taskStates.includes(status))return json({error:'Invalid status.'},400);conditions.push('t.status=?');args.push(status)}if(assignment==='Mine'){conditions.push('t.assignee=?');args.push(user.email.toLowerCase())}else if(assignment==='Unassigned')conditions.push("t.assignee=''");else if(assignment!=='All')return json({error:'Invalid assignment.'},400);if(q){conditions.push('(t.title LIKE ? OR t.details LIKE ?)');args.push('%'+q+'%','%'+q+'%')}const rows=(await db.prepare(`SELECT t.*,s.company,COALESCE(f.status,t.source_state) AS source_state FROM staff_tasks t LEFT JOIN settings s ON s.owner=t.company_owner LEFT JOIN feedback f ON t.source_type='ticket' AND f.id=t.source_id WHERE ${conditions.join(' AND ')} ORDER BY CASE t.priority WHEN 'Urgent' THEN 0 WHEN 'High' THEN 1 ELSE 2 END,CASE WHEN t.due='' THEN '9999' ELSE t.due END,t.updated DESC LIMIT 51 OFFSET ?`).bind(...args,offset).all()).results;const stats=await db.prepare(`SELECT COUNT(*) AS active,COALESCE(SUM(status='Review'),0) AS review,COALESCE(SUM(due<>'' AND due<?),0) AS overdue,COALESCE(SUM(assignee=?),0) AS mine FROM staff_tasks WHERE category IN (${allowed.map(()=>'?').join(',')}) AND status NOT IN ('Done','Dismissed')`).bind(melbourneDay(),user.email.toLowerCase(),...allowed).first();return json({items:rows.slice(0,50),hasMore:rows.length>50,stats,categories:allowed,team:await team(),email:user.email.toLowerCase(),today:melbourneDay(),assistant:'Rules-based review; AI and Gmail are not connected.'})}
if(view==='leads'){if(!canSales(role))return json({error:'Sales access required.'},403);const stage=req.nextUrl.searchParams.get('stage')||'All',q='%'+cleanText(req.nextUrl.searchParams.get('q'),200)+'%';if(stage!=='All'&&!leadStages.includes(stage))return json({error:'Invalid lead stage.'},400);const rows=(await db.prepare("SELECT * FROM staff_leads WHERE (?='All' OR stage=?) AND (name LIKE ? OR company LIKE ? OR email LIKE ?) ORDER BY updated DESC LIMIT 51 OFFSET ?").bind(stage,stage,q,q,q,offset).all()).results;return json({items:rows.slice(0,50),hasMore:rows.length>50,team:(await team()).filter(t=>canSales(t.role as OperatorRole))})}
if(view==='demos'){if(!canSales(role))return json({error:'Sales access required.'},403);const month=req.nextUrl.searchParams.get('month')||melbourneDay().slice(0,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)||!validDay(month+'-01'))return json({error:'Choose a valid month.'},400);const next=new Date(month+'-01T00:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);const start=dayBounds(month+'-01').start,end=dayBounds(next.toISOString().slice(0,10)).start;const rows=(await db.prepare('SELECT d.*,l.name AS contact,l.email,l.company FROM staff_demos d JOIN staff_leads l ON l.id=d.lead_id WHERE d.start>=? AND d.start<? ORDER BY d.start LIMIT 501').bind(start,end).all()).results;return json({items:rows.slice(0,500),truncated:rows.length>500,month,team:(await team()).filter(t=>canSales(t.role as OperatorRole)),googleConnected:false})}
if(view==='connections'){if(role!=='owner')return json({error:'Platform owner access required.'},403);return json({settings:await db.prepare("SELECT * FROM staff_integration_settings WHERE id='platform'").first()||{support_email:'',info_email:'',booking_url:'',version:0},gmailConnected:false,calendarConnected:false,aiConnected:false})}
return json({error:'Unknown view.'},400);
}catch(e){console.error('Staff work read',e);return json({error:'Could not load staff work. Please retry.'},500)}}
export async function POST(req:NextRequest){try{const c=await context();if(!c)return json({error:'PLAN.FLO staff access required.'},403);if(req.headers.get('origin')!==req.nextUrl.origin)return json({error:'Invalid request origin.'},403);const b:any=await req.json(),{db,role,user}=c,allowed=categories(role),now=new Date().toISOString(),id=cleanText(b.id,100);const audit=(action:string,detail:any)=>logAdmin(user.email,action,'',detail);
if(b.action==='scan'){let changed=0,checked=0,truncated=false;const commands=[];if(allowed.includes('Support')){const rows=(await db.prepare("SELECT f.*,t.priority,t.assignee,s.company FROM feedback f LEFT JOIN support_tickets t ON t.feedback_id=f.id LEFT JOIN settings s ON s.owner=f.owner WHERE f.status NOT IN ('Resolved','Closed') ORDER BY f.updated DESC LIMIT 201").all<any>()).results;truncated ||=rows.length>200;for(const f of rows.slice(0,200)){commands.push(await generated({title:'Review support · '+f.subject,details:`${safename(f.company)} · ${f.sender_email}\n${f.message.slice(0,1800)}\nNext step: review the ticket and its conversation, then respond or assign follow-up.`,category:'Support',type:'ticket',id:f.id,owner:f.owner,fingerprint:f.version,state:f.status,priority:f.priority||'Normal',assignee:await eligible(f.assignee||'','Support')?f.assignee:''}));checked++}}
if(allowed.includes('Reconciliation')){const rows=(await db.prepare("SELECT s.*,a.status AS account_status,c.company,b.customer_id FROM subscriptions s JOIN platform_accounts a ON a.owner=s.owner LEFT JOIN settings c ON c.owner=s.owner LEFT JOIN billing_accounts b ON b.owner=s.owner WHERE s.requested_at IS NOT NULL ORDER BY s.requested_at DESC LIMIT 201").all<any>()).results;truncated ||=rows.length>200;for(const s of rows.slice(0,200)){commands.push(await generated({title:'Verify package request · '+safename(s.company),details:`Requested: ${s.requested_plan||'Not specified'} on ${s.requested_at}.\n${s.customer_id?'A Stripe customer is linked.':'No Stripe customer is linked.'}\nCompare the request with the actual Stripe subscription, invoices and paid status before changing account limits. This task does not confirm payment or reconcile the bank.`,category:'Reconciliation',type:'package',id:s.owner,owner:s.owner,fingerprint:s.requested_at+'|'+s.requested_configuration,state:s.account_status}));checked++}}
if(allowed.includes('Leads')){const leads=(await db.prepare("SELECT * FROM staff_leads WHERE stage NOT IN ('Won','Lost') ORDER BY updated DESC LIMIT 201").all<any>()).results;truncated ||=leads.length>200;for(const l of leads.slice(0,200)){commands.push(await leadTask(l));checked++}}
for(let i=0;i<commands.length;i+=50){const results=await db.batch(commands.slice(i,i+50));changed+=results.reduce((n,r)=>n+r.meta.changes,0)}await audit('staff-review-scan',{checked,changed,truncated});return json({ok:true,checked,changed,truncated,message:`Checked ${checked} sources; ${changed} tasks created or refreshed.${truncated?' Showing the 200 most recent sources per category; older sources were not checked.':''}`})}
if(b.action==='task'){const old=id?await db.prepare('SELECT * FROM staff_tasks WHERE id=?').bind(id).first<any>():null;if(id&&!old)return json({error:'Task not found.'},404);const category=old?.category||cleanText(b.category,40);if(!allowed.includes(category))return json({error:'Task category unavailable.'},403);const title=cleanText(b.title,200),details=cleanText(b.details,5000),due=cleanText(b.due,10),assignee=cleanText(b.assignee,254).toLowerCase(),status=cleanText(b.status,30),priority=cleanText(b.priority,20),outcome=cleanText(b.outcome,5000);if(!title||!taskStates.includes(status)||!priorities.includes(priority)||due&&!validDay(due)||!await eligible(assignee,category))return json({error:'Check the title, status, date and assigned staff member.'},400);if(['Done','Dismissed'].includes(status)&&!outcome)return json({error:'Record the outcome before completing or dismissing a task.'},400);const taskId=old?.id||crypto.randomUUID();if(old){const r=await db.prepare('UPDATE staff_tasks SET title=?,details=?,status=?,priority=?,assignee=?,due=?,outcome=?,version=version+1,updated=? WHERE id=? AND version=?').bind(old.source_type==='manual'?title:old.title,old.source_type==='manual'?details:old.details,status,priority,assignee,due,outcome,now,id,b.version).run();if(!r.meta.changes)return json({error:'This task changed. Refresh before saving.'},409)}else await db.prepare("INSERT INTO staff_tasks(id,title,details,category,status,priority,assignee,due,source_key,outcome,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(taskId,title,details,category,status,priority,assignee,due,'manual:'+taskId,outcome,now,now).run();await audit('staff-task-save',{id:taskId,status,assignee});return json({id:taskId})}
if(b.action==='lead'){if(!canSales(role))return json({error:'Sales access required.'},403);const name=cleanText(b.name,200),company=cleanText(b.company,200),email=cleanText(b.email,254).toLowerCase(),phone=cleanText(b.phone,80),stage=cleanText(b.stage,40),assignee=cleanText(b.assignee,254).toLowerCase(),followUp=cleanText(b.follow_up,10),notes=cleanText(b.notes,5000);if(!name||email&&!validEmail(email)||!leadStages.includes(stage)||followUp&&!validDay(followUp)||!await eligible(assignee,'Leads'))return json({error:'Check the contact details, stage, follow-up date and assignee.'},400);const leadId=id||crypto.randomUUID();if(id){const r=await db.prepare('UPDATE staff_leads SET name=?,company=?,email=?,phone=?,stage=?,assignee=?,follow_up=?,notes=?,version=version+1,updated=? WHERE id=? AND version=?').bind(name,company,email,phone,stage,assignee,followUp,notes,now,id,b.version).run();if(!r.meta.changes)return json({error:'This lead changed or is unavailable. Refresh first.'},409)}else await db.prepare('INSERT INTO staff_leads(id,name,company,email,phone,stage,assignee,follow_up,notes,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(leadId,name,company,email,phone,stage,assignee,followUp,notes,now,now).run();const l=await db.prepare('SELECT * FROM staff_leads WHERE id=?').bind(leadId).first();await (await leadTask(l)).run();await audit('staff-lead-save',{id:leadId,stage});return json({id:leadId})}
if(b.action==='demo'){if(!canSales(role))return json({error:'Sales access required.'},403);const title=cleanText(b.title,200),leadId=cleanText(b.lead_id,100),assignee=cleanText(b.assignee,254).toLowerCase(),status=cleanText(b.status,30),notes=cleanText(b.notes,5000);let start:string,end:string;try{start=melbourneTime(String(b.startLocal||''));end=melbourneTime(String(b.endLocal||''))}catch(e:any){return json({error:e.message},400)}if(!title||!['Planned','Completed','Cancelled'].includes(status)||start>=end||Date.parse(end)-Date.parse(start)>8*3600000||!await eligible(assignee,'Leads'))return json({error:'Choose a title, assignee and meeting duration of up to eight hours.'},400);if(!await db.prepare('SELECT id FROM staff_leads WHERE id=?').bind(leadId).first())return json({error:'Choose an existing lead.'},400);const demoId=id||crypto.randomUUID();if(id){const r=await db.prepare('UPDATE staff_demos SET lead_id=?,title=?,start=?,end=?,status=?,assignee=?,notes=?,version=version+1,updated=? WHERE id=? AND version=?').bind(leadId,title,start,end,status,assignee,notes,now,id,b.version).run();if(!r.meta.changes)return json({error:'This demo changed. Refresh before saving.'},409)}else await db.prepare('INSERT INTO staff_demos(id,lead_id,title,start,end,status,assignee,notes,created,updated) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(demoId,leadId,title,start,end,status,assignee,notes,now,now).run();await (await demoTask(await db.prepare('SELECT * FROM staff_demos WHERE id=?').bind(demoId).first())).run();await audit('staff-demo-save',{id:demoId,status,start,end});return json({id:demoId,googleSynced:false})}
if(b.action==='connections'){if(role!=='owner')return json({error:'Platform owner access required.'},403);const support=cleanText(b.support_email,254).toLowerCase(),info=cleanText(b.info_email,254).toLowerCase(),url=cleanText(b.booking_url,1000);if(support&&!validEmail(support)||info&&!validEmail(info))return json({error:'Enter valid mailbox addresses.'},400);if(url){try{const u=new URL(url);if(u.protocol!=='https:'||!['calendar.google.com','calendar.app.google'].includes(u.hostname)||u.username||u.password)throw Error()}catch{return json({error:'Use an HTTPS Google Calendar booking link.'},400)}}const old=await db.prepare("SELECT version FROM staff_integration_settings WHERE id='platform'").first<any>();if((old?.version||0)!==b.version)return json({error:'Connection settings changed. Refresh first.'},409);const r=await db.prepare("INSERT INTO staff_integration_settings(id,support_email,info_email,booking_url,updated) VALUES('platform',?,?,?,?) ON CONFLICT(id) DO UPDATE SET support_email=excluded.support_email,info_email=excluded.info_email,booking_url=excluded.booking_url,updated=excluded.updated,version=staff_integration_settings.version+1 WHERE staff_integration_settings.version=?").bind(support,info,url,now,b.version).run();if(!r.meta.changes)return json({error:'Connection settings changed. Refresh first.'},409);await audit('staff-connections-save',{support,info,bookingUrl:url});return json({ok:true,connected:false})}
return json({error:'Unknown action.'},400);
}catch(e){console.error('Staff work save',e);return json({error:'Could not save staff work. Refresh and try again.'},500)}}
function safename(value:unknown){return cleanText(value,200)||'Unnamed company'}
