import { sqliteTable, text, integer, real, index, uniqueIndex, primaryKey, foreignKey } from 'drizzle-orm/sqlite-core';
export const projects = sqliteTable('projects', { id:text('id').primaryKey(), owner:text('owner').notNull(), name:text('name').notNull(), client:text('client').notNull().default(''), builder:text('builder').notNull().default(''),builderId:text('builder_id').notNull().default(''), address:text('address').notNull().default(''), number:text('number').notNull().default(''), contract:real('contract').notNull().default(0), budgetHours:real('budget_hours').notNull().default(0), status:text('status').notNull().default('Active'), setup:text('setup').notNull().default('{}'), lastActivity:text('last_activity').notNull().default(''), created:text('created').notNull() }, t=>[index('idx_projects_owner').on(t.owner),uniqueIndex('idx_projects_id_owner').on(t.id,t.owner)]);
export const records = sqliteTable('records', { id:text('id').primaryKey(), owner:text('owner').notNull(), projectId:text('project_id').notNull(), kind:text('kind').notNull(), title:text('title').notNull().default(''), status:text('status').notNull().default(''), data:text('data').notNull().default('{}'), created:text('created').notNull() }, t=>[index('idx_records_project_kind').on(t.projectId,t.kind)]);
export const files = sqliteTable('files', { id:text('id').primaryKey(), owner:text('owner').notNull(), projectId:text('project_id').notNull(), category:text('category').notNull(), currentRevisionId:text('current_revision_id').notNull().default(''), revisionNumber:integer('revision_number').notNull().default(1), folderId:text('folder_id').notNull().default(''), archived:integer('archived',{mode:'boolean'}).notNull().default(false), name:text('name').notNull(), mime:text('mime').notNull(), size:integer('size').notNull(), created:text('created').notNull() }, t=>[index('idx_files_project_category').on(t.projectId,t.category)]);
export const settings = sqliteTable('settings', { staffColours:text('staff_colours').notNull().default('{}'), owner:text('owner').primaryKey(), company:text('company').notNull().default(''), colour:text('colour').notNull().default('#1769f4'), theme:text('theme').notNull().default('Light'), abn:text('abn').notNull().default(''), address:text('address').notNull().default(''), email:text('email').notNull().default(''), phone:text('phone').notNull().default(''), logoFileId:text('logo_file_id').notNull().default('') });

export const companyMembers=sqliteTable('company_members',{
 projectAccessVersion:integer('project_access_version').notNull().default(0),id:text('id').primaryKey(),owner:text('owner').notNull(),email:text('email').notNull(),name:text('name').notNull(),userId:text('user_id').unique(),role:text('role').notNull().default('member'),seatType:text('seat_type').notNull().default('office'),permissions:text('permissions').notNull().default('{}'),status:text('status').notNull().default('pending'),tokenHash:text('token_hash').unique(),expires:text('expires'),created:text('created').notNull()
},t=>[index('idx_company_members_owner').on(t.owner),uniqueIndex('idx_company_members_id_owner').on(t.id,t.owner)]);
export const subscriptions=sqliteTable('subscriptions',{
 owner:text('owner').primaryKey(),plan:text('plan').notNull().default('unconfigured'),status:text('status').notNull().default('Not activated'),requestedPlan:text('requested_plan'),requestedAt:text('requested_at'),requestedConfiguration:text('requested_configuration').notNull().default('{}')
});

export const fileFolders=sqliteTable('file_folders',{
 id:text('id').primaryKey(),owner:text('owner').notNull(),projectId:text('project_id').notNull(),category:text('category').notNull(),name:text('name').notNull(),nameKey:text('name_key').notNull(),created:text('created').notNull()
},t=>[uniqueIndex('idx_file_folders_project_category_name').on(t.projectId,t.category,t.nameKey)]);

export const planRevisions=sqliteTable('plan_revisions',{id:text('id').primaryKey(),fileId:text('file_id').notNull(),number:integer('number').notNull(),label:text('label').notNull(),note:text('note').notNull().default(''),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),created:text('created').notNull()},t=>[uniqueIndex('idx_plan_revision_number').on(t.fileId,t.number)]);
export const safetyDocs=sqliteTable('safety_docs',{id:text('id').primaryKey(),owner:text('owner').notNull(),projectId:text('project_id').notNull().default(''),type:text('type').notNull(),title:text('title').notNull(),category:text('category').notNull(),status:text('status').notNull().default('Draft'),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_safety_owner_project').on(t.owner,t.projectId)]);
export const omManuals=sqliteTable('om_manuals',{id:text('id').primaryKey(),owner:text('owner').notNull(),projectId:text('project_id').notNull(),status:text('status').notNull().default('Draft'),data:text('data').notNull(),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_om_owner_project').on(t.owner,t.projectId)]);

export const builders=sqliteTable('builders',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),nameKey:text('name_key').notNull(),colour:text('colour').notNull(),status:text('status').notNull().default('Active'),data:text('data').notNull().default('{}'),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[uniqueIndex('idx_builders_owner_name').on(t.owner,t.nameKey)]);

export const feedback=sqliteTable('feedback',{resolvedAt:text('resolved_at'),id:text('id').primaryKey(),owner:text('owner').notNull(),senderId:text('sender_id').notNull(),senderName:text('sender_name').notNull(),senderEmail:text('sender_email').notNull(),type:text('type').notNull(),impact:text('impact').notNull().default(''),subject:text('subject').notNull(),message:text('message').notNull(),projectId:text('project_id').notNull().default(''),projectName:text('project_name').notNull().default(''),section:text('section').notNull().default(''),status:text('status').notNull().default('New'),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_feedback_owner_created').on(t.owner,t.created)]);

export const billingAccounts=sqliteTable('billing_accounts',{owner:text('owner').primaryKey(),customerId:text('customer_id').notNull().unique(),checkoutLock:integer('checkout_lock')});

export const reviewActivity=sqliteTable('review_activity',{id:integer('id').primaryKey({autoIncrement:true}),owner:text('owner').notNull(),projectId:text('project_id').notNull(),sourceType:text('source_type').notNull(),sourceId:text('source_id').notNull(),category:text('category').notNull(),title:text('title').notNull(),operation:text('operation').notNull(),before:text('before_data'),after:text('after_data'),occurred:text('occurred').notNull()},t=>[index('idx_review_activity_owner_id').on(t.owner,t.id),index('idx_review_activity_source').on(t.owner,t.sourceType,t.sourceId,t.id)]);
export const reviewDecisions=sqliteTable('review_decisions',{eventId:integer('event_id').primaryKey(),owner:text('owner').notNull(),decision:text('decision').notNull(),actor:text('actor').notNull(),decided:text('decided').notNull(),taskId:text('task_id')},t=>[index('idx_review_decisions_owner').on(t.owner)]);
export const reviewConfig=sqliteTable('review_config',{key:text('key').primaryKey(),value:text('value').notNull()});

export const payrollConfig=sqliteTable('payroll_config',{owner:text('owner').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(1),updated:text('updated').notNull()});
export const payrollReviews=sqliteTable('payroll_reviews',{id:text('id').primaryKey(),owner:text('owner').notNull(),start:text('start').notNull(),end:text('end').notNull(),fingerprint:text('fingerprint').notNull(),data:text('data').notNull(),state:text('state').notNull().default('Approved'),version:integer('version').notNull().default(1),syncStatus:text('sync_status').notNull().default('Not sent'),externalIds:text('external_ids').notNull().default('{}'),updated:text('updated').notNull()},t=>[uniqueIndex('idx_payroll_review_period').on(t.owner,t.start,t.end)]);

export const scheduleEntries=sqliteTable('schedule_entries',{id:text('id').primaryKey(),owner:text('owner').notNull(),workerKey:text('worker_key').notNull().default(''),workerName:text('worker_name').notNull().default(''),projectId:text('project_id').notNull().default(''),projectName:text('project_name').notNull().default(''),kind:text('kind').notNull(),date:text('date').notNull(),start:text('start').notNull().default(''),end:text('end').notNull().default(''),breakMinutes:integer('break_minutes').notNull().default(0),notes:text('notes').notNull().default(''),leaveType:text('leave_type').notNull().default(''),role:text('role').notNull().default(''),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_schedule_owner_date').on(t.owner,t.date)]);

export const appSettings=sqliteTable('app_settings',{owner:text('owner').primaryKey(),data:text('data').notNull(),version:integer('version').notNull().default(1),updated:text('updated').notNull()});

export const platformAccounts=sqliteTable('platform_accounts',{owner:text('owner').primaryKey(),status:text('status').notNull().default('Active'),reason:text('reason').notNull().default(''),notes:text('notes').notNull().default(''),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()});
export const platformUsers=sqliteTable('platform_users',{id:text('id').primaryKey(),owner:text('owner').notNull(),name:text('name').notNull(),email:text('email').notNull(),status:text('status').notNull().default('Active'),firstSeen:text('first_seen').notNull(),lastSeen:text('last_seen').notNull(),version:integer('version').notNull().default(1)},t=>[index('idx_platform_users_owner').on(t.owner),index('idx_platform_users_seen').on(t.lastSeen)]);
export const platformUsage=sqliteTable('platform_usage',{owner:text('owner').notNull(),userId:text('user_id').notNull(),day:text('day').notNull(),section:text('section').notNull(),views:integer('views').notNull().default(1)},t=>[uniqueIndex('idx_platform_usage_key').on(t.owner,t.userId,t.day,t.section),index('idx_platform_usage_day').on(t.day)]);
export const supportTickets=sqliteTable('support_tickets',{topic:text('topic').notNull().default(''),feedbackId:text('feedback_id').primaryKey(),category:text('category').notNull(),priority:text('priority').notNull(),assignee:text('assignee').notNull().default(''),version:integer('version').notNull().default(1),updated:text('updated').notNull()});
export const supportNotes=sqliteTable('support_notes',{id:text('id').primaryKey(),feedbackId:text('feedback_id').notNull(),author:text('author').notNull(),body:text('body').notNull(),created:text('created').notNull()},t=>[index('idx_support_notes_feedback').on(t.feedbackId,t.created)]);
export const platformAudit=sqliteTable('platform_audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),owner:text('owner').notNull().default(''),detail:text('detail').notNull(),created:text('created').notNull()},t=>[index('idx_platform_audit_date').on(t.created),index('idx_platform_audit_owner').on(t.owner)]);
export const uploadOutcomes=sqliteTable('upload_outcomes',{id:text('id').primaryKey(),owner:text('owner').notNull(),route:text('route').notNull(),status:integer('status').notNull(),created:text('created').notNull()},t=>[index('idx_upload_outcomes_created').on(t.created)]);
export const platformOperators=sqliteTable('platform_operators',{email:text('email').primaryKey(),role:text('role').notNull(),active:integer('active').notNull().default(1),version:integer('version').notNull().default(1),updated:text('updated').notNull()});
export const accountLimits=sqliteTable('account_limits',{owner:text('owner').primaryKey(),enabled:integer('enabled').notNull().default(0),plan:text('plan').notNull().default(''),projects:integer('projects').notNull(),office:integer('office').notNull(),field:integer('field').notNull(),bytes:integer('bytes').notNull(),overrideProjects:integer('override_projects'),overrideOffice:integer('override_office'),overrideField:integer('override_field'),overrideBytes:integer('override_bytes'),expires:text('expires'),reason:text('reason').notNull().default(''),version:integer('version').notNull().default(1)});
export const customerMessages=sqliteTable('customer_messages',{id:text('id').primaryKey(),owner:text('owner').notNull(),recipient:text('recipient').notNull().default(''),ticketId:text('ticket_id').notNull().default(''),subject:text('subject').notNull(),body:text('body').notNull(),author:text('author').notNull(),created:text('created').notNull()},t=>[index('idx_customer_messages_owner').on(t.owner)]);
export const messageReads=sqliteTable('message_reads',{messageId:text('message_id').notNull(),userId:text('user_id').notNull(),read:text('read').notNull()},t=>[uniqueIndex('idx_message_read').on(t.messageId,t.userId)]);
export const deletionRequests=sqliteTable('deletion_requests',{owner:text('owner').primaryKey(),status:text('status').notNull(),reason:text('reason').notNull(),requested:text('requested').notNull(),eligible:text('eligible').notNull(),actor:text('actor').notNull(),version:integer('version').notNull().default(1)});
export const supportSessions=sqliteTable('support_sessions',{id:text('id').primaryKey(),actor:text('actor').notNull(),owner:text('owner').notNull(),userId:text('user_id').notNull(),reason:text('reason').notNull(),expires:text('expires').notNull(),created:text('created').notNull()});

export const staffTasks=sqliteTable('staff_tasks',{id:text('id').primaryKey(),title:text('title').notNull(),details:text('details').notNull().default(''),category:text('category').notNull(),status:text('status').notNull().default('Review'),priority:text('priority').notNull().default('Normal'),assignee:text('assignee').notNull().default(''),due:text('due').notNull().default(''),companyOwner:text('company_owner').notNull().default(''),sourceType:text('source_type').notNull().default('manual'),sourceId:text('source_id').notNull().default(''),sourceKey:text('source_key').notNull(),fingerprint:text('fingerprint').notNull().default(''),sourceState:text('source_state').notNull().default(''),outcome:text('outcome').notNull().default(''),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[uniqueIndex('idx_staff_tasks_source').on(t.sourceKey),index('idx_staff_tasks_category_status').on(t.category,t.status)]);
export const staffLeads=sqliteTable('staff_leads',{id:text('id').primaryKey(),name:text('name').notNull(),company:text('company').notNull().default(''),email:text('email').notNull().default(''),phone:text('phone').notNull().default(''),stage:text('stage').notNull().default('New'),assignee:text('assignee').notNull().default(''),followUp:text('follow_up').notNull().default(''),notes:text('notes').notNull().default(''),source:text('source').notNull().default('Manual'),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_staff_leads_stage').on(t.stage)]);
export const staffDemos=sqliteTable('staff_demos',{id:text('id').primaryKey(),leadId:text('lead_id').notNull(),title:text('title').notNull(),start:text('start').notNull(),end:text('end').notNull(),status:text('status').notNull().default('Planned'),assignee:text('assignee').notNull().default(''),notes:text('notes').notNull().default(''),version:integer('version').notNull().default(1),created:text('created').notNull(),updated:text('updated').notNull()},t=>[index('idx_staff_demos_start').on(t.start)]);
export const staffIntegrationSettings=sqliteTable('staff_integration_settings',{id:text('id').primaryKey(),supportEmail:text('support_email').notNull().default(''),infoEmail:text('info_email').notNull().default(''),bookingUrl:text('booking_url').notNull().default(''),version:integer('version').notNull().default(1),updated:text('updated').notNull()});

export const projectMembers=sqliteTable('project_members',{
 owner:text('owner').notNull(),projectId:text('project_id').notNull(),memberId:text('member_id').notNull(),
},t=>[primaryKey({columns:[t.owner,t.projectId,t.memberId]}),index('idx_project_members_member').on(t.memberId,t.owner),foreignKey({columns:[t.projectId,t.owner],foreignColumns:[projects.id,projects.owner]}).onDelete('cascade'),foreignKey({columns:[t.memberId,t.owner],foreignColumns:[companyMembers.id,companyMembers.owner]}).onDelete('cascade')]);

export {user,session,account,verification,rateLimit} from './auth-schema';
