'use client';
import {BusinessRegistrationFields} from '../registration-fields';
import {useState} from 'react';
export function safeReturn(value:string){try{const url=new URL(value,'https://local.invalid');return value.startsWith('/')&&!value.startsWith('//')&&url.origin==='https://local.invalid'&&!/^\/(login|logout|api\/auth)/.test(url.pathname)?url.pathname+url.search:'/';}catch{return '/';}}
export default function AuthForm({returnTo='/',token='',initialMode='login'}:{returnTo?:string;token?:string;initialMode?:string}){
 const invitation=new URL(safeReturn(returnTo),'https://local.invalid').pathname==='/join';
 const [mode,setMode]=useState(token?'reset':initialMode),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const fields=Object.fromEntries(new FormData(event.currentTarget));const target=safeReturn(returnTo);const endpoint={login:'sign-in/email',signup:'sign-up/email',recovery:'request-password-reset',reset:'reset-password',verify:'send-verification-email'}[mode];
 try{const body=mode==='reset'?{token,newPassword:fields.password}:mode==='recovery'?{email:fields.email,redirectTo:'/login'}:mode==='verify'?{email:fields.email,callbackURL:'/login?return_to='+encodeURIComponent(target)}:{...fields,...(mode==='signup'?{signupIntent:invitation?'join':'business'}:{}),callbackURL:'/login?return_to='+encodeURIComponent(target)};
 const response=await fetch('/api/auth/'+endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const failure=await response.json().catch(()=>null) as {code?:string;error?:string}|null;if(failure?.code==='INVALID_REGISTRATION'){setMessage(failure.error||'Check your registration details.');return;}setMessage(response.status===429?'Too many attempts. Please wait a minute.':'Unable to complete this request. Check your details or try again later.');return;}
 if(mode==='login'){window.location.assign(target);return;}setMessage(mode==='reset'?'Password updated. You can now sign in.':'If this address is eligible, an email will arrive with the next step.');if(mode==='reset')setMode('login');
 }catch{setMessage('Connection failed. Please try again.');}finally{setBusy(false)}}
 const title={login:'Sign in',signup:'Create your account',recovery:'Reset your password',reset:'Choose a new password',verify:'Resend verification'}[mode];
 return <main className="welcome-screen"><section className="welcome-card"><h1>PLAN.FLO</h1><h2>{title}</h2><form onSubmit={submit} style={{display:'grid',gap:16}}>{mode==='signup'&&<><label>Name<input name="firstName" required maxLength={80} autoComplete="given-name"/></label><label>Surname<input name="surname" required maxLength={80} autoComplete="family-name"/></label>{invitation&&<p>You are joining an existing company. Business details are optional here and will not change that company.</p>}<BusinessRegistrationFields required={!invitation}/></>}{mode!=='reset'&&<label>Email address<input name="email" type="email" required maxLength={254} autoComplete="email"/></label>}{['login','signup','reset'].includes(mode)&&<label>Password<input name="password" type="password" required minLength={mode==='login'?1:12} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'}/>{mode!=='login'&&<small>Use at least 12 characters.</small>}</label>}<button disabled={busy} type="submit">{busy?'Please wait…':title}</button></form>{message&&<p role="status">{message}</p>}<nav style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:20}}>{['login','signup','recovery','verify'].filter(x=>x!==mode).map(x=><button key={x} onClick={()=>{setMode(x);setMessage('')}}>{({login:'Sign in',signup:'Create account',recovery:'Forgot password?',verify:'Resend verification'})[x]}</button>)}</nav></section></main>;
}
