import {invalidMutationOrigin} from '@/app/request-origin';
import {canAccessProject,projectScope} from '@/app/project-access';
import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess} from '@/app/company-access';
import {canAccess} from '@/app/permissions';
import {reviewCategories,reviewAllowed,reviewItem,melbourneDay,validDay,dayBounds} from '@/app/daily-review-model';
const json=(v:unknown,status=200)=>NextResponse.json(v,{status,headers:{'Cache-Control':'private, no-store'}});
async function context(){const user=await getChatGPTUser();if(!user)return null;const access=await getCompanyAccess(user);if(access.disabledTabs?.includes('My Tasks')||access.disabledTabs?.includes('Daily Review')||!canAccess(access,'Tasks'))return null;return {user,access,db:companyDb()}}
export async function GET(req:NextRequest){try{const c=await context();if(!c)return json({error:'You do not have access to Daily Review.'},403);const day=req.nextUrl.searchParams.get('date')||melbourneDay();if(!validDay(day)||day>melbourneDay())return json({error:'Choose today or an earlier date.'},400);const mode=req.nextUrl.searchParams.get('mode')||'queue',offset=Number(req.nextUrl.searchParams.get('offset')||0);if(!['queue','activity','reviewed'].includes(mode)||!Number.isInteger(offset)||offset<0)return json({error:'Invalid review view.'},400);const cats=reviewCategories.filter(x=>reviewAllowed(c.access,x)),{start,end}=dayBounds(day),started=await c.db.prepare("SELECT value FROM review_config WHERE key='tracking_started'").first<{value:string}>();const projects=(await c.db.prepare('SELECT id,name,status FROM projects WHERE owner=? ORDER BY name').bind(c.access.owner).all<{id:string}>()).results.filter(p=>canAccessProject(c.access,p.id));const members=(await c.db.prepare("SELECT name,email,user_id FROM company_members WHERE owner=? AND status='active'").bind(c.access.owner).all<any>()).results;const people=[{key:'user:'+c.access.owner,name:c.access.owner===c.user.userId?c.user.displayName:'Company owner'},...members.map(m=>({key:'user:'+m.user_id,name:m.name}))];if(!cats.length)return json({items:[],projects,people,day,trackingStarted:started?.value,editable:false,hasMore:false});const filter=req.nextUrl.searchParams.get('project')||'';if(filter&&!projects.some(p=>p.id===filter))return json({error:'Project unavailable.'},404);
const conditions=[`a.owner=?`,`a.category IN (${cats.map(()=>'?').join(',')})`,'a.occurred < ?'];const scope=projectScope(c.access,'a.project_id');conditions.push(scope.sql);const args:any[]=[c.access.owner,...cats,end,...scope.args];if(filter){conditions.push('a.project_id=?');args.push(filter)}if(mode==='activity'){conditions.push('a.occurred >= ?');args.push(start)}else if(mode==='reviewed'){conditions.push('d.decided >= ? AND d.decided < ?');args.push(start,end)}else{conditions.push('d.event_id IS NULL');conditions.push('NOT EXISTS (SELECT 1 FROM review_activity newer WHERE newer.owner=a.owner AND newer.source_type=a.source_type AND newer.source_id=a.source_id AND newer.id>a.id)');}
const rows=(await c.db.prepare(`SELECT a.*,p.name AS projectName,d.decision,d.actor,d.decided,d.task_id FROM review_activity a JOIN projects p ON p.id=a.project_id AND p.owner=a.owner LEFT JOIN review_decisions d ON d.event_id=a.id AND d.owner=a.owner WHERE ${conditions.join(' AND ')} ORDER BY a.id DESC LIMIT 101 OFFSET ?`).bind(...args,offset).all<any>()).results;
return json({items:rows.slice(0,100).map(reviewItem),hasMore:rows.length>100,projects,people,day,trackingStarted:started?.value,editable:canAccess(c.access,'Tasks',true),selfKey:'user:'+c.user.userId,generated:new Date().toISOString(),mode});}catch(e){console.error('Daily Review load failed',e);return json({error:'Could not load Daily Review. Please retry.'},500)}}
export async function POST(req:NextRequest){if(invalidMutationOrigin(req))return new Response(JSON.stringify({error:'Invalid request origin'}),{status:403,headers:{'content-type':'application/json'}});try{const c=await context();if(!c||!canAccess(c.access,'Tasks',true))return json({error:'Task edit permission is required to review activity.'},403);const b:any=await req.json();if(!Number.isSafeInteger(b.eventId)||!['Verified','No action needed','Follow-up created'].includes(b.decision))return json({error:'Choose a valid review action.'},400);const row=await c.db.prepare('SELECT a.*,p.name AS projectName FROM review_activity a JOIN projects p ON p.id=a.project_id AND p.owner=a.owner WHERE a.id=? AND a.owner=?').bind(b.eventId,c.access.owner).first<any>();if(!row||!canAccessProject(c.access,row.project_id)||!reviewAllowed(c.access,row.category))return json({error:'Activity unavailable.'},404);const existing=await c.db.prepare('SELECT decision,task_id AS taskId FROM review_decisions WHERE event_id=? AND owner=?').bind(row.id,c.access.owner).first();if(existing)return json({ok:true,...existing});const latest=await c.db.prepare('SELECT MAX(id) AS id FROM review_activity WHERE owner=? AND source_type=? AND source_id=?').bind(c.access.owner,row.source_type,row.source_id).first<any>();if(latest?.id!==row.id)return json({error:'This source has newer activity. Refresh and review the latest change.'},409);
const item=reviewItem(row),now=new Date().toISOString();let taskId:string|null=null,taskData:any=null,title='';if(b.decision==='Follow-up created'){title=String(b.title||item.title).trim().slice(0,240);if(!title)return json({error:'Enter a task title.'},400);const key=String(b.assigneeKey||'user:'+c.user.userId);let assignee=c.user.displayName;if(key!=='user:'+c.access.owner){const member=await c.db.prepare("SELECT name FROM company_members WHERE owner=? AND user_id=? AND status='active'").bind(c.access.owner,key.startsWith('user:')?key.slice(5):'').first<any>();if(!member)return json({error:'Choose an active company user.'},400);assignee=member.name}else if(c.user.userId!==c.access.owner)assignee='Company owner';const due=String(b.due||'');if(due&&!validDay(due))return json({error:'Choose a valid due date.'},400);const source=row.source_type+':'+row.source_id;const open=await c.db.prepare("SELECT id FROM records WHERE owner=? AND project_id=? AND kind='task' AND status<>'Complete' AND json_extract(data,'$.dailyReviewSource')=? LIMIT 1").bind(c.access.owner,row.project_id,source).first<any>();taskId=open?.id||'review-event-'+row.id;taskData={description:String(b.description||item.suggestion).trim().slice(0,10000),assigneeKey:key,assignee,due,priority:item.priority,location:item.tab,fileIds:[],notes:[],version:1,updated:now,dailyReviewEvent:row.id,dailyReviewSource:source};}
const decision=c.db.prepare(`INSERT INTO review_decisions(event_id,owner,decision,actor,decided,task_id) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM review_activity WHERE owner=? AND source_type=? AND source_id=? AND id>?) ON CONFLICT(event_id) DO NOTHING`).bind(row.id,c.access.owner,b.decision,c.user.displayName,now,taskId,c.access.owner,row.source_type,row.source_id,row.id);const statements=[decision];if(taskId){statements.push(c.db.prepare("INSERT INTO records(id,owner,project_id,kind,title,status,data,created) SELECT ?,?,?,'task',?,'To Do',?,? WHERE EXISTS(SELECT 1 FROM review_decisions WHERE event_id=? AND owner=? AND task_id=?) ON CONFLICT(id) DO NOTHING").bind(taskId,c.access.owner,row.project_id,title,JSON.stringify(taskData),now,row.id,c.access.owner,taskId))}await c.db.batch(statements);const saved=await c.db.prepare('SELECT decision,task_id AS taskId FROM review_decisions WHERE event_id=? AND owner=?').bind(row.id,c.access.owner).first();if(!saved)return json({error:'This source changed while reviewing. Refresh and try again.'},409);return json({ok:true,...saved});}catch(e){console.error('Daily Review save failed',e);return json({error:'Could not save the review. Please retry.'},500)}}
