import {ownedWorkspacePredicate,ownedWorkspaceTables} from '@/app/workspace-ownership';
import {limitMessage} from '@/app/account-limits';
import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess,hashInvite} from '@/app/company-access';
import {fieldUserTabs} from '@/app/subscription-plans';
import {normalisePermissions} from '@/app/permissions';
const json=NextResponse.json;
export async function GET(){const user=await getChatGPTUser();if(!user)return json({error:'Sign in required'},{status:401});try{const access=await getCompanyAccess(user);if(access.blocked)return json({error:'Your company access has been disabled.'},{status:403});const db=companyDb();const members=access.role==='member'?[]:(await db.prepare('SELECT id,email,name,role,seat_type AS seatType,permissions,status,expires FROM company_members WHERE owner = ? ORDER BY created DESC').bind(access.owner).all()).results;const subscription=await db.prepare('SELECT plan,status,requested_plan AS requestedPlan,requested_at AS requestedAt FROM subscriptions WHERE owner = ?').bind(access.owner).first();return json({access,members,subscription:subscription||{plan:'unconfigured',status:'Not activated',requestedPlan:null}})}catch(e){if(limitMessage(e))return json({error:limitMessage(e)},{status:409});console.error(e);return json({error:'Could not load company settings. Try again.'},{status:500})}}
export async function POST(req:NextRequest){const user=await getChatGPTUser();if(!user)return json({error:'Sign in required'},{status:401});try{const b:any=await req.json(),db=companyDb();
 if(req.headers.get('origin')!==req.nextUrl.origin)return json({error:'Invalid request origin'},{status:403});if(b.action==='accept'){if(await db.prepare("SELECT 1 FROM platform_users WHERE id=? AND status!='Active'").bind(user.userId).first())return json({error:'Account access is unavailable.'},{status:403});const hash=await hashInvite(String(b.token||''));const invite=await db.prepare("SELECT * FROM company_members WHERE token_hash = ? AND status = 'pending' AND expires > ?").bind(hash,new Date().toISOString()).first<any>();if(!invite)return json({error:'This invitation has expired or is no longer available.'},{status:400});if((await db.prepare('SELECT status FROM platform_accounts WHERE owner=?').bind(invite.owner).first<any>())?.status!=='Active')return json({error:'Company access is unavailable.'},{status:403});if(invite.owner===user.userId)return json({error:'You already own this company.'},{status:400});if(invite.email!==user.email.trim().toLowerCase())return json({error:'Sign in with the email address this invitation was created for.'},{status:403});const existing=await db.prepare('SELECT id FROM company_members WHERE user_id = ?').bind(user.userId).first();if(existing)return json({error:'This account already belongs to a company. Ask its administrator to update your access.'},{status:409});if(await db.prepare(`SELECT 1 AS owned WHERE ${ownedWorkspacePredicate('?')}`).bind(...Array(ownedWorkspaceTables.length).fill(user.userId)).first())return json({error:'This account already owns company data. Keep that workspace and use a separate account, or arrange an explicit ownership transfer before joining.'},{status:409});const result=await db.prepare(`UPDATE company_members SET user_id = ?, status = 'active', token_hash = NULL, expires = NULL WHERE id = ? AND status = 'pending' AND token_hash = ? AND expires > ? AND NOT (${ownedWorkspacePredicate('?')})`).bind(user.userId,invite.id,hash,new Date().toISOString(),...Array(ownedWorkspaceTables.length).fill(user.userId)).run();if(!result.meta.changes)return json({error:'This invitation is no longer available.'},{status:409});return json({ok:true});}
 if(req.headers.get('origin')!==req.nextUrl.origin)return json({error:'Invalid request origin'},{status:403});
 const seatType=b.seatType==='field'?'field':'office';
 const memberRole=seatType==='office'&&b.role==='admin'?'admin':'member';
 const permissions=normalisePermissions(b.permissions);
 if(seatType==='field')for(const tab of Object.keys(permissions))if(!fieldUserTabs.includes(tab))permissions[tab]={view:false,edit:false};
 const access=await getCompanyAccess(user);if(access.blocked||access.role==='member')return json({error:'Administrator access is required.'},{status:403});
 if(b.action==='add'){const email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim().slice(0,120);if(!name||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)return json({error:'Enter a name and valid email address.'},{status:400});if(email===user.email.toLowerCase())return json({error:'You already have access. Add a different team member.'},{status:400});const existing=await db.prepare('SELECT id FROM company_members WHERE owner = ? AND email = ?').bind(access.owner,email).first();if(existing)return json({error:'This person is already listed. Edit or reactivate their access.'},{status:409});const token=crypto.randomUUID()+crypto.randomUUID(),expires=new Date(Date.now()+7*86400000).toISOString();await db.prepare('INSERT INTO company_members (id,owner,email,name,role,seat_type,permissions,status,token_hash,expires,created) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),access.owner,email,name,memberRole,seatType,JSON.stringify(permissions),'pending',await hashInvite(token),expires,new Date().toISOString()).run();return json({ok:true,token});}
 if(['update','disable','invite'].includes(b.action)){const member=await db.prepare('SELECT * FROM company_members WHERE id = ? AND owner = ?').bind(String(b.id),access.owner).first<any>();if(!member)return json({error:'User not found.'},{status:404});if(member.user_id===user.userId)return json({error:'Ask another administrator to change your own access.'},{status:400});if(b.action==='disable'){await db.prepare("UPDATE company_members SET status='disabled', token_hash=NULL, expires=NULL WHERE id=? AND owner=?").bind(member.id,access.owner).run();return json({ok:true});}if(b.action==='invite'){if(member.user_id){await db.prepare("UPDATE company_members SET status='active' WHERE id=? AND owner=?").bind(member.id,access.owner).run();return json({ok:true});}const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare("UPDATE company_members SET status='pending',token_hash=?,expires=? WHERE id=? AND owner=?").bind(await hashInvite(token),new Date(Date.now()+7*86400000).toISOString(),member.id,access.owner).run();return json({ok:true,token});}await db.prepare('UPDATE company_members SET name=?,role=?,seat_type=?,permissions=? WHERE id=? AND owner=?').bind(String(b.name||member.name).slice(0,120),memberRole,seatType,JSON.stringify(permissions),member.id,access.owner).run();return json({ok:true});}
 if(b.action==='subscription'){if(!['basic','standard','pro','business-pro'].includes(b.plan))return json({error:'Choose a valid plan.'},{status:400});await db.prepare("INSERT INTO subscriptions (owner,requested_plan,requested_at) VALUES (?,?,?) ON CONFLICT(owner) DO UPDATE SET requested_plan=excluded.requested_plan,requested_at=excluded.requested_at").bind(access.owner,b.plan,new Date().toISOString()).run();return json({ok:true});}
 if(b.action==='cancelSubscriptionRequest'){await db.prepare('UPDATE subscriptions SET requested_plan=NULL,requested_at=NULL WHERE owner=?').bind(access.owner).run();return json({ok:true});}
 return json({error:'Unknown action'},{status:400});
 }catch(e){if(limitMessage(e))return json({error:limitMessage(e)},{status:409});console.error(e);return json({error:'Could not save company settings. Please try again.'},{status:500})}}
