import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {getCompanyAccess} from '@/app/company-access';
import {invalidMutationOrigin} from '@/app/request-origin';
import {beginXero,xeroStatus,selectXero,disconnectXero,refreshXero,saveXeroMapping} from '@/app/xero-service';
const fail=(error:string,status=400)=>NextResponse.json({error},{status,headers:{'Cache-Control':'no-store'}});
async function context(){const user=await getChatGPTUser();if(!user)return null;const access=await getCompanyAccess(user);return !access.blocked&&access.role!=='member'&&!access.disabledTabs?.includes('Time')?{user,access}:null}
export async function GET(req:NextRequest){const c=await context();if(!c)return fail('Company administrator access is required.',403);try{return NextResponse.json(await xeroStatus(c.access.owner,req.nextUrl.origin),{headers:{'Cache-Control':'no-store'}})}catch{return fail('Could not load Xero setup. Try again.',503)}}
export async function POST(req:NextRequest){if(invalidMutationOrigin(req))return fail('Invalid request origin.',403);const c=await context();if(!c)return fail('Company administrator access is required.',403);try{const b:any=await req.json(),owner=c.access.owner;if(b.action==='connect')return NextResponse.json({url:await beginXero(owner,c.user.userId,req.nextUrl.origin)});if(!Number.isInteger(b.version)||b.version<0)return fail('Refresh the connection before making changes.');if(b.action==='select')await selectXero(owner,b.version,b.tenantId);else if(b.action==='disconnect')return NextResponse.json(await disconnectXero(owner,b.version));else if(b.action==='refresh')await refreshXero(owner,b.version);else if(b.action==='mapping')await saveXeroMapping(owner,b.version,b.mapping);else return fail('Unknown Xero action.');return NextResponse.json({ok:true})}catch(e){const message=e instanceof Error?e.message:'';return fail(/^(Xero |Complete Xero |Another Xero |Connection |Choose |That organisation |This organisation |The employee |Match each |Refresh )/.test(message)?message:'Could not update Xero. Refresh and try again.')}}
