import {NextRequest} from 'next/server';
import {buildDemoData,demoDrawingSvg} from '../app/demo/demo-data';
import * as api from '../app/api/demo/route';
import * as drawing from '../app/api/demo/drawing/route';
import {demoAccessDenial} from '../app/demo/demo-access';
export async function demoChecks({sql,check,identity,req}:any){
 const test=(n:string,ok:boolean)=>check('private demo '+n,ok,{}),request=(path='/api/demo')=>req(path);
 const businessTables=['projects','records','files','settings','company_members','project_members','builders','gmail_connections','xero_connections','schedule_entries','payroll_config','dashboard_layouts'];
 const snapshot=()=>JSON.stringify(businessTables.map(t=>[t,sql.prepare('SELECT * FROM '+t).all()]));const before=snapshot();
 for(const who of [null,'a','aa','ae','b','support']){identity(who);const status=who?403:401;test((who||'anonymous')+' denied data',(await api.GET(request())).status===status);test((who||'anonymous')+' denied drawing',(await drawing.GET(request('/api/demo/drawing'))).status===status);test((who||'anonymous')+' denied page guard',(await demoAccessDenial())?.status===status);test((who||'anonymous')+' denied writes',(await api.POST()).status===status);}
 identity('rob');test('configured owner passes page guard',await demoAccessDenial()===null);const r=await api.GET(request()),d=await r.json() as ReturnType<typeof buildDemoData>;test('configured owner reads private data',r.status===200&&d.company==='Urban Charge Electrical'&&d.project.name==='Riverside Warehouse');test('data cache disabled',r.headers.get('cache-control')==='private, no-store'&&r.headers.get('vary')==='Cookie');
 const pic=await drawing.GET(request('/api/demo/drawing'));test('owner reads generated labelled drawing',pic.status===200&&(await pic.text()).includes('NOT FOR CONSTRUCTION'));test('drawing cache and content isolation',pic.headers.get('cache-control')==='private, no-store'&&pic.headers.get('content-security-policy')?.includes('sandbox')===true);
 for(const route of [api,drawing]){for(const method of ['POST','PUT','PATCH','DELETE'] as const)test('owner '+method+' cannot mutate',(await route[method]()).status===405);}
 for(const suffix of ['?owner=a','?projectId=a1','?userId=rob','?fileId=real-file']){test('rejects forged selector '+suffix,(await api.GET(request('/api/demo'+suffix))).status===400);test('drawing rejects forged selector '+suffix,(await drawing.GET(request('/api/demo/drawing'+suffix))).status===400);}
 const env=(globalThis as any).__testEnv,savedOwner=env.PLANFLO_PLATFORM_OWNER_ID,savedEmail=env.PLANFLO_PLATFORM_OWNER_EMAIL;
 env.PLANFLO_PLATFORM_OWNER_ID='different-owner';test('matching email alone insufficient',(await api.GET(request())).status===403);env.PLANFLO_PLATFORM_OWNER_ID=savedOwner;env.PLANFLO_PLATFORM_OWNER_EMAIL='different@example.test';test('matching subject alone insufficient',(await api.GET(request())).status===403);delete env.PLANFLO_PLATFORM_OWNER_ID;test('missing owner config fails closed',(await api.GET(request())).status===403);env.PLANFLO_PLATFORM_OWNER_ID=savedOwner;env.PLANFLO_PLATFORM_OWNER_EMAIL=savedEmail;
 const user=sql.prepare("SELECT status,owner FROM platform_users WHERE id='rob'").get();const account=sql.prepare('SELECT status FROM platform_accounts WHERE owner=?').get(user.owner);
 sql.prepare("UPDATE platform_users SET status='Disabled' WHERE id='rob'").run();test('disabled owner denied',(await api.GET(request())).status===403&&(await drawing.GET(request('/api/demo/drawing'))).status===403);sql.prepare("UPDATE platform_users SET status=? WHERE id='rob'").run(user.status);
 sql.prepare("UPDATE platform_accounts SET status='Suspended' WHERE owner=?").run(user.owner);test('disabled owner company denied',(await demoAccessDenial())?.status===403);sql.prepare('UPDATE platform_accounts SET status=? WHERE owner=?').run(account.status,user.owner);
 const savedDb=env.DB;env.DB=undefined;test('authorization storage outage fails closed',(await api.GET(request())).status===503);env.DB=savedDb;
 const t=d.totals;test('exact three variations two approved one pending',d.variations.length===3&&d.variations.filter(v=>v.status==='Approved').length===2&&d.variations.filter(v=>v.status==='Pending').length===1);test('variation line items reconcile',d.variations.every(v=>v.amount===v.items.reduce((n,i)=>n+i.quantity*i.rate,0)));
 test('contract excludes pending variation',t.baseContract===240000&&t.approvedVariations===25500&&t.pendingVariations===9800&&t.revisedContract===265500&&t.potentialContract===275300);
 test('four synthetic staff and 70 real sample entries',d.staff.length===4&&d.timesheets.length===70&&d.timesheets.every(e=>d.staff.some(s=>s.id===e.staffId)&&e.cost===e.hours*e.rate));test('hours and labour reconcile',t.actualHours===500&&t.actualLabour===33200&&d.timesheets.reduce((n,e)=>n+e.hours,0)===500&&d.timesheets.reduce((n,e)=>n+e.cost,0)===33200);
 test('cost budget and actual reconcile',t.budgetHours===1600&&t.budgetCost===205000&&t.actualMaterials===34800&&t.actualCost===68000&&t.remainingBudget===137000&&d.expenses.reduce((n,e)=>n+e.amount,0)===t.actualMaterials);
 test('PO is a separate commitment',d.project.purchaseOrderReference===d.purchaseOrder.reference&&d.purchaseOrder.amount===12000&&d.purchaseOrder.items.reduce((n,i)=>n+i.quantity*i.rate,0)===12000&&t.uncommittedMaterials===38200&&t.actualCost===t.actualLabour+t.actualMaterials);
 test('two RFIs one answered and one open',d.rfis.length===2&&d.rfis.filter(r=>r.status==='Responded').length===1&&d.rfis.filter(r=>r.status==='Issued').length===1);
 test('equal weight progress independently reconciles',t.completedStages===4&&t.totalStages===9&&t.progressPercent===44&&Object.values(d.project.stageProgress).filter(Boolean).length===4);
 test('stable independent fixtures',JSON.stringify(buildDemoData())===JSON.stringify(d));d.staff[0].name='Changed';test('returned fixture edits never persist',buildDemoData().staff[0].name==='Alex Demo');test('drawing has no external resources',!demoDrawingSvg().includes('href=')&&!demoDrawingSvg().includes('<script'));
 test('no business records changed',snapshot()===before);identity('a');
}
