import {NextRequest,NextResponse} from 'next/server';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {operatorRole,protectedCompany,logAdmin} from '@/app/operator-access';
import {operatorEmails,platformDb} from '@/app/platform-store';
import {getCompanyAccess,hashInvite} from '@/app/company-access';
import {cleanText,validEmail} from '@/app/platform-model';
import {limitsFor,limitMessage} from '@/app/account-limits';
import {canAccess,recordTab,fileTab} from '@/app/permissions';
const json=(v:unknown,status=200)=>NextResponse.json(v,{status,headers:{'Cache-Control':'private, no-store'}});
async function context(){const user=await getChatGPTUser();const role=user?await operatorRole(user):null;return user&&role?{user,role,db:platformDb()}:null}
async function known(owner:string){return platformDb().prepare('SELECT owner,status FROM platform_accounts WHERE owner=?').bind(owner).first<any>()}
async function detail(owner:string){const db=platformDb();const [company,users,members,limits,history,messages,deletion,tickets]=await Promise.all([db.prepare('SELECT company,email,phone FROM settings WHERE owner=?').bind(owner).first(),db.prepare('SELECT id,name,email,status,last_seen FROM platform_users WHERE owner=?').bind(owner).all(),db.prepare('SELECT id,name,email,role,seat_type,status,expires,user_id FROM company_members WHERE owner=?').bind(owner).all(),limitsFor(owner),db.prepare('SELECT action,actor,created,detail FROM platform_audit WHERE owner=? ORDER BY created DESC LIMIT 100').bind(owner).all(),db.prepare('SELECT m.*, (SELECT COUNT(*) FROM message_reads r WHERE r.message_id=m.id) AS readers FROM customer_messages m WHERE owner=? ORDER BY created DESC LIMIT 100').bind(owner).all(),db.prepare('SELECT * FROM deletion_requests WHERE owner=?').bind(owner).first(),db.prepare('SELECT id,subject,sender_email,status FROM feedback WHERE owner=? ORDER BY created DESC LIMIT 100').bind(owner).all()]);return {tickets:tickets.results,company,users:users.results,members:members.results,...limits,history:history.results,messages:messages.results,deletion}}
const exportTables=['projects','records','files','file_folders','settings','builders','safety_docs','om_manuals','schedule_entries','app_settings','payroll_config','payroll_reviews','subscriptions','customer_messages'] as const;
export async function GET(req:NextRequest){try{const c=await context();if(!c||c.role==='billing')return json({error:'Owner or support access required.'},403);const {db,user,role}=c,owner=cleanText(req.nextUrl.searchParams.get('owner'),200),view=req.nextUrl.searchParams.get('view')||'index';
if(view==='index'){const q='%'+cleanText(req.nextUrl.searchParams.get('q'),200)+'%';const accounts=(await db.prepare("SELECT a.owner,a.status,COALESCE(NULLIF(s.company,''),u.name,'Unnamed company') AS name FROM platform_accounts a LEFT JOIN settings s ON s.owner=a.owner LEFT JOIN platform_users u ON u.id=a.owner WHERE COALESCE(s.company,'') LIKE ? OR COALESCE(u.name,'') LIKE ? OR a.owner LIKE ? ORDER BY a.created DESC LIMIT 100").bind(q,q,q).all()).results;return json({accounts,role,operators:role==='owner'?(await db.prepare('SELECT email,role,active,version,updated FROM platform_operators ORDER BY email').all()).results:[],protectedOwners:role==='owner'?operatorEmails():[]})}
if(view==='preview'){const session=await db.prepare('SELECT * FROM support_sessions WHERE id=? AND actor=? AND expires>?').bind(cleanText(req.nextUrl.searchParams.get('session'),100),user.email,new Date().toISOString()).first<any>();if(!session)return json({error:'Support session expired or ended.'},403);const target=await db.prepare('SELECT * FROM platform_users WHERE id=? AND owner=?').bind(session.user_id,session.owner).first<any>();if(!target)return json({error:'User no longer belongs to this company.'},404);const access=await getCompanyAccess({userId:target.id,email:target.email,fullName:target.name,displayName:target.name},false);if(access.owner!==session.owner)return json({error:'Company membership changed.'},409);const projects=(await db.prepare('SELECT id,name,status,number FROM projects WHERE owner=? ORDER BY created DESC LIMIT 100').bind(session.owner).all()).results;const rows=(await db.prepare('SELECT kind,COUNT(*) AS count FROM records WHERE owner=? GROUP BY kind').bind(session.owner).all<any>()).results.filter(r=>canAccess(access,recordTab(r.kind))&&!(role==='support'&&['cost','variation','purchase-order'].includes(r.kind)));const files=(await db.prepare('SELECT category,COUNT(*) AS count FROM files WHERE owner=? GROUP BY category').bind(session.owner).all<any>()).results.filter(r=>canAccess(access,fileTab(r.category)));await logAdmin(user.email,'support-preview',session.owner,{target:target.id,session:session.id});return json({expires:session.expires,user:{name:target.name,email:target.email},blocked:access.blocked,projects:access.blocked?[]:projects,records:access.blocked?[]:rows,files:access.blocked?[]:files,readOnly:true})}
if(!owner||!await known(owner))return json({error:'Company not found.'},404);
if(view==='conversation'){const ticket=await db.prepare('SELECT id FROM feedback WHERE id=? AND owner=?').bind(cleanText(req.nextUrl.searchParams.get('ticketId'),100),owner).first<any>();if(!ticket)return json({error:'Ticket not found.'},404);return json({items:(await db.prepare('SELECT * FROM customer_messages WHERE owner=? AND ticket_id=? ORDER BY created DESC LIMIT 100').bind(owner,ticket.id).all()).results.reverse()})}
if(view==='detail'){const d=await detail(owner);if(role==='support'){d.history=d.history.filter((h:any)=>['notice','ticket-reply','invite-renew','invite-revoke','support-start','support-preview','support-end'].includes(h.action));return json({tickets:d.tickets,company:d.company,users:d.users,members:d.members,history:d.history,messages:d.messages,role})}return json({...d,role,protected:await protectedCompany(owner)})}
if(view==='timeline'){const events=(await db.prepare("SELECT 'First recorded' AS kind,created AS time FROM platform_accounts WHERE owner=? UNION ALL SELECT 'Package requested',requested_at FROM subscriptions WHERE owner=? AND requested_at IS NOT NULL UNION ALL SELECT 'Feedback: '||subject,created FROM feedback WHERE owner=? ORDER BY time DESC LIMIT 100").bind(owner,owner,owner).all()).results;return json({events})}
if(role!=='owner')return json({error:'Platform owner access required.'},403);
if(view==='export'){const payload:any={companyId:owner,exportedAt:new Date().toISOString(),format:'PLAN.FLO company records and file manifest',tables:{}};for(const table of exportTables){const result=await db.prepare(`SELECT * FROM ${table} WHERE owner=? LIMIT 10001`).bind(owner).all();if(result.results.length>10000)return json({error:'This company exceeds the interactive export limit. Arrange a complete managed export before deleting.'},413);payload.tables[table]=result.results;}payload.tables.company_members=(await db.prepare('SELECT id,email,name,user_id,role,seat_type,permissions,status,created FROM company_members WHERE owner=?').bind(owner).all()).results;payload.tables.plan_revisions=(await db.prepare('SELECT r.* FROM plan_revisions r JOIN files f ON f.id=r.file_id WHERE f.owner=?').bind(owner).all()).results;payload.tables.feedback=(await db.prepare('SELECT id,sender_name,sender_email,type,impact,subject,message,status,created,updated FROM feedback WHERE owner=?').bind(owner).all()).results;payload.fileDownloads=[...payload.tables.files.map((f:any)=>({name:f.name,id:f.id})),...payload.tables.plan_revisions.map((r:any)=>({name:r.name,id:r.id}))].map(f=>({...f,url:req.nextUrl.origin+'/api/admin-controls?view=file&owner='+encodeURIComponent(owner)+'&id='+encodeURIComponent(f.id)}));await logAdmin(user.email,'data-export',owner,{tables:Object.keys(payload.tables)});return new Response(JSON.stringify(payload,null,2),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="planflo-company-export.json"','Cache-Control':'private, no-store'}})}
if(view==='file'){const id=cleanText(req.nextUrl.searchParams.get('id'),100);const f=await db.prepare('SELECT name,mime FROM files WHERE owner=? AND id=?').bind(owner,id).first<any>()||await db.prepare('SELECT r.name,r.mime FROM plan_revisions r JOIN files f ON f.id=r.file_id WHERE f.owner=? AND r.id=?').bind(owner,id).first<any>();if(!f)return json({error:'File not found.'},404);const object=await (env as any).FILES.get(owner+'/'+id);if(!object)return json({error:'Stored file unavailable.'},404);await logAdmin(user.email,'file-export',owner,{id});return new Response(object.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(f.name),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}
return json({error:'Unknown view'},400);
}catch(e){console.error('Account controls',e);return json({error:'Could not load account controls.'},500)}}
export async function POST(req:NextRequest){try{const c=await context();if(!c||c.role==='billing')return json({error:'Platform access required.'},403);if(req.headers.get('origin')!==req.nextUrl.origin)return json({error:'Invalid request origin.'},403);const b:any=await req.json(),{user,role,db}=c,owner=cleanText(b.owner,200),now=new Date().toISOString(),reason=cleanText(b.reason,1000);if(role!=='owner'&&!['notice','ticket-reply','invite-renew','invite-revoke','support-start','support-end'].includes(b.action))return json({error:'Platform owner access required.'},403);
if(b.action==='operator'){const email=cleanText(b.email,254).toLowerCase();if(!validEmail(email)||!['support','billing'].includes(b.role)||typeof b.active!=='boolean')return json({error:'Choose a valid email and role.'},400);if(operatorEmails().includes(email)||email===user.email.toLowerCase())return json({error:'Protected platform owner access cannot be changed here.'},400);const previous=await db.prepare('SELECT version FROM platform_operators WHERE email=?').bind(email).first<any>();if((previous?.version||0)!==b.version)return json({error:'Operator changed. Refresh first.'},409);const result=await db.prepare('INSERT INTO platform_operators(email,role,active,updated) VALUES(?,?,?,?) ON CONFLICT(email) DO UPDATE SET role=excluded.role,active=excluded.active,updated=excluded.updated,version=platform_operators.version+1 WHERE platform_operators.version=?').bind(email,b.role,b.active?1:0,now,b.version).run();if(!result.meta.changes)return json({error:'Operator changed. Refresh first.'},409);await logAdmin(user.email,'operator-access','',{email,role:b.role,active:b.active});return json({ok:true})}
if(b.action==='support-end'){const session=await db.prepare('SELECT owner FROM support_sessions WHERE id=? AND actor=?').bind(cleanText(b.session,100),user.email).first<any>();await db.prepare('DELETE FROM support_sessions WHERE id=? AND actor=?').bind(cleanText(b.session,100),user.email).run();if(session)await logAdmin(user.email,'support-end',session.owner,{});return json({ok:true})}
const account=await known(owner);if(!account)return json({error:'Company not found.'},404);
if(b.action==='limits'){if(typeof b.enabled!=='boolean'||b.expires&&!Number.isFinite(Date.parse(b.expires)))return json({error:'Choose valid settings and an expiry date.'},400);if(reason.length<5)return json({error:'Add a reason.'},400);for(const key of ['projects','office','field','bytes'])if(!Number.isSafeInteger(b[key])||b[key]<0||b[key]>1e15)return json({error:'Use valid non-negative limits.'},400);if(b.office<1)return json({error:'Allow at least one office user for the owner.'},400);const overrides=b.overrides||{};for(const key of ['projects','office','field','bytes'])if(overrides[key]!=null&&(!Number.isSafeInteger(overrides[key])||overrides[key]<b[key]||overrides[key]>1e15))return json({error:'Temporary limits must be at least the base limit.'},400);const expires=b.expires?new Date(b.expires).toISOString():null;if(Object.values(overrides).some(v=>v!=null)&&(!expires||expires<=now||Date.parse(expires)>Date.now()+366*86400000))return json({error:'Set an override expiry within the next year.'},400);const old=await db.prepare('SELECT version FROM account_limits WHERE owner=?').bind(owner).first<any>();if((old?.version||0)!==b.version)return json({error:'Limits changed. Refresh first.'},409);const r=await db.prepare('INSERT INTO account_limits(owner,enabled,plan,projects,office,field,bytes,override_projects,override_office,override_field,override_bytes,expires,reason) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(owner) DO UPDATE SET enabled=excluded.enabled,plan=excluded.plan,projects=excluded.projects,office=excluded.office,field=excluded.field,bytes=excluded.bytes,override_projects=excluded.override_projects,override_office=excluded.override_office,override_field=excluded.override_field,override_bytes=excluded.override_bytes,expires=excluded.expires,reason=excluded.reason,version=account_limits.version+1 WHERE account_limits.version=?').bind(owner,b.enabled?1:0,cleanText(b.plan,80),b.projects,b.office,b.field,b.bytes,overrides.projects??null,overrides.office??null,overrides.field??null,overrides.bytes??null,expires,reason,b.version).run();if(!r.meta.changes)return json({error:'Limits changed. Refresh first.'},409);await logAdmin(user.email,'limits',owner,{enabled:!!b.enabled,plan:b.plan,projects:b.projects,office:b.office,field:b.field,bytes:b.bytes,overrides,expires,reason});return json({ok:true})}
if(['notice','ticket-reply'].includes(b.action)){const body=cleanText(b.body,5000),subject=cleanText(b.subject,160);if(!body||!subject)return json({error:'Enter a subject and message.'},400);let recipient='',ticketId='';if(b.action==='ticket-reply'){const ticket=await db.prepare('SELECT id,sender_id FROM feedback WHERE id=? AND owner=?').bind(cleanText(b.ticketId,100),owner).first<any>();if(!ticket)return json({error:'Ticket not found in this company.'},404);recipient=ticket.sender_id;ticketId=ticket.id;}const id=cleanText(b.id,100);if(!/^[0-9a-f-]{36}$/.test(id))return json({error:'Invalid message request.'},400);const r=await db.prepare('INSERT INTO customer_messages(id,owner,recipient,ticket_id,subject,body,author,created) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,owner,recipient,ticketId,subject,body,user.email,now).run();if(r.meta.changes)await logAdmin(user.email,b.action,owner,{id,subject,ticketId,delivery:'in-app'});return json({ok:true})}
if(['invite-renew','invite-revoke'].includes(b.action)){const m=await db.prepare('SELECT * FROM company_members WHERE id=? AND owner=?').bind(cleanText(b.id,100),owner).first<any>();if(!m||m.user_id)return json({error:'Choose a pending or disabled invitation that has not been accepted.'},400);if(account.status!=='Active')return json({error:'Reactivate the company before managing invitations.'},400);const token=crypto.randomUUID()+crypto.randomUUID(),expires=new Date(Date.now()+7*86400000).toISOString();await db.prepare('UPDATE company_members SET status=?,token_hash=?,expires=? WHERE id=? AND owner=? AND user_id IS NULL').bind(b.action==='invite-renew'?'pending':'disabled',b.action==='invite-renew'?await hashInvite(token):null,b.action==='invite-renew'?expires:null,m.id,owner).run();await logAdmin(user.email,b.action,owner,{member:m.id,email:m.email});return json({ok:true,url:b.action==='invite-renew'?req.nextUrl.origin+'/?invite='+encodeURIComponent(token):null})}
if(b.action==='support-start'){if(reason.length<5)return json({error:'Enter a reason for support access.'},400);const target=await db.prepare('SELECT id FROM platform_users WHERE id=? AND owner=?').bind(cleanText(b.userId,200),owner).first();if(!target)return json({error:'Choose a recorded user in this company.'},400);const id=crypto.randomUUID(),expires=new Date(Date.now()+15*60000).toISOString();await db.prepare('INSERT INTO support_sessions(id,actor,owner,user_id,reason,expires,created) VALUES(?,?,?,?,?,?,?)').bind(id,user.email,owner,b.userId,reason,expires,now).run();await logAdmin(user.email,'support-start',owner,{userId:b.userId,reason,expires});return json({id,expires})}
if(['delete-request','delete-cancel','delete-purge'].includes(b.action)){if(await protectedCompany(owner))return json({error:'An operator company cannot be deleted here.'},400);const old=await db.prepare('SELECT * FROM deletion_requests WHERE owner=?').bind(owner).first<any>();const company=await db.prepare('SELECT company FROM settings WHERE owner=?').bind(owner).first<any>();if(b.action==='delete-cancel'){if(!old||old.status!=='Requested')return json({error:'No pending deletion request.'},400);await db.prepare("UPDATE deletion_requests SET status='Cancelled',version=version+1 WHERE owner=? AND status='Requested'").bind(owner).run();await logAdmin(user.email,b.action,owner,{});return json({ok:true})}if(b.confirmation!=='DELETE '+(company?.company||owner))return json({error:'Type the exact deletion confirmation.'},400);if(b.action==='delete-request'){if(reason.length<5)return json({error:'Enter the deletion reason.'},400);if(old?.status==='Purged')return json({error:'Data already deleted.'},400);if(['Requested','Purging'].includes(old?.status))return json({error:'A deletion request is already pending.'},409);await db.batch([db.prepare("INSERT INTO deletion_requests(owner,status,reason,requested,eligible,actor) VALUES(?,'Requested',?,?,?,?) ON CONFLICT(owner) DO UPDATE SET status='Requested',reason=excluded.reason,requested=excluded.requested,eligible=excluded.eligible,actor=excluded.actor,version=deletion_requests.version+1").bind(owner,reason,now,new Date(Date.now()+30*86400000).toISOString(),user.email),db.prepare("UPDATE platform_accounts SET status='Closed',reason='Deletion requested',version=version+1,updated=? WHERE owner=?").bind(now,owner)]);await logAdmin(user.email,b.action,owner,{eligible:new Date(Date.now()+30*86400000).toISOString()});return json({ok:true})}
if(!old||!['Requested','Purging'].includes(old.status)||old.eligible>now||account.status!=='Closed')return json({error:'Deletion requires a closed account and the completed 30-day review period.'},400);if(await db.prepare('SELECT owner FROM billing_accounts WHERE owner=?').bind(owner).first())return json({error:'This account has a Stripe customer link. Billing and retention must be reviewed before a managed deletion; automated purge is unavailable.'},409);
const claimed=await db.prepare("UPDATE deletion_requests SET status='Purging',version=version+1 WHERE owner=? AND status IN ('Requested','Purging') AND version=?").bind(owner,old.version).run();if(!claimed.meta.changes)return json({error:'Deletion changed elsewhere. Refresh before continuing.'},409);
// Keep the account blocked throughout; R2 removal is repeatable if interrupted.
let cursor:string|undefined;do{const list=await (env as any).FILES.list({prefix:owner+'/',cursor,limit:1000});if(list.objects.length)await (env as any).FILES.delete(list.objects.map((o:any)=>o.key));cursor=list.truncated?list.cursor:undefined}while(cursor);
const commands=[db.prepare('DELETE FROM plan_revisions WHERE file_id IN (SELECT id FROM files WHERE owner=?)').bind(owner),db.prepare('DELETE FROM support_notes WHERE feedback_id IN (SELECT id FROM feedback WHERE owner=?)').bind(owner),db.prepare('DELETE FROM support_tickets WHERE feedback_id IN (SELECT id FROM feedback WHERE owner=?)').bind(owner),db.prepare('DELETE FROM message_reads WHERE message_id IN (SELECT id FROM customer_messages WHERE owner=?)').bind(owner),...([...exportTables,'company_members','feedback','review_decisions','review_activity','platform_usage','platform_users','upload_outcomes','account_limits','support_sessions'] as string[]).map(table=>db.prepare(`DELETE FROM ${table} WHERE owner=?`).bind(owner)),db.prepare("UPDATE platform_audit SET detail='{}',actor='redacted' WHERE owner=?").bind(owner),db.prepare("UPDATE platform_accounts SET notes='',reason='Data purged',version=version+1 WHERE owner=?").bind(owner),db.prepare("UPDATE deletion_requests SET status='Purged',reason='',version=version+1 WHERE owner=?").bind(owner)];await db.batch(commands);await logAdmin(user.email,'data-purged',owner,{note:'Minimal deletion and access-blocking record retained; provider backups are outside this operation.'});return json({ok:true})}
return json({error:'Unknown action.'},400);
}catch(e){console.error('Account control update',e);return json({error:limitMessage(e)||'Could not save this change. Refresh and try again.'},limitMessage(e)?409:500)}}
