import {invalidMutationOrigin} from '@/app/request-origin';
import {canAccessProject} from '@/app/project-access';
import {canAccessInvoice,invoiceScope} from '@/app/invoice-access';
import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess} from '@/app/company-access';
import {canAccess} from '@/app/permissions';
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
async function context(edit=false){const user=await getChatGPTUser();if(!user)return null;const access=await getCompanyAccess(user);return canAccess(access,'Costs',edit)?{user,access,db:companyDb()}:null;}
export async function GET(req:NextRequest){const c=await context();if(!c)return fail('You do not have access to project expenses.',403);try{const project=req.nextUrl.searchParams.get('project')||'',id=req.nextUrl.searchParams.get('id')||'',history=req.nextUrl.searchParams.get('history')==='1',offset=Math.max(0,Math.min(1000000,Math.floor(Number(req.nextUrl.searchParams.get('offset'))||0)));const scope=invoiceScope(c.access);if(project&&(!canAccessProject(c.access,project)||!await c.db.prepare('SELECT id FROM projects WHERE id=? AND owner=?').bind(project,c.access.owner).first()))return fail('Project unavailable.',404);
 const projects=(await c.db.prepare('SELECT id,name,status FROM projects WHERE owner=? ORDER BY name').bind(c.access.owner).all<{id:string}>()).results.filter(p=>canAccessProject(c.access,p.id));
 if(id){const r:any=await c.db.prepare('SELECT * FROM supplier_invoices WHERE id=? AND owner=?').bind(id,c.access.owner).first();if(!r||!canAccessInvoice(c.access,r.project_id))return fail('Invoice unavailable.',404);return NextResponse.json({invoice:{...r,data:JSON.parse(r.data)},projects,editable:canAccess(c.access,'Costs',true)});}
 const rows=(await c.db.prepare(`SELECT i.*,p.name AS projectName FROM supplier_invoices i LEFT JOIN projects p ON p.id=i.project_id AND p.owner=i.owner WHERE i.owner=? AND (?='' OR i.project_id=?) AND (?=1 OR i.status IN ('Needs review','Unmatched')) AND ${scope.sql} ORDER BY i.created DESC LIMIT 51 OFFSET ?`).bind(c.access.owner,project,project,history?1:0,...scope.args,offset).all<any>()).results;
 return NextResponse.json({items:rows.slice(0,50).map(r=>{const {excerpt,...data}=JSON.parse(r.data);return {...r,data}}),hasMore:rows.length>50,projects,editable:canAccess(c.access,'Costs',true)});
 }catch{return fail('Could not load supplier invoices.',503);}}
export async function POST(req:NextRequest){if(invalidMutationOrigin(req))return fail('Invalid request origin.',403);const c=await context(true);if(!c)return fail('Expense edit permission is required.',403);try{const b:any=await req.json();const old:any=await c.db.prepare('SELECT * FROM supplier_invoices WHERE id=? AND owner=?').bind(String(b.id||''),c.access.owner).first();if(!old||!canAccessInvoice(c.access,old.project_id))return fail('Invoice unavailable.',404);if(!['Needs review','Unmatched'].includes(old.status)||b.version!==old.version)return fail('This invoice changed or has already been reviewed. Reopen it.',409);const now=new Date().toISOString(),actor=c.user.fullName||c.user.email;
 if(b.action==='ignore'){const result=await c.db.prepare("UPDATE supplier_invoices SET status='Ignored',reviewed_by=?,reviewed_at=?,version=version+1 WHERE id=? AND owner=? AND version=? AND status IN ('Needs review','Unmatched')").bind(actor,now,old.id,c.access.owner,old.version).run();if(!result.meta.changes)return fail('Invoice changed. Reopen it.',409);return NextResponse.json({ok:true});}
 if(!['approve','assign'].includes(b.action))return fail('Choose an invoice review action.');const p:any=await c.db.prepare('SELECT id,status FROM projects WHERE id=? AND owner=?').bind(String(b.projectId||''),c.access.owner).first();if(!p||!canAccessProject(c.access,p.id))return fail('Choose an available project from your company.');if(p.status==='Archived')return fail('Restore the project before assigning an invoice.');const data=JSON.parse(old.data);if(old.file_id&&!await c.db.prepare("SELECT id FROM files WHERE id=? AND owner=? AND project_id=? AND category='invoice' AND archived=0").bind(old.file_id,c.access.owner,old.project_id).first())return fail('Invoice attachment unavailable.',409);
 if(b.action==='assign'){const results=await c.db.batch([c.db.prepare("UPDATE supplier_invoices SET project_id=?,status='Needs review',match_reason='Project selected by reviewer',version=version+1 WHERE id=? AND owner=? AND version=? AND status IN ('Needs review','Unmatched')").bind(p.id,old.id,c.access.owner,old.version),c.db.prepare("UPDATE files SET project_id=? WHERE id=? AND owner=? AND category='invoice' AND EXISTS(SELECT 1 FROM supplier_invoices WHERE id=? AND owner=? AND project_id=? AND version=?)").bind(p.id,old.file_id,c.access.owner,old.id,c.access.owner,p.id,old.version+1)]);if(!results[0].meta.changes)return fail('Invoice changed. Reopen it.',409);return NextResponse.json({ok:true});}
 const amount=Number(b.amount),supplier=String(b.supplier||'').trim().slice(0,300),date=String(b.date||'');if(b.confirmed!==true)return fail('Confirm the invoice details before adding the expense.');if(data.duplicateOf&&b.duplicateConfirmed!==true)return fail('Confirm this is a separate expense despite the duplicate warning.');if(b.amount===''||b.amount==null||!Number.isFinite(amount)||amount<0||amount>1e9||!supplier||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)return fail('Enter a supplier, valid invoice date and amount excluding GST in AUD.');
 const invoiceNumber=String(b.invoiceNumber||'').trim().slice(0,100),costId='invoice-'+old.id;const updated={...data,amount:Math.round(amount*100)/100,supplier,invoiceNumber,invoiceDate:date,currency:'AUD',duplicateConfirmed:!!b.duplicateConfirmed};const costData={amount:updated.amount,date,supplier,category:'Materials',invoiceNumber,purchaseOrderReference:data.references?.join(', ')||'',sourceInvoiceId:old.id,fileId:old.file_id,reviewedBy:actor,reviewedAt:now};
 const results=await c.db.batch([c.db.prepare("INSERT INTO records(id,owner,project_id,kind,title,status,data,created) SELECT ?,owner,?,'cost',?,'Approved',?,? FROM supplier_invoices WHERE id=? AND owner=? AND version=? AND status IN ('Needs review','Unmatched')").bind(costId,p.id,`Invoice ${invoiceNumber||old.id.slice(0,8)} - ${supplier}`,JSON.stringify(costData),now,old.id,c.access.owner,old.version),c.db.prepare("UPDATE supplier_invoices SET project_id=?,status='Approved',data=?,reviewed_by=?,reviewed_at=?,version=version+1 WHERE id=? AND owner=? AND version=? AND status IN ('Needs review','Unmatched')").bind(p.id,JSON.stringify(updated),actor,now,old.id,c.access.owner,old.version),c.db.prepare("UPDATE files SET project_id=? WHERE id=? AND owner=? AND category='invoice' AND EXISTS(SELECT 1 FROM supplier_invoices WHERE id=? AND owner=? AND project_id=? AND version=? AND status='Approved')").bind(p.id,old.file_id,c.access.owner,old.id,c.access.owner,p.id,old.version+1)]);if(!results[0].meta.changes)return fail('Invoice changed. Reopen it.',409);return NextResponse.json({ok:true,costId});
 }catch{return fail('Could not save the invoice review. Refresh and try again.',500);}}
