import {limitMessage} from '@/app/account-limits';
import {operatorRole,allOperatorEmails,canRead,protectedCompany} from '@/app/operator-access';
import {billingList,billingDetail} from '@/app/platform-billing';
import {analytics} from '@/app/platform-analytics';
import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {getCompanyAccess} from '@/app/company-access';
import {platformDb,isPlatformAdmin,operatorEmails} from '@/app/platform-store';
import {accountStatuses,userStatuses,ticketStatuses,ticketPriorities,ticketCategories,ticketDefaults,cleanText,validEmail} from '@/app/platform-model';
import {normalisePermissions,permissionTabs} from '@/app/permissions';
import {fieldUserTabs} from '@/app/subscription-plans';
const json=(v:unknown,status=200)=>NextResponse.json(v,{status,headers:{'Cache-Control':'private, no-store'}});
const owners=`WITH owners AS (SELECT owner FROM platform_accounts UNION SELECT owner FROM settings UNION SELECT owner FROM projects UNION SELECT owner FROM company_members UNION SELECT owner FROM (SELECT owner FROM feedback UNION SELECT owner FROM subscriptions))`;
async function context(){const u=await getChatGPTUser();const role=u?await operatorRole(u):null;if(!u||!role)return null;await getCompanyAccess(u);return {u,db:platformDb(),role};}
async function known(owner:string){return platformDb().prepare(owners+' SELECT owner FROM owners WHERE owner=?').bind(owner).first();}
function page(req:NextRequest){const n=Number(req.nextUrl.searchParams.get('offset')||0);return Number.isInteger(n)&&n>=0&&n<=100000?n:0;}
function audit(actor:string,action:string,target:string,owner:string,detail:unknown,now:string,conditional=false){return platformDb().prepare(`INSERT INTO platform_audit(id,actor,action,target,owner,detail,created) SELECT ?,?,?,?,?,?,? ${conditional?'WHERE changes()>0':''}`).bind(crypto.randomUUID(),actor,action,target,owner,JSON.stringify(detail),now);}
const protectedAccount=protectedCompany;
export async function GET(req:NextRequest){try{const c=await context();if(!c)return json({error:'PLAN.FLO platform administrator access is required.'},403);const {db}=c,view=req.nextUrl.searchParams.get('view')||'overview',offset=page(req),q=cleanText(req.nextUrl.searchParams.get('q'),200),like='%'+q+'%';
if(!canRead(c.role,view))return json({error:'Your platform role cannot access this section.'},403);
if(view==='billing')return json(await billingList(q,offset));
if(view==='billing-account'){const status=req.nextUrl.searchParams.get('status')||'all',after=req.nextUrl.searchParams.get('after')||'';if(!['all','draft','open','paid','void','uncollectible'].includes(status)||after&&!/^in_[A-Za-z0-9]+$/.test(after))return json({error:'Choose a valid invoice filter or page.'},400);try{const detail=await billingDetail(cleanText(req.nextUrl.searchParams.get('owner'),200),status,after);return detail?json(detail):json({error:'Billing account not found.'},404)}catch{return json({error:'Stripe billing could not be loaded. Check the connection and try again.'},502)}}
if(view==='analytics')return json(await analytics());
if(view==='overview'){const [counts,activity,sections,plans,recent]=await Promise.all([
 db.prepare(owners+` SELECT (SELECT COUNT(*) FROM owners) AS accounts,(SELECT COUNT(*) FROM platform_accounts WHERE status='Suspended') AS suspended,(SELECT COUNT(*) FROM platform_accounts WHERE status='Closed') AS closed,(SELECT COUNT(*) FROM platform_users) AS users,(SELECT COUNT(*) FROM platform_users WHERE last_seen>=strftime('%Y-%m-%dT%H:%M:%fZ','now','-30 days')) AS activeUsers,(SELECT COUNT(*) FROM projects) AS projects,(SELECT COUNT(*) FROM files) AS files,(SELECT COUNT(*) FROM feedback WHERE status NOT IN ('Resolved','Closed')) AS openTickets,(SELECT MIN(first_seen) FROM platform_users) AS trackingStarted`).first(),
 db.prepare("SELECT day,COUNT(DISTINCT user_id) AS users,SUM(views) AS views FROM platform_usage WHERE day>=date('now','-29 days') GROUP BY day ORDER BY day").all(),
 db.prepare("SELECT section,SUM(views) AS views,COUNT(DISTINCT user_id) AS users FROM platform_usage WHERE day>=date('now','-29 days') GROUP BY section ORDER BY views DESC LIMIT 10").all(),
 db.prepare("SELECT COALESCE(requested_plan,'Not selected') AS plan,COUNT(*) AS count FROM subscriptions GROUP BY COALESCE(requested_plan,'Not selected')").all(),
 db.prepare('SELECT actor,action,detail,created FROM platform_audit ORDER BY created DESC LIMIT 8').all()
]);return json({counts,activity:activity.results,sections:sections.results,plans:plans.results,recent:recent.results,operator:c.u.email});}
if(view==='accounts'){const status=req.nextUrl.searchParams.get('status')||'All';if(status!=='All'&&!accountStatuses.includes(status as any))return json({error:'Invalid account status.'},400);const rows=await db.prepare(owners+` SELECT o.owner,COALESCE(NULLIF(s.company,''),NULLIF(u.name,''),'Unnamed company') AS name,u.email,COALESCE(a.status,'Active') AS status,a.created,a.version,sub.requested_plan AS requestedPlan,sub.plan,sub.status AS billingStatus,(SELECT COUNT(*) FROM projects p WHERE p.owner=o.owner) AS projects,(SELECT COUNT(*) FROM company_members m WHERE m.owner=o.owner AND m.status<>'disabled') AS members,(SELECT MAX(last_seen) FROM platform_users pu WHERE pu.owner=o.owner) AS lastSeen FROM owners o LEFT JOIN settings s ON s.owner=o.owner LEFT JOIN platform_accounts a ON a.owner=o.owner LEFT JOIN platform_users u ON u.id=o.owner LEFT JOIN subscriptions sub ON sub.owner=o.owner WHERE (COALESCE(s.company,'') LIKE ? OR COALESCE(u.email,'') LIKE ? OR COALESCE(u.name,'') LIKE ?) AND (?='All' OR COALESCE(a.status,'Active')=?) ORDER BY COALESCE(a.created,'') DESC,o.owner LIMIT 51 OFFSET ?`).bind(like,like,like,status,status,offset).all();return json({items:rows.results.slice(0,50),hasMore:rows.results.length>50});}
if(view==='account'){const owner=cleanText(req.nextUrl.searchParams.get('owner'),200);if(!await known(owner))return json({error:'Account not found.'},404);const [account,company,users,members,subscription,counts,history,activity]=await Promise.all([
 db.prepare('SELECT * FROM platform_accounts WHERE owner=?').bind(owner).first(),db.prepare('SELECT company,abn,email,phone,address FROM settings WHERE owner=?').bind(owner).first(),db.prepare('SELECT id,name,email,status,first_seen,last_seen,version FROM platform_users WHERE owner=? ORDER BY name').bind(owner).all(),db.prepare('SELECT id,name,email,user_id,role,seat_type,status,permissions,expires FROM company_members WHERE owner=? ORDER BY name').bind(owner).all(),db.prepare('SELECT plan,status,requested_plan,requested_at,requested_configuration FROM subscriptions WHERE owner=?').bind(owner).first(),db.prepare('SELECT (SELECT COUNT(*) FROM projects WHERE owner=?) AS projects,(SELECT COUNT(*) FROM records WHERE owner=?) AS records,(SELECT COUNT(*) FROM files WHERE owner=?) AS files,(SELECT COUNT(*) FROM feedback WHERE owner=?) AS tickets').bind(owner,owner,owner,owner).first(),db.prepare('SELECT actor,action,detail,created FROM platform_audit WHERE owner=? ORDER BY created DESC LIMIT 30').bind(owner).all(),db.prepare("SELECT day,SUM(views) AS views,COUNT(DISTINCT user_id) AS users FROM platform_usage WHERE owner=? AND day>=date('now','-29 days') GROUP BY day ORDER BY day").bind(owner).all()
]);return json({account:account||{owner,status:'Active',reason:'',notes:'',version:0,created:null},company:company||{},users:users.results,members:members.results,subscription,counts,history:history.results,activity:activity.results,protected:owner===c.u.userId||await protectedAccount(owner),permissionTabs,operators:await allOperatorEmails()});}
if(view==='users'){const rows=await db.prepare(`SELECT u.id,u.owner,u.name,u.email,u.status,u.first_seen,u.last_seen,u.version,COALESCE(s.company,'Unnamed company') AS company,COALESCE(a.status,'Active') AS accountStatus,CASE WHEN u.id=u.owner THEN 'Owner' ELSE COALESCE(m.role,'Member') END AS role FROM platform_users u LEFT JOIN settings s ON s.owner=u.owner LEFT JOIN platform_accounts a ON a.owner=u.owner LEFT JOIN company_members m ON m.user_id=u.id WHERE u.name LIKE ? OR u.email LIKE ? OR s.company LIKE ? ORDER BY u.last_seen DESC LIMIT 51 OFFSET ?`).bind(like,like,like,offset).all();return json({items:rows.results.slice(0,50),hasMore:rows.results.length>50});}
if(view==='tickets'){const status=req.nextUrl.searchParams.get('status')||'All',priority=req.nextUrl.searchParams.get('priority')||'All';if(status!=='All'&&!ticketStatuses.includes(status as any)||priority!=='All'&&!ticketPriorities.includes(priority as any))return json({error:'Choose a valid ticket filter.'},400);const rows=await db.prepare(`SELECT f.*,COALESCE(s.company,'Unnamed company') AS company,t.category,COALESCE(t.priority,CASE f.impact WHEN 'Blocking work' THEN 'Urgent' WHEN 'Slowing work' THEN 'High' ELSE 'Normal' END) AS priority,t.assignee,(SELECT COUNT(*) FROM support_notes n WHERE n.feedback_id=f.id) AS noteCount FROM feedback f LEFT JOIN settings s ON s.owner=f.owner LEFT JOIN support_tickets t ON t.feedback_id=f.id WHERE (?='All' OR f.status=?) AND (?='All' OR COALESCE(t.priority,CASE f.impact WHEN 'Blocking work' THEN 'Urgent' WHEN 'Slowing work' THEN 'High' ELSE 'Normal' END)=?) AND (f.subject LIKE ? OR f.message LIKE ? OR f.sender_email LIKE ? OR COALESCE(s.company,'') LIKE ?) ORDER BY CASE COALESCE(t.priority,CASE f.impact WHEN 'Blocking work' THEN 'Urgent' WHEN 'Slowing work' THEN 'High' ELSE 'Normal' END) WHEN 'Urgent' THEN 0 WHEN 'High' THEN 1 WHEN 'Normal' THEN 2 ELSE 3 END,f.created DESC LIMIT 51 OFFSET ?`).bind(status,status,priority,priority,like,like,like,like,offset).all<any>();return json({items:rows.results.slice(0,50).map(r=>({...r,category:r.category||ticketDefaults(r.type,r.impact).category,assignee:r.assignee||''})),hasMore:rows.results.length>50,operators:await allOperatorEmails()});}
if(view==='ticket'){const id=cleanText(req.nextUrl.searchParams.get('id'),100);const ticket=await db.prepare('SELECT f.*,s.company,t.category,t.priority,t.assignee,t.topic FROM feedback f LEFT JOIN settings s ON s.owner=f.owner LEFT JOIN support_tickets t ON t.feedback_id=f.id WHERE f.id=?').bind(id).first<any>();if(!ticket)return json({error:'Ticket not found.'},404);return json({ticket:{...ticket,category:ticket.category||ticketDefaults(ticket.type,ticket.impact).category,priority:ticket.priority||ticketDefaults(ticket.type,ticket.impact).priority,assignee:ticket.assignee||''},notes:(await db.prepare('SELECT id,author,body,created FROM support_notes WHERE feedback_id=? ORDER BY created').bind(id).all()).results,operators:await allOperatorEmails()});}
if(view==='audit'){const rows=await db.prepare('SELECT * FROM platform_audit WHERE actor LIKE ? OR action LIKE ? OR target LIKE ? ORDER BY created DESC LIMIT 51 OFFSET ?').bind(like,like,like,offset).all();return json({items:rows.results.slice(0,50),hasMore:rows.results.length>50});}
return json({error:'Unknown admin view.'},400);
}catch(e){console.error('Platform admin read',e);return json({error:'Could not load platform administration. Please retry.'},500);}}
export async function POST(req:NextRequest){try{const c=await context();if(!c)return json({error:'PLAN.FLO platform administrator access is required.'},403);if(req.headers.get('origin')!==req.nextUrl.origin)return json({error:'Invalid request origin.'},403);const b:any=await req.json(),{db,u}=c,now=new Date().toISOString(),owner=cleanText(b.owner,200),reason=cleanText(b.reason,1000);if(c.role!=='owner'&&!(c.role==='support'&&b.action==='ticket'))return json({error:'Your platform role cannot perform this action.'},403);if(['account-status','account-profile','account-notes','member'].includes(b.action)&&!await known(owner))return json({error:'Account not found.'},404);
if(['account-status','account-profile','account-notes'].includes(b.action)){const a:any=await db.prepare('SELECT * FROM platform_accounts WHERE owner=?').bind(owner).first();const version=a?.version||0;if(b.version!==version)return json({error:'This account changed. Refresh before saving.'},409);let status=a?.status||'Active',notes=a?.notes||'',changeReason=a?.reason||'',detail:any={};if(b.action==='account-status'){if(b.status==='Active'&&await db.prepare("SELECT owner FROM deletion_requests WHERE owner=? AND status IN ('Requested','Purging','Purged')").bind(owner).first())return json({error:'Cancel the pending deletion first. Purged accounts cannot be reactivated.'},409);if(!accountStatuses.includes(b.status))return json({error:'Choose an account status.'},400);if(owner===u.userId||await protectedAccount(owner))return json({error:'The platform administrator’s company cannot be suspended or closed here.'},400);if(reason.length<5)return json({error:'Add a reason for this account change.'},400);status=b.status;changeReason=reason;detail={before:a?.status||'Active',after:status,reason,billing:'No Stripe billing change'};}if(b.action==='account-notes'){notes=cleanText(b.notes,10000);detail={note:'Internal account notes updated'};}let profile:any=null;if(b.action==='account-profile'){profile={company:cleanText(b.company,200),abn:cleanText(b.abn,80),email:cleanText(b.email,200),phone:cleanText(b.phone,80),address:cleanText(b.address,400)};if(!profile.company||profile.email&&!validEmail(profile.email))return json({error:'Enter a company name and valid contact email.'},400);detail={before:await db.prepare('SELECT company,abn,email,phone,address FROM settings WHERE owner=?').bind(owner).first(),after:profile};}
const update=db.prepare('INSERT INTO platform_accounts(owner,status,reason,notes,version,created,updated) VALUES(?,?,?,?,1,?,?) ON CONFLICT(owner) DO UPDATE SET status=excluded.status,reason=excluded.reason,notes=excluded.notes,version=platform_accounts.version+1,updated=excluded.updated WHERE platform_accounts.version=?').bind(owner,status,changeReason,notes,a?.created||now,now,version);
const commands=[update,audit(u.email,b.action,owner,owner,detail,now,true)];if(profile)commands.push(db.prepare('INSERT INTO settings(owner,company,abn,email,phone,address) SELECT ?,?,?,?,?,? WHERE changes()>0 ON CONFLICT(owner) DO UPDATE SET company=excluded.company,abn=excluded.abn,email=excluded.email,phone=excluded.phone,address=excluded.address').bind(owner,profile.company,profile.abn,profile.email,profile.phone,profile.address));const results=await db.batch(commands);if(!results[0].meta.changes)return json({error:'This account changed. Refresh before saving.'},409);return json({ok:true});}
if(b.action==='user-status'){if(!userStatuses.includes(b.status)||reason.length<5)return json({error:'Choose a user status and add a reason.'},400);const old=await db.prepare('SELECT * FROM platform_users WHERE id=?').bind(cleanText(b.id,200)).first<any>();if(!old)return json({error:'User not found.'},404);if(await operatorRole(old)||old.id===u.userId)return json({error:'Platform administrator access cannot be disabled here.'},400);const results=await db.batch([db.prepare('UPDATE platform_users SET status=?,version=version+1 WHERE id=? AND version=?').bind(b.status,old.id,b.version),audit(u.email,'user-status',old.id,old.owner,{email:old.email,before:old.status,after:b.status,reason},now,true)]);if(!results[0].meta.changes)return json({error:'This user changed. Refresh before saving.'},409);return json({ok:true});}
if(b.action==='member'){const m=await db.prepare('SELECT * FROM company_members WHERE id=? AND owner=?').bind(cleanText(b.id,200),owner).first<any>();if(!m)return json({error:'Team member not found.'},404);if(await operatorRole({email:m.email})||m.user_id===u.userId)return json({error:'Platform administrator membership cannot be changed here.'},400);if(!['active','pending','disabled'].includes(b.status)||!['admin','member'].includes(b.role)||!['office','field'].includes(b.seatType)||b.seatType==='field'&&b.role==='admin')return json({error:'Choose valid team settings.'},400);if(!m.user_id&&b.status==='active')return json({error:'This person must accept their invitation before activation.'},400);if(m.user_id&&b.status==='pending')return json({error:'Accepted users cannot be returned to pending.'},400);const previous=JSON.stringify({status:m.status,role:m.role,seatType:m.seat_type,permissions:m.permissions});if(b.previous!==previous)return json({error:'Team access changed. Refresh before saving.'},409);const perms=normalisePermissions(b.permissions);if(b.seatType==='field')for(const tab of Object.keys(perms))if(!fieldUserTabs.includes(tab))perms[tab]={view:false,edit:false};const result=await db.batch([db.prepare('UPDATE company_members SET role=?,seat_type=?,status=?,permissions=?,token_hash=CASE WHEN ?=\'disabled\' THEN NULL ELSE token_hash END,expires=CASE WHEN ?=\'disabled\' THEN NULL ELSE expires END WHERE id=? AND owner=? AND status=? AND role=? AND seat_type=? AND permissions=?').bind(b.role,b.seatType,b.status,JSON.stringify(perms),b.status,b.status,m.id,owner,m.status,m.role,m.seat_type,m.permissions),audit(u.email,'member-access',m.id,owner,{email:m.email,before:{role:m.role,status:m.status,seatType:m.seat_type,permissions:JSON.parse(m.permissions)},after:{role:b.role,status:b.status,seatType:b.seatType,permissions:perms}},now,true)]);if(!result[0].meta.changes)return json({error:'Team access changed. Refresh before saving.'},409);return json({ok:true});}
if(b.action==='ticket'){const f=await db.prepare('SELECT * FROM feedback WHERE id=?').bind(cleanText(b.id,100)).first<any>();if(!f)return json({error:'Ticket not found.'},404);if(!ticketStatuses.includes(b.status)||!ticketPriorities.includes(b.priority)||!ticketCategories.includes(b.category)||b.assignee&&!(await allOperatorEmails()).includes(b.assignee))return json({error:'Choose valid ticket details.'},400);if(b.version!==f.version)return json({error:'This ticket changed. Reload it before saving.'},409);const note=cleanText(b.note,5000);const commands=[db.prepare(`UPDATE feedback SET resolved_at=CASE WHEN ? IN ('Resolved','Closed') THEN COALESCE(resolved_at,?) ELSE NULL END,status=?,version=version+1,updated=? WHERE id=? AND version=?`).bind(b.status,now,b.status,now,f.id,b.version),audit(u.email,'ticket-update',f.id,f.owner,{before:f.status,after:b.status,category:b.category,priority:b.priority,assignee:b.assignee||'',noteAdded:!!note,topic:cleanText(b.topic,80)},now,true),db.prepare('INSERT INTO support_tickets(feedback_id,category,priority,assignee,updated,topic) SELECT ?,?,?,?,?,? WHERE changes()>0 ON CONFLICT(feedback_id) DO UPDATE SET category=excluded.category,priority=excluded.priority,assignee=excluded.assignee,updated=excluded.updated,version=support_tickets.version+1,topic=excluded.topic').bind(f.id,b.category,b.priority,b.assignee||'',now,cleanText(b.topic,80))];if(note)commands.push(db.prepare('INSERT INTO support_notes(id,feedback_id,author,body,created) SELECT ?,?,?,?,? WHERE changes()>0').bind(crypto.randomUUID(),f.id,u.email,note,now));const results=await db.batch(commands);if(!results[0].meta.changes)return json({error:'This ticket changed. Reload it before saving.'},409);return json({ok:true});}
return json({error:'Unknown admin action.'},400);
}catch(e){if(limitMessage(e))return json({error:limitMessage(e)},409);console.error('Platform admin save',e);return json({error:'Could not save this change. Please retry.'},500);}}
