import {NextRequest,NextResponse} from 'next/server';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {companyDb,getCompanyAccess} from '@/app/company-access';
import {canAccess} from '@/app/permissions';
import {equipmentTab,checkResults} from '@/app/equipment-model';
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
const text=(v:unknown,max=500)=>String(v??'').trim().slice(0,max);
const validDate=(v:string)=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(new Date(v+'T12:00:00Z').getTime())&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
export async function GET(req:NextRequest){try{const u=await getChatGPTUser();if(!u)return fail('Sign in required.',401);const a=await getCompanyAccess(u),kind=req.nextUrl.searchParams.get('kind')||'',projectId=req.nextUrl.searchParams.get('projectId')||'';if(!['ewp','test-tag'].includes(kind))return fail('Invalid register.');if(!canAccess(a,equipmentTab(kind)))return fail('Access denied.',403);const db=companyDb();if(!await db.prepare('SELECT id FROM projects WHERE id=? AND owner=?').bind(projectId,a.owner).first())return fail('Project unavailable.',404);const query=kind==='ewp'?"SELECT * FROM records WHERE owner=? AND ((project_id=? AND kind='ewp') OR (project_id='' AND kind='ewp-template')) ORDER BY created DESC":"SELECT * FROM records WHERE owner=? AND project_id=? AND kind='test-tag' ORDER BY created DESC";const rows=await db.prepare(query).bind(a.owner,projectId).all<any>();return NextResponse.json({items:rows.results.map(r=>({id:r.id,kind:r.kind,title:r.title,created:r.created,data:JSON.parse(r.data)}))})}catch(e){console.error(e);return fail('Could not load equipment records.',500)}}
export async function POST(req:NextRequest){try{const u=await getChatGPTUser();if(!u)return fail('Sign in required.',401);const a=await getCompanyAccess(u),b:any=await req.json(),kind=text(b.kind),db=companyDb();if(!equipmentTab(kind))return fail('Invalid equipment record.');if(!canAccess(a,equipmentTab(kind),true)||(kind==='ewp-template'&&a.role==='member'))return fail('Edit access is required. Shared templates are managed by administrators.',403);const projectId=kind==='ewp-template'?'':text(b.projectId),title=text(b.title,200);if(!title)return fail('Enter an equipment name.');if(kind!=='ewp-template'&&!await db.prepare('SELECT id FROM projects WHERE id=? AND owner=?').bind(projectId,a.owner).first())return fail('Project unavailable.',404);const old:any=b.id?await db.prepare('SELECT * FROM records WHERE id=? AND owner=? AND project_id=? AND kind=?').bind(text(b.id),a.owner,projectId,kind).first():null;if(b.id&&!old)return fail('Record unavailable.',404);const input=b.data||{},data:any={};for(const key of ['assetId','make','model','serial','location','operator','date','tester','nextDue','result','templateTitle'])data[key]=text(input[key],200);data.notes=text(input.notes,5000);if(!validDate(data.date)||!validDate(data.nextDue))return fail('Enter valid dates.');if(kind==='test-tag'){if(!data.assetId||!data.date||!data.tester||!['Pass','Fail'].includes(data.result))return fail('Enter the asset/tag ID, test date, tester and test result.');if(data.nextDue&&data.nextDue<data.date)return fail('Next test date cannot be before the test date.');}else{if(!Array.isArray(input.checks)||input.checks.length>40)return fail('Use up to 40 checklist items.');data.checks=input.checks.map((c:any)=>({label:text(c.label,200),result:kind==='ewp-template'?'Not checked':text(c.result)}));if(data.checks.some((c:any)=>!c.label||!checkResults.includes(c.result)))return fail('Name each checklist item and select a result.');if(kind==='ewp'&&!data.date)return fail('Enter the record date.');data.fileIds=kind==='ewp-template'?[]:Array.from(new Set((Array.isArray(input.fileIds)?input.fileIds:[]).map((id:unknown)=>text(id,100))));if(data.fileIds.length>20)return fail('Use up to 20 photos per record.');for(const id of data.fileIds)if(!await db.prepare("SELECT id FROM files WHERE id=? AND owner=? AND project_id=? AND category='ewp-photo'").bind(id,a.owner,projectId).first())return fail('A photo is unavailable for this project.');}
const previous=old?JSON.parse(old.data):{};if(old&&Number(b.version)!==(previous.version||1))return fail('This record changed elsewhere. Reopen it before saving.',409);data.version=(previous.version||0)+1;data.updated=new Date().toISOString();data.updatedBy=u.email;const id=old?.id||crypto.randomUUID();if(old){const result=await db.prepare('UPDATE records SET title=?,data=? WHERE id=? AND owner=? AND data=?').bind(title,JSON.stringify(data),id,a.owner,old.data).run();if(!result.meta.changes)return fail('This record changed elsewhere. Reopen it before saving.',409)}else await db.prepare('INSERT INTO records (id,owner,project_id,kind,title,status,data,created) VALUES (?,?,?,?,?,?,?,?)').bind(id,a.owner,projectId,kind,title,'',JSON.stringify(data),new Date().toISOString()).run();return NextResponse.json({id});}catch(e){console.error('Equipment save',e);return fail('Could not save the equipment record. Please retry.',500)}}
